회원, 비회원의 카페 정보 조회 API 개발
woowacourse-teams/2023-yozm-cafe pull request #100
Opened 2023-07-21 05:27 UTC by hum02

## #️⃣ 연관된 이슈

- close #83 

## 📝 작업 내용
- 비회원과 회원의 카페 정보 조회 API 엔드 포인트 분리
- 회원의 카페 정보 조회 API 구현 및 테스트

## 💬 리뷰 요구사항
- 비회원의 API url을 우선 `guest/cafes?page=1` 과 같이 구현했습니다. **비회원의 API url로 이것이 괜찮을지 논의해보면 좋을 것 같습니다**
- 기존의 CafeAcceptanceTest는 사실 CafeControllerTest랑 똑같다고 생각해서 해당 테스트를 CafeControllerTest로 이동해 합쳤습니다.
-  CafeConrollerTest에서 회원의 카페 조회 테스트를 위해 member와 UnViewedCafe를 저장하는 과정을 repositroy로 직접하고 메서드 분리했습니다. 테스트이기 때문에 jpa의 casacde, orphanRemoval옵션에 의지하지 않고 직접 db에 넣어주는 게 나을거라 생각했는데 괜찮을까요?

2023-07-23 06:10 UTC, nuyh99 requested changes
고생하셨습니다!!

> 비회원의 API url을 우선 guest/cafes?page=1 과 같이 구현했습니다. 비회원의 API url로 이것이 괜찮을지 논의해보면 좋을 것 같습니다

- 저는 페이지 번호를 PathVariable로 넣는 것이 좋을 것 같네요.
> 기존의 CafeAcceptanceTest는 사실 CafeControllerTest랑 똑같다고 생각해서 해당 테스트를 CafeControllerTest로 이동해 합쳤습니다.
- 모두 컨트롤러 테스트로 하면 통일되고 좋을 것 같네요! 근데 AcceptanceContext를 사용할 지 안할 지는 통일하면 좋겠습니다.

> CafeConrollerTest에서 회원의 카페 조회 테스트를 위해 member와 UnViewedCafe를 저장하는 과정을 repositroy로 직접하고 메서드 분리했습니다. 테스트이기 때문에 jpa의 casacde, orphanRemoval옵션에 의지하지 않고 직접 db에 넣어주는 게 나을거라 생각했는데 괜찮을까요?

- 인수테스트라면 잘못된 방식이고 컨트롤러 메서드의 로직을 테스트하기 위함이라면 개인 선호의 차이일 것 같습니다. 하지만 현재는 Cafe를 저장하는 방법이 Repository 밖에 없지 않나요?? 현재가 최선의 방법이라고 생각해요!

2023-07-23 06:10 UTC, nuyh99 commented on server/src/test/java/com/project/yozmcafe/controller/CafeControllerTest.java
> +        this.unViewedCafeCafeRepository.saveAll(allUnViewedCafes);
this는 없어도 될 것 같아요!

2023-07-23 08:28 UTC, donghae-kim requested changes
비회원의 API url을 우선 guest/cafes?page=1 과 같이 구현했습니다. 비회원의 API url로 이것이 괜찮을지 논의해보면 좋을 것 같습니다

> 저는 이대로 쿼리스트링으로 가져가는게 좋다고 생각합니다. 현재 page=1을통해서 필터링, 정렬? 등을 처리하는데 이는 pathvariable보다는 query string이 좀 더 적합합니다.

기존의 CafeAcceptanceTest는 사실 CafeControllerTest랑 똑같다고 생각해서 해당 테스트를 CafeControllerTest로 이동해 합쳤습니다.

> Good 근데 궁금한 것은 지금까지 사용하지 않던 AcceptanceContext 갑자기 사용하게 된 계기나 의도가 있나요 ? 프롤로그에서 고민없이 그대로 가져온 것 같아서 여쭤봅니다!

CafeConrollerTest에서 회원의 카페 조회 테스트를 위해 member와 UnViewedCafe를 저장하는 과정을 repositroy로 직접하고 메서드 분리했습니다. 테스트이기 때문에 jpa의 casacde, orphanRemoval옵션에 의지하지 않고 직접 db에 넣어주는 게 나을거라 생각했는데 괜찮을까요?

> 좀 더 정확한 로직의 테스트를 위해서는 사용한 jpa대로 구현하는 것이 좋지 않을까요 ?

2023-07-23 08:28 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeRepository.java
>  }
@Param을 왜 붙여야 하는지 아시는지 궁금합니다! 공부하고 공유해주시나요 ?? 폴로는 param 어노테이션을 오히려 지웠던데 서로 합의(?) 가 되었던 건지 궁금합니다.

2023-07-23 08:28 UTC, donghae-kim commented on server/src/test/java/com/project/yozmcafe/controller/CafeControllerTest.java
> +        assertThat(response.jsonPath().getList("$")).hasSize(5);
중요한 것은 반환값의 카페 정보 '값' 이라고 생각되는데 size만 확인하면 충분하다고 생각하시는지 궁금합니다.

2023-07-23 08:28 UTC, donghae-kim commented on server/src/test/java/com/project/yozmcafe/controller/CafeControllerTest.java
> +                .extract();
extract를 하지 않아도 response를 받아 모든 처리가 가능할 것 같은데 이렇게 진행하는 이유가 있을까요 ? 다른부분도 마찬가지입니다!

2023-07-23 08:28 UTC, donghae-kim commented on server/src/test/java/com/project/yozmcafe/controller/CafeControllerTest.java
> +                .toList();
unviewcafe에도 savedCafe, member만 받는 생성자를 오버로딩 해서 체이닝 방식으로 사용하는 것은 어떨까요 ?

2023-07-24 11:19 UTC, hum02 commented
> 저는 이대로 쿼리스트링으로 가져가는게 좋다고 생각합니다. 현재 page=1을통해서 필터링, 정렬? 등을 처리하는데 이는 pathvariable보다는 query string이 좀 더 적합합니다. 
 👍

 > Good 근데 궁금한 것은 지금까지 사용하지 않던 AcceptanceContext 갑자기 사용하게 된 계기나 의도가 있나요 ? 프롤로그에서 고민없이 그대로 가져온 것 같아서 여쭤봅니다!
- 기존 restAssured로 테스트를 작성하면 테스트 코드의 길이가 너무 길어져서 읽기 힘들다는 생각은 했었는데,
 template을 쓰는 게 나을 것 같다는 생각은 아래 글을 보고 하게되었는데요
 [달록 테스트 가독성 개선기](https://velog.io/@gudonghee2000/%EC%9D%BD%EA%B8%B0-%EC%A2%8B%EC%9D%80-%ED%85%8C%EC%8A%A4%ED%8A%B8-%EC%BD%94%EB%93%9C%EB%8A%94-%EC%86%8C%EC%84%A4-%EA%B0%99%EC%A7%80-%EC%95%8A%EC%9D%84%EA%B9%8C)
이 글을 보고 다른 프로젝트에서는 restAssured에 대한 가독성을 어떻게 개선했을까 찾아보니
[f12 테스트 utils](https://github.com/woowacourse-teams/2022-f12/tree/release/backend/src/test/java/com/woowacourse/f12/acceptance/support)
이런식으로 template을 쓰는 게 나을 것 같아보였습니다.
우선 프롤로그 걸  쓴 것은  팀원이 가장 익숙해보여서 채택했는데, 굳이 이것을 고수할 생각은 전혀 없습니다.
다만 restAssured에 대한 template은 무엇이든 있는게 가독성이 좋을 것 같네요!

> 좀 더 정확한 로직의 테스트를 위해서는 사용한 jpa대로 구현하는 것이 좋지 않을까요 ?
- 실제 서비스에서는 db에 unViewedCafe와 member가 저장된 상태에서 하기에 given절의 구성은 지금처럼
repository를 사용하는 게 정확하지 않을까요?
이에 대한 부분을 보다가 생각난 건데
```java
//authService

    @Transactional
    public TokenResponse createAccessToken(final String code, final OAuthProvider provider) {
        final MemberInfo memberInfo = provider.getUserInfo(code);

        final Member member = memberRepository.findById(memberInfo.openId())
                .orElseGet(() -> memberRepository.save(memberInfo.toMember()));

        return new TokenResponse(jwtTokenProvider.createAccessFrom(member.getId()));
    }
```
현재 이 부분에서 보이듯 새로운 member일 경우 member에게 unViewCafe까지 저장/할당해주는 로직이 아직 개발되지 않아
운영에서 하듯 unViewedCafe를 저장해주지 못했습니다. **이 기능 개발이 필요할 듯 해서 이슈도 새로 만들겠습니다**

2023-07-24 11:32 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeRepository.java
>  }
폴로하고 미리 합의 했으면 좋았을 텐데, 미리 애기하진 못했네요..
https://github.com/woowacourse-teams/2023-yozm-cafe/pull/96#discussion_r1271662452
위의 pr 대화에서 이번에 합의했습니다.

연어의 리뷰까지 반영해서 param을 붙이는 식으로 수정하려합니다

2023-07-25 01:49 UTC, hum02 commented on server/src/test/java/com/project/yozmcafe/controller/CafeControllerTest.java
> +    public void afterEach() {
값에 대한 검증을 하면서 random port로 통합테스트 시 격리가 잘 안되고 있다는 걸 알았습니다.
reference: 
https://mangkyu.tistory.com/264
[테스트 격리의 방법들](https://be-student.tistory.com/65#%ED%85%8C%EC%9D%B4%EB%B8%94%20%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%A5%BC%20%ED%95%A9%EB%A6%AC%EC%A0%81%EC%9C%BC%EB%A1%9C%20%EC%A0%9C%EA%B1%B0%ED%95%98%EB%8A%94%20%EB%B0%A9%EB%B2%95-1)
randomPort로 테스트 하면 별도의 스레드에서 테스트를 수행하기에 db의 rollback이 되지 않을 수 있습니다.

이 문제를 해결하는 방법으로는 안전장치로 h2테스트 db임을 확인한 후 truncate를 하는 방법이 있습니다.
그런데 현재 우리의 테스트 db는 mysql로 되어있어 h2로 확인할 수는 없겠고,
때문에 `@autoConfigurationTestDataBase`로 테스트 db임을 설정했습니다.

현재는 저장할 때마다  cafe1,cafe2.. 에 새로 할당하고 id로 값을 검증하는 방법으로 구현했습니다. 
이 방법 말고는 `@sql`을 활용해 쿼리로 truncate하는 방법이 있을 것 같습니다. 
어떤 방식이 좋을까요? 더 나은 방식이 있을까요?

2023-07-25 02:05 UTC, hum02 commented on server/src/test/java/com/project/yozmcafe/controller/CafeControllerTest.java
> +        assertThat(response.jsonPath().getList("$")).hasSize(5);
size 확인만으로는 불충분하네요..
값의 검증까지 추가하고 테스트 격리까지 추가했습니다.

2023-07-25 07:16 UTC, green-kong approved these changes
이전에 다른 분들이 남겨주신 리뷰를 적극적으로 반영해주셔서,
제가 딱히 남길 부분은 없는것같아요!
개인적인 의견들 몇개 남겨놓았습니다~

2023-07-25 07:16 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/controller/CafeController.java
> +    @GetMapping("/guest")
개인적인 의견인데요. 당장 변경하는건 아니더라도, guest가 뒤로 가는게 좀더 이쁘지 않을까 싶어요.

2023-07-25 07:16 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/controller/CafeController.java
> +    public ResponseEntity<List<CafeResponse>> getCafesWithMember(final Member member, @PageableDefault(size = 5) final Pageable pageable) {
현재 api 명세에 /cafes 로 uri가 수정되었고,
이 api에서 만들어지는 pageable은 size=5, page=0인 고정값으로 처리될 것 같은데,
Pageable을 queryParam으로 받는 방식보다는 controller 내부에서 직접 PageRequeste를 만드는 방식은 어떨까요?

2023-07-25 07:16 UTC, green-kong commented on server/src/test/java/com/project/yozmcafe/controller/CafeControllerTest.java
> +class CafeControllerTest {
테스트 엄청 꼼꼼하네요 👍👍👍

2023-07-25 07:16 UTC, donghae-kim approved these changes
고생하셨습니다

2023-07-25 07:26 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/controller/CafeController.java
> +    public ResponseEntity<List<CafeResponse>> getCafesWithMember(final Member member, @PageableDefault(size = 5) final Pageable pageable) {
회원의 카페 조회 API에서 /cafes?page=3
같이 page파라미터를 지정해야 하는 줄로 오해할 여지가 있으니 controller 구현부에서부터 page를 받지 말자는 의미이군요!
동의합니다. 수정하겠습니다.

2023-07-25 10:37 UTC, nuyh99 approved these changes
고생하셨습니다👍

2023-07-25 10:37 UTC, merged