프로필 기능 구현 (API 연동)
woowacourse-teams/2023-yozm-cafe pull request #134
Opened 2023-07-25 02:11 UTC by solo5star

## #️⃣ 연관된 이슈
close #132 

## 📝 작업 내용
<img height="700" src="https://github.com/woowacourse-teams/2023-yozm-cafe/assets/20203944/b02fe9f4-24f7-4771-bcbf-5341f141cbe5">

API에서 가져온 정보를 네비게이션 바, 프로필 화면에 표시하도록 기능 구현

## 💬 리뷰 요구사항
#131 이 먼저 머지된 후 머지되어야 합니다.

2023-07-25 04:16 UTC, jeongwusi requested changes
확인해주세여~!

2023-07-25 04:16 UTC, jeongwusi commented on client/src/hooks/useUser.ts
> +};
여기서 리액트 쿼리를 사용한 이유는 에러처리를 하게 위해서 사용한거죠? 아니면 다른 이유가 있나여?

2023-07-25 04:18 UTC, solo5star commented on client/src/hooks/useUser.ts
> +};
비동기 상태 관리를 하기 위함입니다. 지금은 성공의 경우만 고려하고 있지만, 향후 로딩, 실패의 경우까지 고려할 때 react-query로 통일을 시켜두었기 때문에 대응이 쉬울 거라 생각합니다.

2023-07-25 04:20 UTC, jeongwusi commented on client/src/hooks/useUser.ts
> +};
네네 좋습니다!

2023-07-25 04:20 UTC, jeongwusi approved these changes

2023-07-26 01:28 UTC, geuntaek1013 commented on client/src/hooks/useUser.ts
> +};
네 확인했습니다!!

2023-07-26 01:29 UTC, geuntaek1013 approved these changes
고생하셨습니다!!

2023-07-26 03:10 UTC, merged