백엔드 로그아웃 기능 구현
woowacourse-teams/2023-yozm-cafe pull request #147
Opened 2023-07-25 07:47 UTC by nuyh99

## #️⃣ 연관된 이슈
- closed #113

## 📝 작업 내용
- 로그아웃 컨트롤러 추가
- 리프레시 토큰 제거 테스트

2023-07-26 03:27 UTC, donghae-kim requested changes
고생하셨습니다

2023-07-26 03:27 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/controller/auth/AuthController.java
> +        final String accessToken = request.getHeader(AUTHORIZATION).replace(BEARER,"");
누가 작성했는지 잘 작성했네요 👍

2023-07-26 03:27 UTC, donghae-kim commented on server/src/test/java/com/project/yozmcafe/controller/auth/AuthControllerTest.java
> +    private AcceptanceContext request;
@Autowired로 의존성 주입한게 아닌 setup 한 이유가 있을 까요 ?

2023-07-26 04:04 UTC, green-kong approved these changes
수고하셨습니다!

2023-07-26 04:04 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/controller/auth/AuthController.java
> +    private static final String BEARER = "Bearer ";
상수화 좋아용👍

2023-07-26 04:04 UTC, green-kong commented on server/src/test/java/com/project/yozmcafe/controller/auth/AuthControllerTest.java
> +                .cookie("refreshToken", expectedDetail);
덕분에 RestAssuredMatcher의 존재를 알게되었네요! 🙇‍

2023-07-26 06:48 UTC, nuyh99 commented on server/src/test/java/com/project/yozmcafe/controller/auth/AuthControllerTest.java
> +    private AcceptanceContext request;
`AcceptanceContext` 내부에서 사용하는 request, response, storage 등을 초기화하기 위해서 했습니다.
현재는 Autowired로 받아도 문제가 없지만 추후에도 독립성을 보장하기 위해서 그렇습니다.

2023-07-26 11:33 UTC, hum02 approved these changes
고생하셨습니다~~

2023-07-26 11:33 UTC, hum02 commented on server/src/test/java/com/project/yozmcafe/controller/auth/AuthControllerTest.java
> +        request = new AcceptanceContext();
AcceptaneContext를 초기화 하는 방법! 좋네요

2023-07-26 11:33 UTC, hum02 commented on server/src/test/java/com/project/yozmcafe/service/auth/AuthServiceTest.java
> +@Transactional
test코드에 transactional이 붙어있는 거 일단은 롤백을 위해서라지만 제대로 된 테스트가 되지 않을 위험이 있을 것 같아요. 
springBootTest의 경우 데이터를 초기화할 다른 좋은 방법이 있을지 같이 고민해보면 좋지 않을까요?

2023-07-26 11:33 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/controller/auth/AuthController.java
> +    public ResponseEntity<Void> logout(final HttpServletResponse response) {
저는 로그아웃을 어떻게 구현할 지 잘 몰랐는데 token의 기간을 만료시키는 식으로 구현되나 보네요! 보고 배웁니다

2023-07-26 11:47 UTC, nuyh99 commented on server/src/test/java/com/project/yozmcafe/service/auth/AuthServiceTest.java
> +@Transactional
제대로된 테스트가 되지 않는다는 것이 잘 이해가 되지 않습니다!
1차 캐시를 유지하는 것이 이유라면 결국 테스트가 끝나면 모두 flush 되기 때문에 상관없지 않을까요??!

지금은 잘 와닿지 않는데 추가 설명해주실 수 있을까요ㅠㅠ?

2023-07-26 12:16 UTC, donghae-kim approved these changes
고생하셨습니다

2023-07-26 12:16 UTC, merged

2023-07-27 00:59 UTC, hum02 commented on server/src/test/java/com/project/yozmcafe/service/auth/AuthServiceTest.java
> +@Transactional
간단한 예시로는 변경감지를 이용하는 구현에 실수로 @transactional을 붙이지 않았을 때,
테스트에서 transactional이 붙어있다면 실패해야하는데 성공하는 경우가 있습니다!
또한
![image](https://github.com/woowacourse-teams/2023-yozm-cafe/assets/96762301/68506580-2a44-42fc-9918-2c17a58a0077)
이렇게 repository의 메서드들은 그 자체로 transactional이 붙어있습니다. 
실제 운영의 환경은 여러 트랜잭션이 끝나고, 이어서 실행되는 상황인데, 테스트에 transactional이 붙어있는다면 
위의 repositroy에 붙어있는 transactional을 상위의 하나의 트랜잭션으로 묶어버려서 운영과 다른 환경이 조성되는 것 같습니다. 

사례로는
![image](https://github.com/woowacourse-teams/2023-yozm-cafe/assets/96762301/e7e090ac-d64d-488e-a6b6-ecabf75012e9)
위 이미지의 경우 save의 트랜잭션이 테스트의 트랜잭션으로 묶여서 given의 구성이 커밋되지 않아 테스트가 실패하는 경우입니다.