좋아요 추가, 취소 API 개발
woowacourse-teams/2023-yozm-cafe pull request #152
Opened 2023-07-25 14:49 UTC by green-kong

## #️⃣ 연관된 이슈

> 연관된 이슈 번호를 모두 작성해주세요
> resolved #97 
> resolved #138 

## 📝 작업 내용

> #97 
> 좋아요 추가 취소API URI를 프론트와 협의 후 다음과 같이 변경하였습니다.`/cafes/{cafe_id}/likes?isLiked=true|false` 
> DB에서 좋아요가 되어있으면 좋아요 취소를, 반대의 경우는 좋아요 추가를 하려했으나,
> 프론트 측에서 좋아요 기능에 대해 `낙관적 업데이트`를 진행하기에,  
> 동일한 유저가 동일한 카페정보에 좋아요를 여러번 누르는 경우 하나의 요청이라도 정상적으로 처리되지않을 경우
> 사용자의 요청에 반대되는 결과가 일어날 수도 있다고 생각하여, 
> `QueryParam` 을 통해 *업데이트 하고 싶은 상태* 를 전달받아 처리하였습니다.
> 현재 서버측에서 좋아요가 되어있는지 확인 후, URI를 통해 전달 받은 값과 비교하여 두개의 값이 다른 경우에만 업데이트를 진행했습니다.

> #138 
> AuthControllerTest#loginWithKakao & loginWithGoogle 테스트 시,
> `AccessToken`이 정상적으로 반환되지 않는 문제가 있었습니다.
>  테스트에서 사용되는 `JwtProvider` 가 `@MockBean`으로 모킹되어있으나,
> 위 두 메서드에서 스터빙 되어있지 않아 정상적으로 동작하지 않는 문제였습니다.
> `JwtProvider`를 `@SpyBean`으로 모킹방식을 변경하였습니다.

## 💬 리뷰 요구사항

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요

2023-07-26 04:10 UTC, donghae-kim requested changes
고생하셨습니다~

2023-07-26 04:10 UTC, donghae-kim commented on server/src/test/java/com/project/yozmcafe/util/AcceptanceContext.java
> +    public void setAccessToken(String accessToken) {
사용하지 않는 메소드 인 것 같은데 제거하는게 어떨까요 ?

2023-07-26 04:10 UTC, donghae-kim commented on server/src/test/java/com/project/yozmcafe/controller/CafeControllerTest.java
> +    private void addLikedCafes() {
저는 개인적으로 위의코드랑 이코드들은 해당하는 메소드 하단에 위치하여 직관적으로 볼 수 있게 하는 편이긴 합니다

2023-07-26 04:10 UTC, donghae-kim commented on server/src/test/java/com/project/yozmcafe/domain/member/MemberTest.java
> +                IllegalArgumentException.class).hasMessage("존재하지 않는 내역입니다.");
변경전 개행 
구조가 낫지 않을까요 ??!
```suggestion
assertThatThrownBy(() -> member.removeUnViewedCafe(inValidUnViewedCafe))
.isInstanceOf(IllegalArgumentException.class)
.hasMessage("존재하지 않는 내역입니다.");
```

2023-07-26 04:10 UTC, donghae-kim commented on server/src/test/java/com/project/yozmcafe/util/LikeCafeRepository.java
> +public interface LikeCafeRepository extends JpaRepository<LikedCafe, Long> {
여기서만 사용하는 Repository를 만든 이유가 궁금합니다.
존재할필요가 없을 것 같아서요 ! 충분히 프로덕션 코드의 구조로 처리가능하지 않나요 ?

2023-07-26 04:13 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/controller/CafeController.java
> +    private final MemberService memberService;
좋아요를 하는 기능의 주체가 멤버에 있다고 생각했고,
해당 로직을 처리하기 위해 member인스턴스 내부의 동작에 의존하기 때문에 MemberService에서 
동작하는게 좀 더 타당하다고 생각했습니다!

2023-07-26 04:15 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/domain/member/Member.java
> +    public static final String UN_EXISTED_LIKED_CAFE = "존재하지 않는 좋아요 내역입니다.";
처음엔 UNEXISTED로 했는데 다 대문자로 되어있다보니 눈에 확 들어오는 느낌이 없더라구요.
`없다` 라는 부분이 눈에 확 들어오면 좋겠다 싶어 중간에 언더스코어 삽입했습니다.
음 근데 없다는 부분을 강조하고 싶으면, NO 또는 NOT 이 조금더 와닿는 느낌이네요

2023-07-26 04:17 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/domain/member/Member.java
> +        if (currentIsLike != isLiked && !isLiked) {
처음엔 그런식으로 작성했는데 if 분기가 3개가 되다보니 오히려 읽기가 불편한 느낌이더라구요.
주관적인 생각이다 보니 다른분들 의견도 들어보고 반영할게요!

2023-07-26 04:21 UTC, green-kong commented on server/src/test/java/com/project/yozmcafe/domain/member/MemberTest.java
> +                IllegalArgumentException.class).hasMessage("존재하지 않는 내역입니다.");
다른부분도 확인 후 반영할게요!👍

2023-07-26 06:27 UTC, green-kong commented on server/src/test/java/com/project/yozmcafe/util/LikeCafeRepository.java
> +public interface LikeCafeRepository extends JpaRepository<LikedCafe, Long> {
반영했습니다!

2023-07-26 10:59 UTC, nuyh99 requested changes
고생하셨습니다!!
제가 잘못 본 게 있다면 그냥 무시해주시고 괜찮다고 생각되면 반영해주세용가리

2023-07-26 10:59 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/domain/member/Member.java
> +    public static final String UN_EXISTED_LIKED_CAFE = "존재하지 않는 좋아요 내역입니다.";
말씀하신 대로 `NOT_EXISTED_~`가 좋아보여요!
그리고 하나가 public 인 것 같습니다!

2023-07-26 10:59 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/domain/member/Member.java
> +
```suggestion
public void updateLikedCafesBy(final Cafe cafe, final boolean isLiked){
    if(alreadySatisfiedBy(cafe, isLiked)){
        return;
    }
    
    if(isLiked){
        addLikedCafe(cafe); //cafe.like();도 addLikedCafe(cafe) 내부에서 실행
    }
    
    removeLikedCafe(cafe); //cafe.unlike()도 removeLikedCafe() 내부에서 실행
}

private boolean alreadySatisfiedBy(final Cafe cafe, final boolean isLiked){
    final boolean isLikedCafe = likedCafes.stream()
                                                      .anyMatch(likedCafe -> likedCafe.isSameCafe(cafe));
    
    return isLikedCafe == isLiked;
}
```
1. 처음 봤을 때 `updateIsLike` 라는 네이밍이 다소 와닿지 않았던 것 같아요! 그래서 위와 같은 네이밍은 어떨까 생각했습니다.
2. 오션 말처럼 현재 상태가 이미 만족하는 지 보고 리턴하면 좋을 것 같습니다.
3. 카페의 카운트를 줄이는 것은 remove~, add~ 메서드에 포함되면 좋을 것 같아요. 생명주기가 같다고 생각합니다.

2023-07-26 10:59 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/domain/member/Member.java
> +                .findAny()
`해당 필터에 대해 만족하는 무언가`를 찾는 것이라면 findAny()가 낫지 않을까요??
findFirst는 만족하는 여러 개가 있고 제일 첫 번째 것을 찾고 싶을 때 쓰면 좀 더 명확할 것 같다고 생각합니다.

2023-07-26 10:59 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/domain/member/Member.java
> +    }
개인적으로 `ifPresentOrElse()`로 처리하면 더 좋을 것 같아요!

2023-07-26 10:59 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/service/MemberService.java
> +    public void updateLike(final Member member, final long cafeId, final boolean isLiked) {
`updateLikedCafes()`가 네이밍이 더 와닿을 것 같습니다!!

그리고 유지보수 할 때를 생각해봤는데
카페 좋아요를 하기 위해서 어느 서비스를 찾아갈 것인지 생각해보면, `LikedCafeService` 등이 있는지 먼저 보고 `CafeService`를 그 다음으로 찾아갈 것 같아요!

2023-07-26 10:59 UTC, nuyh99 commented on server/src/test/java/com/project/yozmcafe/controller/CafeControllerTest.java
> +
저는 약간 이 부분이 이해하기가 느렸습니다.(`cur` 때문일수도...?)
스트림으로 찾기보다는 `cafeResponses`까지만 받아두고
```java
final CafeResponse expected = new CafeResponse(~);
```
위와 같은 expected 객체를 가지고 검증문에서 cafeResponses가 해당 객체를 포함하는 지 보면 어떨까요?!

2023-07-26 10:59 UTC, nuyh99 commented on server/src/test/java/com/project/yozmcafe/domain/member/MemberTest.java
> +    public static Stream<Arguments> provideMemberAndIsLiked() {
이건 혹시 쓰이고 있는 메서드인가요?
제 인텔리제이에서 버그 때문인지 안 쓰인다고 뜨네요...! 제 문제라면 무시해주세요!!

2023-07-26 10:59 UTC, nuyh99 commented on server/src/test/java/com/project/yozmcafe/service/MemberServiceTest.java
> +    @DisplayName("member의 likedCafes에 cafeId에 해당하는 카페가 존재하지 않고, isLiked가 true인 경우 likedCafes에 카페를 추가한다.")
기존 상태와 동일하면 바뀌지 않는 테스트도 있으면 좋을 것 같아요!

2023-07-26 11:22 UTC, hum02 reviewed
고생했어요 폴로~~

2023-07-26 11:22 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/controller/CafeController.java
> +    public ResponseEntity<Void> updateLikes(Member member, @PathVariable("cafeId") final long cafeId,
사소하지만 Member에 final이 안 붙어있네요!

2023-07-26 11:22 UTC, hum02 commented on server/src/test/java/com/project/yozmcafe/controller/CafeControllerTest.java
> +        given(jwtTokenProvider.getMemberId(anyString())).willReturn("memberId");
"토큰"보다 더 적절한 이름이네요

2023-07-26 12:18 UTC, donghae-kim approved these changes
고생하셨습니다 폴로 ~

2023-07-27 00:41 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/controller/CafeController.java
> +    public ResponseEntity<Void> updateLikes(Member member, @PathVariable("cafeId") final long cafeId,
사소하지 않아요! 감사합니다!

2023-07-27 00:42 UTC, green-kong commented on server/src/test/java/com/project/yozmcafe/controller/CafeControllerTest.java
> +        given(jwtTokenProvider.getMemberId(anyString())).willReturn("memberId");
memberId를 "토큰"이라고 해놓은 사람은 정말 센스가 없는것 같아요ㅎㅎ

2023-07-27 00:55 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/domain/member/Member.java
> +
1. 훨씬 좋은네이밍인 듯 해요!
2. 중론이 그러니 반영하겠습니다 ㅎㅎ
3. 오... 생각도 못했는데 백프로 동의합니다!

2023-07-27 02:16 UTC, green-kong commented on server/src/test/java/com/project/yozmcafe/controller/CafeControllerTest.java
> +
변수명 고민하다가 cur로 박아둔게 그대로 커밋됐네요.. ㅠ
CafeResponse dto 자체가 너무커서 이걸 직접 만드는 것보다 현재 상태가 좀더 깔끔하다고 느꼈습니다.

2023-07-27 02:17 UTC, green-kong commented on server/src/test/java/com/project/yozmcafe/domain/member/MemberTest.java
> +    public static Stream<Arguments> provideMemberAndIsLiked() {
위에 있는 @MethodSource 테스트에서 사용하고 있어요~

2023-07-27 02:23 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/service/MemberService.java
> +    public void updateLike(final Member member, final long cafeId, final boolean isLiked) {
저어는... 멤버로 갈거 같아요....
네이밍은 수정했습니다!

2023-07-27 04:15 UTC, nuyh99 approved these changes
고생하셨습니다!!

2023-07-27 05:55 UTC, merged