좋아요 목록 조회 기능 구현
woowacourse-teams/2023-yozm-cafe pull request #162
Opened 2023-07-26 05:27 UTC by donghae-kim

## #️⃣ 연관된 이슈

> close #115 

## 📝 작업 내용

> 사용자가 좋아요한 목록을 Slice 타입으로 받은 후 반환해 준다.(현재 10개 디폴트 값)

## 💬 리뷰 요구사항

> 테스트 쪽에 db 초기화를 위해 truncate sql을 사용했습니다. 더 좋은 방법이 있을까요 ?

2023-07-26 11:44 UTC, nuyh99 requested changes
고생하셨습니다!!
계속 코드 리뷰를 하니 집중력이 떨어져서 잘못 본 게 있을 수도 있습니다ㅠㅠ

2023-07-26 11:44 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/Images.java
> +    private static final Integer REPRESENTATIVE_INDEX = 0;
Integer로 하신 이유가 있을까요?!

2023-07-26 11:44 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/domain/member/MemberRepository.java
> +    Slice<LikedCafe> findLikedCafeByMemberId(@Param("memberId") final String memberId, final Pageable pageable);
`findLikedCafesByMemberId`
복수형이면 좋을 것 같네요!

2023-07-26 11:44 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/service/MemberService.java
> +    }
```suggestion
return likedCafes.stream()
    .map(LikedCafeResponse::from)
    .toList();
```
위와 같은 형태면 좋을 것 같습니다!

2023-07-26 11:44 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/service/MemberService.java
> +
위 `findById()`에서도 동일한 로직이 보이는데 `findMemberOrThrow()` 등의 메서드로 분리하면 어떨까요?!

2023-07-26 11:44 UTC, nuyh99 commented on server/src/test/java/com/project/yozmcafe/controller/MemberControllerTest.java
> +
context.response를 Response response에 대입하는데 context의 response 객체가 매번 달라지나 보군요! 감사합니당

2023-07-26 11:44 UTC, nuyh99 commented on server/src/test/java/com/project/yozmcafe/domain/cafe/ImagesTest.java
> +        assertThatThrownBy(images::getRepresentativeImage).isInstanceOf(IllegalArgumentException.class);
추후 커스텀 예외를 생각해서 hasMessage()를 하지 않으신건가요?!

2023-07-26 11:44 UTC, nuyh99 commented on server/src/test/java/com/project/yozmcafe/service/MemberServiceTest.java
> +    @DisplayName("멤버에 해당하는 좋아요 카페 목록을 조회한다.")
(Optional) 멤버가 좋아요한 카페 목록을 조회한다

2023-07-26 11:44 UTC, nuyh99 commented on server/src/test/java/com/project/yozmcafe/service/MemberServiceTest.java
> +    }
1. //then이 있으면 좋을 것 같습니다!
2. List의 사이즈가 1이고, isEqualTo로 id를 비교하는 Assertion이 아닌 for-each문으로 위와 같이 작성하신 이유가 무엇인가요!

2023-07-26 11:44 UTC, nuyh99 commented on server/src/test/java/com/project/yozmcafe/service/MemberServiceTest.java
> +                .isInstanceOf(IllegalArgumentException.class);
앞서 말했지만 표준 예외의 경우 hasMessage()까지 검증하는 것이 좋다고 생각하는데 커스텀 예외 때를 생각하신 건지 궁금해요.

2023-07-26 12:47 UTC, hum02 approved these changes
고생하셨슴다~~

2023-07-26 12:47 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/service/MemberService.java
> +    public List<LikedCafeResponse> findLikedCafesById(final String memberId, Pageable pageable) {
소소하게 pageable 앞에 final 붙여주기!

2023-07-26 12:47 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/Images.java
> +            throw new IllegalArgumentException("카페 이미지가 존재하지 않습니다.");
IllegalArument예외보다는 IllegalStateException이 더 적절해보이는 듯해요!

2023-07-26 12:47 UTC, hum02 commented on server/src/test/java/com/project/yozmcafe/controller/MemberControllerTest.java
> +@Sql(scripts = {"classpath:truncate.sql"}, executionPhase = AFTER_TEST_METHOD)
이 부분에서 trucate.sql을 사용했네요!
이 상태에서는 profile설정을 잘못하고 truncate.sql로 초기화를 하면 운영의 db가 날아갈 수도 있어서 autoConfigureTestDatabase같은 어노테이션으로 테스트db임을 확실히하고 사용하던지, 인메모리db라면 h2 db인지 확인하고 사용하던지의 안전장치가 있는게 나을 것 같아요!

저는 deleteAll을 하던 truncate를 하던 큰 차이는 없다고 생각하지만 테스트들에서 통일은 해야할 것 같아서 의논해보아야겠네요

2023-07-26 13:44 UTC, solo5star commented
왜 제가 리뷰어로 되어있죠?

2023-07-27 01:45 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/domain/cafe/Images.java
> +    private static final Integer REPRESENTATIVE_INDEX = 0;
코테만 하다 보니 익숙해져버린 래핑클래스 ..

2023-07-27 01:54 UTC, green-kong requested changes
수고하셨습니다~ 코멘트 몇개 남겼는데 확인 부탁드릴게요~

2023-07-27 01:54 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/service/MemberService.java
> +                .map(cafe -> new LikedCafeResponse(cafe.getId(), cafe.getRepresentativeImage())).toList();
개취의 영역인거 같긴한데, 전 stream 이후는 개행을 한번씩 해주는게 가독성이 더 좋다고 생각합니다.

2023-07-27 01:54 UTC, green-kong commented on server/src/test/java/com/project/yozmcafe/controller/MemberControllerTest.java
> +        );
1, 2 직접 넣는 것 보다, 위에 저장된 savedCafe1, savedCafe2의 id값으로 검증하는게 좀더 유연한 테스트가 될것같아요!

2023-07-27 01:54 UTC, green-kong commented on server/src/test/java/com/project/yozmcafe/controller/MemberControllerTest.java
> +                () -> assertThat(response.jsonPath().getBoolean("empty")).isTrue()
dto의 내용이 바뀌었는데, 테스트에는 반영이 안된것 같아요~

2023-07-27 01:54 UTC, green-kong commented on server/src/test/java/com/project/yozmcafe/service/MemberServiceTest.java
> +    }
size가 1인데 for문으로 검증을 할 필요가 있을까요..?
size가 변경됐을 때의 경우를 위함이었다면,
저라면 size를 변수에 할당하고, size를 검증하는 방식으로 할것 같아요!

2023-07-27 01:54 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/service/MemberService.java
> +                .map(cafe -> new LikedCafeResponse(cafe.getId(), cafe.getRepresentativeImage())).toList();
정팩메 쓰면 좀더 코드 깔끔해질듯요!

2023-07-27 01:57 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/service/MemberService.java
> +    }
좋아용

2023-07-27 01:59 UTC, donghae-kim commented on server/src/test/java/com/project/yozmcafe/domain/cafe/ImagesTest.java
> +        assertThatThrownBy(images::getRepresentativeImage).isInstanceOf(IllegalArgumentException.class);
커스텀 예외를 처리할 경우에 에러타입과 에러메세지 모두 변경될 것 같아서 굳이 지금 hasMessage사용할 필요가 없을 것 같아 가볍게만 진행했습니다. (추후 또 수정해야할 필요가 있어서)

2023-07-27 02:03 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/service/MemberService.java
> +
좀 더 명확하게 `findMemberByIdOrElseThrow` 로 변경하였습니다

2023-07-27 02:11 UTC, donghae-kim commented on server/src/test/java/com/project/yozmcafe/service/MemberServiceTest.java
> +    }
1. 감사합니다~
2. 처음 의도는 여러개의 좋아요한 데이터를 비교해보려고 했었는데 단일 assertThat으로 수정하였습니다

2023-07-27 02:17 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/service/MemberService.java
> +                .map(cafe -> new LikedCafeResponse(cafe.getId(), cafe.getRepresentativeImage())).toList();
저는 코드 길이가 120컬럼 이내이면 개행을 따로 처리하진 않았는데 개행하는게 가독성이 더 좋을것 같네요

2023-07-27 02:17 UTC, donghae-kim commented on server/src/test/java/com/project/yozmcafe/controller/MemberControllerTest.java
> +        );
구우우웃

2023-07-27 02:21 UTC, donghae-kim commented on server/src/test/java/com/project/yozmcafe/controller/MemberControllerTest.java
> +                () -> assertThat(response.jsonPath().getBoolean("empty")).isTrue()
헉 꼼꼼한 폴로 👍

2023-07-27 02:23 UTC, donghae-kim commented on server/src/test/java/com/project/yozmcafe/service/MemberServiceTest.java
> +    }
사실 원래 의도는 여러개의 Cafe를 추가해놓고 테스트 할 예정이었습니다. 근데 1개의 데이터만 넣어서 진행했기에 코드 수정하였습니다~

2023-07-27 02:46 UTC, donghae-kim commented on server/src/test/java/com/project/yozmcafe/controller/MemberControllerTest.java
> +@Sql(scripts = {"classpath:truncate.sql"}, executionPhase = AFTER_TEST_METHOD)
저는 deleteAll을 하게 될 경우 의존하는 repository가 많으면 하나하나 관리해주어야 하는 불편함이 있을 것 같았습니다.
그리고 외래키를 고려해주지 않으면 삭제 안될 가능성도 있을 것 같습니다!

또한 운영 db가 삭제되지는 않을 것 같다고 생각한게 운영환경에서 test코드가 작동하지 않고 빌드된 파일을 넘겨서 그럴 일이 없다고 생각했습니다.

2023-07-27 08:13 UTC, nuyh99 approved these changes
CONFLICT!

2023-07-27 08:19 UTC, green-kong approved these changes
수고하셨어용

2023-07-27 08:20 UTC, merged