새로운 멤버 저장 시 모든 unviewedCafe들도 저장하는 기능 구현
woowacourse-teams/2023-yozm-cafe pull request #164
Opened 2023-07-26 06:09 UTC by hum02

## #️⃣ 연관된 이슈

> resolved #126 

## 📝 작업 내용

> 새로운 멤버 저장 시 그 시점의 모든 cafe들을 멤버의 unviewedCafe로 저장한다.

## 💬 리뷰 요구사항

기존의 authControllerTest가 깨져서 수정했습니다.
![기존 oauth테스트 터짐](https://github.com/woowacourse-teams/2023-yozm-cafe/assets/96762301/74ff0ff3-a931-4e16-a04a-c4685c552d48)
mokc한 Repositroy라 member를 save()해주지 못해서 발생하기에, spyBean으로 변경했습니다.

2023-07-26 11:11 UTC, nuyh99 approved these changes
고생하셨습니다!!
간단한 것만 남겼는데 자유롭게 반영해주시고 approve 하겠습니다.

2023-07-26 11:11 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/service/auth/AuthService.java
> +    private Member saveNewMember(final MemberInfo memberInfo) {
`saveNewMemberWithAllCafes`로 하면 메서드의 역할이 잘 드러날 것 같습니다!

2023-07-26 12:29 UTC, donghae-kim requested changes

2023-07-26 12:29 UTC, donghae-kim commented on server/src/test/java/com/project/yozmcafe/service/auth/AuthServiceTest.java
> +        final List<Member> members = memberRepository.findAll();
findAll로 가져온 이유가 있을까요?
findById로 찾아온 이후에 list에서 뺄 필요 없이 바로 UnviewedCafe볼 수 있을 것 같아서요 !
그리고 has Size로 테스트하는것은 무의미 한 것 같습니다.

2023-07-27 01:34 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/service/auth/AuthService.java
> +    private Member saveNewMember(final MemberInfo memberInfo) {
짱입니다

2023-07-27 02:09 UTC, hum02 commented on server/src/test/java/com/project/yozmcafe/service/auth/AuthServiceTest.java
> +        final List<Member> members = memberRepository.findAll();
findById로 조회하는게 size로 단순히 새롭게 저장되었다고 생각하고 넘어가는 것보다 정확할 것 같네요!
반영하겠습니다.

2023-07-27 04:02 UTC, green-kong requested changes
간단한 코멘트 하나 남겼습니다!

2023-07-27 04:02 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/service/auth/AuthService.java
> +    }
cafeRepository 에서 모든 카페정보를 가져온 뒤, member에 넣어주는 방식이네요!
그런데 이렇게 되면 cafeRepository에 저장된 순서로 삽입이 되고, 카페 정보를 조회할 때도 순서대로 보여질 것 같아요.
신규 회원이라 저희 서비스에 대한 경헙이 없기 때문에, 순서대로 보여줘도 괜찮다고 판단하신 걸까요?

음 그런데, 비회원으로 사용을하다가 회원가입을 하게되면 비회원일 때 보던 순서와 동일한 순서로 보여질 것 같다는 생각이 드네요ㅎㅎ
저희가 CafeHistoryService 에서 구현한 것 처럼 shuffle을 한 뒤 삽입하는건 어떨까요??

2023-07-27 04:04 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/service/auth/AuthService.java
> +    }
날카로운 피드백입니다. 반영하겠습니다!

2023-07-27 04:33 UTC, donghae-kim requested changes

2023-07-27 04:33 UTC, donghae-kim commented on server/src/test/java/com/project/yozmcafe/service/auth/AuthServiceTest.java
> +        assertAll(
테스트가 한개인데 assertAll을 사용안해도 되지 않을까요?

2023-07-27 04:54 UTC, green-kong approved these changes
반영해줘서 고마워용~

2023-07-27 04:54 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/service/auth/AuthService.java
> +        Collections.shuffle(allCafes);
굿 👍

2023-07-27 05:59 UTC, hum02 commented on server/src/test/java/com/project/yozmcafe/service/auth/AuthServiceTest.java
> +        assertAll(
반영했습니다!

2023-07-27 08:18 UTC, donghae-kim approved these changes
고생하셨습니다!

2023-07-27 08:30 UTC, merged