요청 URI 로깅 필터 구현
woowacourse-teams/2023-yozm-cafe pull request #165
Opened 2023-07-26 06:33 UTC by nuyh99

## #️⃣ 연관된 이슈
- closed #130

## 📝 작업 내용
- logback 작성
  - 콘솔 출력
  - 파일 출력(경로: server/logs)

2023-07-26 07:45 UTC, green-kong requested changes
코멘트 남겼습니다! 확인해주세용

2023-07-26 07:45 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/controller/LoggingFilter.java
> +        logger.info("Request For '{}'", request.getRequestURI());
하는김에 얘도 상수화 해버리는건 어떨까요?

2023-07-26 07:45 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/controller/LoggingFilter.java
> +        return UUID.nameUUIDFromBytes(authorization.getBytes()).toString();
AccessToken으로 UUID를 만드네요!
그런데 사용자가 서비스를 이용하는 도중에 AccessToken이 만료되면 RefreshToken을 통해 새로운 AccessToken이 발급 된다면,
로그에 남을 때는 다른 사용자처럼 보이지 않을까요?
Token을 Decode해서 Token안에 들어있는 사용자 정보를 이용해 UUID를 만드는 건 어떨까요?

2023-07-26 07:45 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/controller/LoggingFilter.java
> +        return UUID.nameUUIDFromBytes(authorization.getBytes()).toString();
이렇게 하면 토큰이 새로 발급되어도 같은 사용자로 로그가 남기때문에,
하루에 몇명의 이용자가 이용하는지도 확인해볼수 있을것 같아요!

2023-07-26 12:24 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/controller/LoggingFilter.java
> +        logger.info("Request For '{}'", request.getRequestURI());
해당 메시지는 다른 곳에서 반복 사용될 곳이 없고, `{}` 이게 몇 개가 있는 지, 어느 위치에 존재하는 지를 보기는 지금이 좋지 않을까 싶습니다! 
공통된 에러 메시지가 아닌 이상 상수화하지 않는 경우랑 같은 것 같아요.
물론 제 개인적인 기준입니다! 틀린 부분이 있다면 알려주시면 반영하겠습니다!!

2023-07-26 13:11 UTC, donghae-kim approved these changes

2023-07-26 13:11 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/controller/LoggingFilter.java
> +        logger.info("Request For '{}'", request.getRequestURI());
단순하게 궁금한건데 getUserFrom에서 받아온 autorization 정보는 사용하지 않는 건가요 ??

2023-07-27 01:16 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/controller/LoggingFilter.java
> +        logger.info("Request For '{}'", request.getRequestURI());
MDC(Mapped Diagnostic Context)라는 게 있더라구요!

2023-07-27 01:24 UTC, hum02 approved these changes
로깅 감사합니다~~

2023-07-27 01:24 UTC, hum02 commented on server/src/main/resources/logback-spring.xml
> +                %d{yyyy-MM-dd HH:mm:ss} | %t | [USER: %X{user}] | %highlight(%-5p) | %cyan(%logger{0}) | %m%n
이런 방식으로 MDC에서 가져오나 보네요! 연 선생님 많이 배웁니다

2023-07-27 01:30 UTC, green-kong approved these changes

2023-07-27 06:37 UTC, merged