redirectAuthorizationUri 제공 코드 수정
woowacourse-teams/2023-yozm-cafe pull request #170
Opened 2023-07-26 09:56 UTC by donghae-kim

## #️⃣ 연관된 이슈

> close #163 

## 📝 작업 내용

> redirectAuthorizationUri을 현재 @GetMapping("/{providerName}") 이렇게 받으면 바로 서버가 만든 uri로 카카오,구글로 날려주었습니다. 그래서 모든 enum 타입에 있는 것을 list로 보내게되었습니다.

근데 솔스가 모킹이 어렵다고 그 주소를 클라이언트로 보내달래요.ㅠ

## 💬 리뷰 요구사항

> 최대한 추상화 수준 유지한 상태로 짰어요

2023-07-26 09:56 UTC, solo5star commented
징징대지 마세요

2023-07-26 11:21 UTC, nuyh99 approved these changes
고생하셨습니다!!
간단한 코멘트만 남겨서 반영은 자유롭게 해주시고 Approve 하겠습니다!

2023-07-26 11:21 UTC, nuyh99 commented on server/src/test/java/com/project/yozmcafe/controller/auth/AuthControllerTest.java
>                  .redirects().follow(false)
이 구문도 계속 필요한 지 궁금합니다!

2023-07-26 11:21 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/service/auth/AuthService.java
> +                .map(it -> new AuthorizationUrlDto(it.name(), it.getAuthorizationUrl()))
it 대신에 provider가 더 좋을 것 같습니다!

2023-07-26 11:43 UTC, hum02 approved these changes
로그인 아저씨 감사합니다

2023-07-26 11:43 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/controller/auth/AuthController.java
> +    public ResponseEntity<List<AuthorizationUrlDto>> getRedirectAuthorizationUrl() {
사소하지만 controller의 메서드명도 getRedirectAuthorizationUrl`s`` 로 바꾸는 게 list를 반환하는 것에 더 맞을 것 같아요!

2023-07-26 11:55 UTC, solo5star commented on server/src/main/java/com/project/yozmcafe/service/auth/AuthService.java
> +                .map(it -> new AuthorizationUrlDto(it.name(), it.getAuthorizationUrl()))
코틀린 향기... 굿~~

2023-07-26 11:55 UTC, solo5star commented on server/src/main/java/com/project/yozmcafe/controller/auth/AuthController.java
> +    public ResponseEntity<List<AuthorizationUrlDto>> getRedirectAuthorizationUrl() {
저도 그렇게 생각합니다

2023-07-27 01:27 UTC, donghae-kim commented on server/src/test/java/com/project/yozmcafe/controller/auth/AuthControllerTest.java
>                  .redirects().follow(false)
redirects에서 변경되어서 필요없다고 판단되어 삭제했습니다~

2023-07-27 01:29 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/service/auth/AuthService.java
> +                .map(it -> new AuthorizationUrlDto(it.name(), it.getAuthorizationUrl()))
it이 익숙해진 나머지 ..

2023-07-27 01:31 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/controller/auth/AuthController.java
> +    public ResponseEntity<List<AuthorizationUrlDto>> getRedirectAuthorizationUrl() {
good~~~~~~

2023-07-27 04:34 UTC, green-kong requested changes
테스트 관련해서 코멘트 하나 남겨두었습니다!
확인해주세용~

2023-07-27 04:34 UTC, green-kong commented on server/src/test/java/com/project/yozmcafe/controller/auth/AuthControllerTest.java
>      }
현재 이 API 가 List로 응답하는 걸로 보이는데요.
`response.getBody().jsonPath().getString("authorizationUrl")`의 반환값이  String 타입으로`"[카카오 url, 구글 url]"` 이렇게 되지 않나요?  
리스트에 있는 dto중에 하나만 `"response_type", "redirect_uri", "client_id", "scope"`이 값들을 contain 하고 있어도 테스트가 통과될것 같은데,
의도하신 부분일까요??

2023-07-27 06:17 UTC, donghae-kim commented on server/src/test/java/com/project/yozmcafe/controller/auth/AuthControllerTest.java
>      }
의도하진 않았는데 놓쳤던 것 같습니다!

enum 타입 추가되어도 계속해서 테스트가 가능하도록 수정하였습니다!

2023-07-27 08:00 UTC, green-kong approved these changes
수고하셨어요오옹

2023-07-27 08:00 UTC, merged