좋아요한 카페 목록을 보여주도록 구현한다.
woowacourse-teams/2023-yozm-cafe pull request #173
Opened 2023-07-27 02:01 UTC by jeongwusi

## #️⃣ 연관된 이슈

> 연관된 이슈 번호를 모두 작성해주세요

close #110 

## 📝 작업 내용

- [getLikedCafeList라는 이름으로 fetch 추상화](https://github.com/woowacourse-teams/2023-yozm-cafe/commit/cacd54aaf509efb449c79d597f0a8519bb3e7262)
- [LikedCafeList 컴포넌트에서 실제 데이터를 불러올 수 있도록 값 수정](https://github.com/woowacourse-teams/2023-yozm-cafe/commit/cf00f6d22c44e15e228ede162c11a7f528688120)
- [좋아요한 카페 리스트 목업 데이터 추가](https://github.com/woowacourse-teams/2023-yozm-cafe/commit/88515443ae08700825ec538e4b9a17fa05270e01)
- [좋아요한 목록의 무한스크롤 기능 추가](https://github.com/woowacourse-teams/2023-yozm-cafe/commit/bf2848bc442f410f1e10f78c5c9252fd4c5d9a1d)
- [좋아요한 카페 목록의 MSW 핸들러 수정](https://github.com/woowacourse-teams/2023-yozm-cafe/commit/e0ece6dd4e9b8dbc1aa0577fd67b4fbc67ebaa72)
- [MyProfile 컴포넌트의 무한 스크롤 실행할 수 있는 기능 추가](https://github.com/woowacourse-teams/2023-yozm-cafe/commit/8809c99f753545ef03421ccf9663ba5ac52536ac)
- [Outlet에 Suspense 추가](https://github.com/woowacourse-teams/2023-yozm-cafe/commit/375c9c865cac71405a3a2510a3ab20ab4aef1d0b)
- [LikedCafe 타입 추가](https://github.com/woowacourse-teams/2023-yozm-cafe/commit/2ca4410d707bb6c1a66e49ec97d228bf0dda9aba)

## 💬 리뷰 요구사항

2023-07-27 02:29 UTC, solo5star requested changes

2023-07-27 02:29 UTC, solo5star commented on client/src/pages/MyProfile.tsx
> +      console.log('하하하');
```suggestion
```
하하하

2023-07-27 02:29 UTC, solo5star commented on client/src/pages/MyProfile.tsx
> +    }
`useIntersection` 훅이 아니라 scroll 이벤트로 하신 이유가 있으실까용? (궁금)

2023-07-27 02:29 UTC, solo5star commented on client/src/pages/Root.tsx
> +        </Suspense>
임시 방편으로 Suspense를 걸어두었지만 향후 근본적으로 해결하는 방법을 찾을 수 있다면 좋을 듯 합니다

2023-07-27 05:03 UTC, jeongwusi commented on client/src/pages/Root.tsx
> +        </Suspense>
넹넹

2023-07-28 12:48 UTC, geuntaek1013 approved these changes
고생하셨습니다!! 리뷰 확인 부탁드립니다:)

2023-07-28 12:48 UTC, geuntaek1013 commented on client/src/pages/Root.tsx
> +        <Suspense>
`Outlet`에 `Suspense` 추가는 왜 하셨는지 알 수 있을까요?

2023-07-28 12:48 UTC, geuntaek1013 commented on client/src/mocks/handlers.ts
> +    const PAGINATE_UNIT = 15;
`const PAGINATE_UNIT = 15` 15로 변경하신 이유가 무엇인가요?

2023-07-28 13:18 UTC, jeongwusi commented on client/src/mocks/handlers.ts
> +    const PAGINATE_UNIT = 15;
백엔드랑 15개로 맞추기로 하였습니당!

2023-07-28 13:21 UTC, jeongwusi commented on client/src/pages/Root.tsx
> +        <Suspense>
데이터가 준비가 되지 않는 경우 리액트에게 알려주기 위해 Suspense가 필요합니다~

2023-07-28 13:39 UTC, solo5star approved these changes

2023-07-28 13:39 UTC, merged