OAuth 페이지 URL을 API에서 받도록 하고, 모킹하여 백엔드 없이 로그인 플로우가 동작하도록 구현
woowacourse-teams/2023-yozm-cafe pull request #178
Opened 2023-07-27 06:18 UTC by solo5star

## #️⃣ 연관된 이슈
close #168 

## 📝 작업 내용
* /api/auth/urls API 엔드포인트에서 OAuth 페이지 로그인 URL들을 받아 로그인 페이지에 표시하도록 하였음
* /api/auth/urls을 모킹하여 백엔드 서버를 띄우지 않아도 로그인 플로우를 테스트 할 수 있게 하였음

## 💬 리뷰 요구사항

2023-07-27 06:24 UTC, jeongwusi requested changes
확인해주세요~!

2023-07-27 06:24 UTC, jeongwusi commented on client/src/components/Navbar.tsx
> +      <Suspense>{isModalOpen && <Modal onClose={closeModal} />}</Suspense>
여기에 Suspense가 필요한가요??

2023-07-27 06:28 UTC, solo5star commented on client/src/components/Navbar.tsx
> +      <Suspense>{isModalOpen && <Modal onClose={closeModal} />}</Suspense>
`<Modal />` 에서 useQuery를 사용하기 때문입니다. 쿼리가 로딩중일 시 렌더링이 모두 완료되지 않고 `throw promise` 처리가 되기 때문에 이를 catch할 `<Suspense />` 가 있어야 합니다.

2023-07-27 06:30 UTC, jeongwusi approved these changes

2023-07-28 12:44 UTC, geuntaek1013 approved these changes
고생하셨습니다!!🥹

2023-07-28 13:02 UTC, merged