회원 카페 조회 API - 이미 본 것 제외하고 랜덤한 페이지의 카페를 응답하는 기능 구현
woowacourse-teams/2023-yozm-cafe pull request #192
Opened 2023-07-28 06:34 UTC by hum02

## #️⃣ 연관된 이슈

> resolved #187 

## 📝 작업 내용

> 우선 운영에 카페들이 중복되지 않게 조회되는 상태로 설문하는 게 필요할 듯 해서 최대한 간단하게 구현했습니다.

## 💬 리뷰 요구사항

테스트 코드 짜보려고 했는데 랜덤성이라 이미 본 카페가 겹칠 수도 있고 안 겹칠 수도 있어서 우선 미루려고 합니다.

2023-07-28 07:18 UTC, green-kong requested changes

2023-07-28 07:18 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/service/CafeService.java
> +        Page<Cafe> cafePage = cafeRepository.findUnViewedCafesByMember(pageable, member.getId());
굳이 이걸 Page받을 필요가 없을것 같아요!
저라면 전체 (목록 수 / SIZE )+ 1 을 해서 전체 페이지 갯수를 계산하는 방식으로 할것 같네요!

2023-07-28 08:08 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/service/CafeService.java
> +        Page<Cafe> cafePage = cafeRepository.findUnViewedCafesByMember(pageable, member.getId());
반영했습니다

2023-07-29 05:32 UTC, nuyh99 requested changes
고생하셨습니다!!!

최대한 생각해보면서 개인 주관으로 리뷰해봤습니다!
자유롭게 반영해주시고 제 코멘트에 대한 도치의 생각이 궁금해요.
감사합니당

2023-07-29 05:32 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/service/CafeService.java
> +        Page<Cafe> randomPage = cafeRepository.findUnViewedCafesByMember(randomPageRequest, member.getId());
말씀하신대로 2개 이하면 문제가 발생하겠네요!
가져온 갯수를 검증해서 처리를 하던지 다른 방법을 고안해야 할 것 같아요.

```java
@Query(value = "SELECT * FROM un_viewed_cafe order by RAND() limit 5",nativeQuery = true)
List<Literature> findAll();
```
랜덤으로 가져오는 것 자체에 대한 방법은 위처럼 native query로 db에서부터 가져올 수도 있을 것 같고(풀 테이블 정렬하는 문제가 있긴 하지만요!)

기존 Slice 방식을 사용하면서 프론트측에서 봤던 카페 id들을 가지고 처리할 수도 있을 것 같네요. 봤다는 처리를 프론트에서 하기 때문에 백엔드 자체만으로 중복을 100% 제외하기는 힘들지 않을까요??

2023-07-29 05:32 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/service/CafeService.java
> +    private static final boolean UN_LOGIN_USER_IS_LIKED = false;
차라리 CafeResponse의 정적 메서드 자체를

fromLoggedInUser(Cafe cafe, boolean liked)
fromUnLoggedInUser(Cafe cafe)

이렇게 두 가지 만드는 건 어떨까요?
메서드 내부에서 false로 하드코딩해도 될 것 같아요!

2023-07-29 05:32 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/controller/CafeController.java
> +    private static final int PAGE_SIZE = 5;
이건 어떻게 해야할 지 당장 떠오르지는 않는데,

PAGE_SIZE가 컨트롤러와 서비스에서 모두 쓰이고 있습니다.
한 곳에서 관리할 수는 없을까요??

근데 또 드는 생각으로는 CafeService에서는 필요 없을 것 같아요.
Pageable 객체에서 꺼낼 수 있을 것 같아요!

2023-07-29 05:32 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/service/CafeService.java
> +        int pageIdx = (int) (Math.random() * Math.ceil(unViewedCafeCount / pageable.getPageSize()));
```java
new SecureRandom().nextInt(pageable.getPageSize());
```
위와 같은 방법으로도 인덱스를 구할 수 있을 것 같아요! 다만 테스트하기는 힘들 수도...?
`CafeService`에서 필드로 RandomPageGenerator 등을 가진 상태로 만들어도 되겠네요! 다만 랜덤 정책이 바뀔 일이 없다면 그냥 하드코딩해도 될 것 같구요.

2023-07-29 05:32 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/controller/CafeController.java
> +        this.cafeHistoryService = cafeHistoryService;
컨트롤러에 의존 객체들이 점점 늘어나는데 컨트롤러를 분리하는 것은 어떤가요??

좋아요 누르기용 LikedCafeController
봤던 카페 처리용 UnViewedCafeController

uri도 분리할 수 있을 것 같고 분업하기도 더 쉬워질 것 같고 처음 코드를 보더라도 해당 부분만 신경쓸 수 있을 것 같다고 생각합니다.

2023-07-29 05:32 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/controller/CafeController.java
> +                                                                 @PageableDefault(size = PAGE_SIZE) final Pageable pageable) {
API 명세와 다른 부분인 것 같습니다!
코드레벨에서 페이지 사이즈를 받는 부분을 제거하던가 명세를 수정해야 할 것 같아요!!

2023-07-29 08:26 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/controller/CafeController.java
> +    public ResponseEntity<Void> updateMemberUnViewedCafeHistory(final Member member,
음 uri 관련해서는 프론트 포함해서 논의가 필요할 것 같네요. 
'CafeHistoryService'관련해서는 나름 의미를 잘 드러내는 네이밍이라 생각했는데
구현부로 들어가면 헷갈릴 수 있겠군요. 
UnviewedCafeService라는 네이밍으로 바꾸는 게 적절할 것 같은데 다른 팀원도 의견도 들어봐야겠습니다

2023-07-29 08:36 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/service/CafeService.java
> +        Page<Cafe> randomPage = cafeRepository.findUnViewedCafesByMember(randomPageRequest, member.getId());
아 이 문제 관련해서 프론트에게 물어보았는데 `5개마다 3개를 보면 요청을 한다` 가 아니라
프론트가 조회를 요청하는 기준이 **남아있는 미조회 카페들이 3개 이하일 경우**라서 신경쓰지 않아도 된다고 했습니다. 여러 명 있을 때 다시 확인해보아야겠네요.

2023-07-29 08:38 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/controller/CafeController.java
> +                                                                 @PageableDefault(size = PAGE_SIZE) final Pageable pageable) {
음 오해가 없게 구현부를 지우는 것! 이번 pr에서 해도 좋을 작업이네요. 반영하겠습니다.

2023-07-29 09:05 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/service/CafeService.java
> +    private static final boolean UN_LOGIN_USER_IS_LIKED = false;
좋은 생각입니다. 비회원이면 false로 설정되는 것을 메서드만 보아도 알 수 있겠네요!

2023-07-29 09:19 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/controller/CafeController.java
> +        this.cafeHistoryService = cafeHistoryService;
좋아요용controller 메서드 하나, unviewedCafeController메서드도 하나라 현재는 나누기도,안나누기도 애매한 사이즈라 생각이 되는데요.. 
보았던 카페 처리는 여기서 더 생길 controller 메서드가 거의 없을 것 같아서 cafeController에 그대로 놔두고
좋아요 controller는 분리하는 게 어떨까 싶기도 한데, 팀원들과 논의해보야겠네요.

2023-07-29 09:23 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/controller/CafeController.java
> +    private static final int PAGE_SIZE = 5;
Pageable을 활용하는 형태가 통일성이 있어 더 좋겠네요. 👍

2023-07-29 09:39 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeRepository.java
'분리'라는 게 UnViewedCafeRepository를 만들고 아래처럼 쿼리메서드를 활용하자는 의미일까요?
```java
@Repository
public interface UnViewedCafeRepository extends JpaRepository<UnViewedCafe, Long> {

    Long countByMemberId(String memberId);
}
```
저는 지금 정도의 사이즈로 끝이라면 분리하지 않아도 된다는 생각이지만,
생각해보니 앞으로의 기능에서 회원의 기능은 웬만하면 다 unviewedCafe가 관여하며 점점 커질 것 같아 분리하자는데 동의합니다. 
controller와 repository를 나누는 것에 대해서는 다 같이 애기를 나눠보고 결정하는게 좋지 않을까 합니다.

2023-07-29 12:41 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/service/CafeService.java
> +        int pageIdx = (int) (Math.random() * Math.ceil(unViewedCafeCount / pageable.getPageSize()));
SecureRandom 이 장점이 많네요. 또 하나 배웠습니다. 😀

RandomPageGenerator같은 객체를 둘까 고민했는데 이 객체에서 repositroy의 메서드까지 호출하지 않는 이상
Page를 받아올 수는 없습니다.
그러면 random한 pageRequest 를 만들어 줄텐데 복잡하지도 않은 로직으로 pageRequest를 만들자고 객체를 하나 더 만드는 건 좀 과한 선택이 아닌가? 하는 생각이 들어 우선 메서드 분리로 수정하겠습니다!

2023-07-29 13:12 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/controller/CafeController.java
> +        this.cafeHistoryService = cafeHistoryService;
저도 연어 말처럼 분리해도 좋을 것 같습니다. 저는 분리하는데 내부 메소드 개수는 중요하다고 생각하지는 않는 편입니다.

2023-07-29 13:55 UTC, green-kong approved these changes
또오치! 수고하셨어요
코멘트 몇개 남기긴 했는데 필수적인 요소들은 아닌것 같다는 생각이 들어서
approve로 해둘게요!

2023-07-29 13:55 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/service/CafeService.java
> +        final PageRequest randomPageRequest = getRandomPageRequest(unViewedCafeCount, pageSize);
취향의 영역같은데요ㅎㅎ
unViewedCafeCount 같은 경우는 현재 `getRandomPageRequest()` 에서만 사용되는 걸로 보이는데요,
count는 `getRandomPageRequest()` 에서 구하고 member를 파라미터로 넘기는게 어떨까요?

그리고 `getRandomPageRequest()` 의 네이밍을 `getRandomPageRequestByMember()` 로 변경을 하면 좀더 의미를 알기쉬운 메서드가 되지 않을까 싶네요!

2023-07-29 13:55 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeRepository.java
전적으로 연어 의견에 동의해요!

2023-07-29 13:55 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/service/CafeService.java
>                  .toList();
음. 제가 코드를 잘못읽은 걸수도 있는데,
현재 `findUnViewedCafesByMember()` 메서드가 `Page`를 반환할 필요가 있나요?
Page에 있는 다른 필드들은 사용하지 않고, `getContent()` 를 통해 content만 사용하고 있는것 같은데요.
이러면 그냥 `List` 또는 `Slice`를 반환하게 하는건 어떨까요? 
음. 현재라면 `List` 가 가장 적절할 것 같다는 생각이 드네요!

2023-07-29 13:55 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/controller/dto/cafe/CafeResponse.java
>  }
게스트 사용자는 isLike가 false로 매핑이 되는데요. 
이미 CafeResponse에 들어가는 모든 값을 알고있는 저도 순간적으로 `false가 뭐하는 값이지..` 라는 생각이 들었어요!
false를 상수화하여 이 코드를 처음 보는 사람도 이해할만한 네이밍을 지어주면 좋지 않을까요?
가령 `GUEST_USER_DEFAULT_IS_LIKE` 또는 통일성을 위해 `UN_LOGGED_IN_USER~` 도 괜찮을 것 같구요!

2023-07-29 14:13 UTC, donghae-kim requested changes
고생하셨어요

저는 테스트 코드는 존재해야 된다고 생각해서 requestChanges로 설정하였습니다!
랜덤에 대한 의존성을 외부에서 주입하거나, 아니면 랜덤 값을 설정해주는 곳을 service 내부 private 메소드가 아닌 특정한 어딘가에서 할 수 있도록 하여 성공적인 테스트를 작성하면 좋을 것 같습니다!

저도 주말동안 고민 해볼게요

2023-07-29 14:13 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/service/CafeService.java
> +        Page<Cafe> randomPage = cafeRepository.findUnViewedCafesByMember(randomPageRequest, member.getId());
마지막 페이지의 카페 개수가 1개일 경우 응답이 가고 그럼 프론트에서는 남아있는 미조회 카페가 3개 이하이기 때문에 바로 다시 요청 api를 쏘나요 ??

2023-07-29 14:51 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/service/CafeService.java
> +        Page<Cafe> randomPage = cafeRepository.findUnViewedCafesByMember(randomPageRequest, member.getId());
그 UnViewdCafe가 1-6 까지 있다고 가정해볼게요.
처음에는 1-5 까지 갈거구요.
사용자가 끝에서 3번째 정보를 조회할때, 즉 3번 카페를 볼때 api 요청이 들어올거에요.
이때 응답은 6하나만 가겠죠?
(이때 로직상 멤버의 unViewdCafe가 모두 삭제되었기 때문에 랜덤한 순서로 다시 리셋 됩니다.)

그럼 프론트에서 갖고 있는 카페의 정보는 1 - 6 이 될거고, 현재 보고잇는 정보는 3번 일거에요.
그리고 사용자가 4번카페정보를 보게 되면, 4번이 끝에서 3번째 정보이기 때문에, 이때 api 요청이 날아가겠네요.

오션의 질문에 대한 답변은 아니오! 겠네요.
한번더 스크롤을 내려야 api 요청이 날아갈거에요!

2023-07-29 22:39 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/controller/CafeController.java
> +    public ResponseEntity<Void> updateMemberUnViewedCafeHistory(final Member member,
UnviewedCafeController를 새로 만들었습니다.
uri 는 변경이 필요하지만 프론트에서 기존의 api uri대로 구현했놓았기에 이번 배포까지는 uri 유지하는 게 낫지 않을까해서 수정하지는 않았습니다.

2023-07-29 22:56 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeRepository.java
UnViewedCafeRepository 분리되도록 수정했습니다!

2023-07-29 23:00 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/controller/dto/cafe/CafeResponse.java
> +    public static CafeResponse fromLoggedInUser(final Cafe cafe, final boolean isLiked) {
https://github.com/woowacourse-teams/2023-yozm-cafe/pull/192#discussion_r1278247267
정팩메를 분리해서 비회원일 경우에 fale가 기본세팅되는 걸 더 명시적으로 알 수 있겠다고 생각했는데, 단점이 있을까요?

2023-07-29 23:29 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/service/CafeService.java
> +        final PageRequest randomPageRequest = getRandomPageRequest(unViewedCafeCount, pageSize);
더 가독성이 좋아지네요! 감사합니다

2023-07-29 23:32 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/service/CafeService.java
>                  .toList();
아 잘 봐주셨습니다! 페이지 count 메서드가 추가되어서 전체페이지를 page로 구할 필요가 없습니다. 수정하겠습니다👍

2023-07-30 01:01 UTC, hum02 commented
> 고생하셨어요
> 
> 저는 테스트 코드는 존재해야 된다고 생각해서 requestChanges로 설정하였습니다! 랜덤에 대한 의존성을 외부에서 주입하거나, 아니면 랜덤 값을 설정해주는 곳을 service 내부 private 메소드가 아닌 특정한 어딘가에서 할 수 있도록 하여 성공적인 테스트를 작성하면 좋을 것 같습니다!
> 
> 저도 주말동안 고민 해볼게요

저도 최소한의 랜덤 테스트는 있는게 좋을 것 같아 randomPageRequestGenerator를 만들어 랜덤 페이지를 만드는 책임을 주고, 반복 테스트로 범위를 확인하는 테스트를 작성해보았습니다. 그런데 하고보니 좀 불필요한 테스트이려나? 하는 생각도 드네요..

랜덤에 대한 테스트가 불안하기보다는 사실 프론트에서의 시청기록 처리에 따라 카페들이 중복되지 않게 잘 반환되는 지가 검증이 필요했던 것 같습니다. 이는 솔로스타가 슬랙에서 말한 토큰을 이용해 일정주기마다 이미 본 카페를 flush하는 방식으로 바꾸면 더 개선될 것 같아요.

2023-07-30 01:57 UTC, green-kong requested changes
컨트롤러가 왜... 테스트에..??!!

2023-07-30 01:57 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/domain/cafe/UnViewedCafeRepository.java
> +public interface UnViewedCafeRepository extends JpaRepository<UnViewedCafe, Long> {
리포지토리를 분리하셨네요!
UnViewdCafeRepository가 분리되면서 리포지토리들에게 책임과 역할이 적절히 분리된 것 같아 너무 좋네요!
JPQL사용도 줄었구요!

2023-07-30 01:57 UTC, green-kong commented on server/src/test/java/com/project/yozmcafe/controller/UnViewedCafeController.java
> +
???? 이게 왜 테스트에...?

2023-07-30 01:57 UTC, green-kong commented on server/src/test/java/com/project/yozmcafe/service/CafeServiceTest.java
> +    private final RandomPageRequestGenerator pageRequestGenerator = new RandomPageRequestGenerator();
왜 얘만 final 일까요..? 높은확률로 cmd+opt+v 로 예상은 되는데, 혹시 다른 이유가 있는지 궁금하네요!

2023-07-30 01:57 UTC, green-kong commented on server/src/test/java/com/project/yozmcafe/service/RandomPageRequestGeneratorTest.java
> +    @RepeatedTest(20)
호옹... 이런 어노테이션이 있네요!

2023-07-30 01:57 UTC, green-kong commented on server/src/test/java/com/project/yozmcafe/service/RandomPageRequestGeneratorTest.java
> +    void getPageRequest() {
아하 이게 범위가 넘어가는지 아닌지에 대한 반복테스트군요!
또치가 의미가 없는 테스트는 아닐까 라고 하셨는데,
이 테스트를 통해 또치의 마음이 편하다면 전 충분히 의미 있는 테스트라고 생각해요!

2023-07-30 02:06 UTC, hum02 commented on server/src/test/java/com/project/yozmcafe/controller/UnViewedCafeController.java
> +
시정하겠습니다. 죄송합니다

2023-07-30 02:11 UTC, hum02 commented on server/src/test/java/com/project/yozmcafe/service/CafeServiceTest.java
> +    private final RandomPageRequestGenerator pageRequestGenerator = new RandomPageRequestGenerator();
DataJpaTest이기에 이 객체는 autoWired해줄 수는 없고,
cafeService처럼 직접 할당해야 해서 이렇게 작성했습니다.
흠 그런데 어차피 이 테스트에서는 RandomPageRequestGenerator를 필드로 직접 사용하지는 않으니 
아래처럼 하는게 더 나을 것 같아서 수정하겠습니다.

```java
@BeforeEach
    void setUp() {
        cafeService = new CafeService(cafeRepository, unViewedCafeRepository, new RandomPageRequestGenerator());
    }
```

2023-07-30 02:29 UTC, green-kong commented
도치! 주말인데도 도치의 열정에 너무 감사합니다!🙇‍♂️
너무 고생많았습니다!!
approve 하도록할게요!
수고하셨어요!👍

2023-07-30 02:30 UTC, green-kong approved these changes

2023-07-30 02:30 UTC, green-kong commented on server/src/test/java/com/project/yozmcafe/service/CafeServiceTest.java
> +    private final RandomPageRequestGenerator pageRequestGenerator = new RandomPageRequestGenerator();
와우! 좋아요!

2023-07-30 03:34 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/controller/CafeController.java
> +    public ResponseEntity<Void> updateMemberUnViewedCafeHistory(final Member member,
이슈에 uri 수정을 두고 추후에 변경하도록 해도 좋을 것 같아요!
잊어 버릴 수도 있으니 ..

2023-07-30 03:50 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/controller/dto/cafe/CafeResponse.java
> +    public static CafeResponse fromLoggedInUser(final Cafe cafe, final boolean isLiked) {
저는 정적 메서드의 적절한 메서드 네이밍을 통해 반환될 객체의 특성을 유추한다고 생각하는데요. 네이밍을 통해 어떤 값을 이용해 어떤 카페Response 객체를 만들려고 하는지 쉽게 설계 의도가 나타날수 있다고 생각합니다.
그래서 이럴 경우에는 개인적으로 `UnLoggedInUserUnlikedOf`, `LoggedInUserIsLikedFrom` 이런식으로 의도를 드러내서 작성하려고 하는 편인데 생각보다 길어서 좀 가독성이 별로네요 ..

2023-07-30 04:06 UTC, donghae-kim requested changes
RandomPageRequestGenerator 계산하는 로직을 page 의 pageable정보를 가지고 하면 좀더 쉽게 될 것 같은데 도치는 어떻게 생각하시나요 !

2023-07-30 04:06 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/controller/CafeController.java
> +        final PageRequest memberDefaultPageRequest = PageRequest.of(IGNORED_PAGE, PAGE_SIZE);
기존 방식에서 이렇게 분리한 이유가 따로 있을까요 ?

2023-07-30 04:06 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/service/RandomPageRequestGenerator.java
> +        final int pageIdx = new SecureRandom().nextInt((int) Math.ceil((double) unViewedCafeCount / pageSize));
이렇게 하기보다 애초에 Page로 받아서 totalPages를 통해 계산하는건 어떨까요 ? 그게 훨씬 깔끔하고 있는 기능을 사용하는거라 좋을 것 같아서요 !

2023-07-30 04:30 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/controller/CafeController.java
> +        final PageRequest memberDefaultPageRequest = PageRequest.of(IGNORED_PAGE, PAGE_SIZE);
아 설명이 부족했네요
https://github.com/woowacourse-teams/2023-yozm-cafe/pull/192#discussion_r1278249959
현재 회원 카페  API는 page를 쿼리 파리미터로 받지 않고 그냥 서버에서 자체적으로 랜덤한 페이지를 응답하도록 합의했는데, 수정 이전처럼 page파라미터를 받을 수 있도록 구현되있으면 page파라미터를 줘야하는 건가? 하는 오해가 생길 것 같아요. 그래서 구현부에서 아예 파라미터를 받지 않도록 수정했어요!

2023-07-30 05:03 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/service/RandomPageRequestGenerator.java
> +        final int pageIdx = new SecureRandom().nextInt((int) Math.ceil((double) unViewedCafeCount / pageSize));
https://github.com/woowacourse-teams/2023-yozm-cafe/pull/192#discussion_r1277198558
아 수정 전에는 page로 받아서 했었는데요..
해당 방식을 사용하면 totalpage를 알기 위한 목적으로 findUnViewedCafesByMember() 의 쿼리가 나가는데 비효율적이라고 생각했습니다.
 
지금의 방식은 더 적은 쿼리로 개수만을 가져와 계산을 하는 장점이 있다고 생각하는데, page로 계산하는 방식이 그래도 더 깔끔해서 낫다고 보시나요?

2023-07-30 06:59 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/service/RandomPageRequestGenerator.java
> +        final int pageIdx = new SecureRandom().nextInt((int) Math.ceil((double) unViewedCafeCount / pageSize));
page에서 totalpage를 알기 위한 목적으로 나가는 쿼리인데요
![image](https://github.com/woowacourse-teams/2023-yozm-cafe/assets/86547109/fbd292ed-4df6-4843-ab60-bf582311c2c0)
이럴 경우 단순하게 count하는 거 아닌가요 ?

2023-07-30 08:10 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/service/RandomPageRequestGenerator.java
> +        final int pageIdx = new SecureRandom().nextInt((int) Math.ceil((double) unViewedCafeCount / pageSize));
음 현재 로직이
1. 카운트쿼리를 통한 전채갯수
2. 1을 통한 랜덤페이지 생성
3. 리포지토리에서 랜덤 페이지 가져오기(join 쿼리가 나가겠죠?)
인데,

오션의 말대로. 페이지를 반환받으면..
1. Page를 반환받아서 totalPage 가져오기(여기서 join 쿼리가 나가지않나요?)
2. total페이지를 통해 랜덤페이지 생성
3. 리포지토리ㅔ서 랜덤페이지 가져오기(join쿼리 또나감)

이런식으로 되는거 아닌가요???
제가 잘못 알고있다면 말씀해주세요!

2023-07-30 08:16 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/service/RandomPageRequestGenerator.java
> +        final int pageIdx = new SecureRandom().nextInt((int) Math.ceil((double) unViewedCafeCount / pageSize));
습 제가 이해를 잘못한 건가요? ㅠ 
오션이 한 말을 아래의 findUnViewedCafesByMember메서드로 page를 구해와서 totalPage를 알아내 이 값을 이용하자는 방법으로 이해했어요. 
```java
@Query(value = "SELECT c FROM Cafe AS c "
            + "INNER JOIN UnViewedCafe AS u "
            + "ON c.id = u.cafe.id "
            + "WHERE u.member.id = :memberId")
    Page<Cafe> findUnViewedCafesByMember(final Pageable pageable, @Param("memberId") final String memberId);
```
이 메서드는 오션이 이미지로 보여준 쿼리도 나가고 Cafe정보를 반환하기 위한 join한 쿼리도 같이 나갈 거라는 게 제가 말한 join쿼리가 나간다는 말이었어요.
이렇게 findUnViewedCafesByMember()로 totalPage를 구하고, 이 페이지 중 랜덤한 페이지를 지정한 후 또 findUnViewedCafesByMember메서드를 호출해 cafe정보를 반환하는 방법을 오션이 주장하는 방법이라 생각했어요.

지금은 unViewedCafeRepository.countByMemberId()메서드(오션의 이미즈로 보여준 쿼리와 같겠죠) 만으로 unViewedCafed의 개수를 구해오고, 이 값을 이용해 pageTotal을 계산해 그 중 랜덤한 page를 지정해 findUnViewedCafesByMember() 요청을 보내는 방식이에요.

대답이 되었을까요?

2023-07-30 09:09 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/service/RandomPageRequestGenerator.java
> +        final int pageIdx = new SecureRandom().nextInt((int) Math.ceil((double) unViewedCafeCount / pageSize));
최대한 PageCount를 사용해가지고 어떻게 해보려고 했는데 
제가 말한 방식대로 하면 계산한 count를 가지고 다시한번 page쿼리를 날려야하더라고요. 그래서 지금처럼 한번만 쿼리요청 하는 방식이 더 좋을 것 같습니다~

2023-07-30 09:10 UTC, donghae-kim approved these changes
고생했어요 도치~

2023-07-30 10:01 UTC, nuyh99 approved these changes
고생하셨습니다!!
원하시는 부분만 반영해주세용

2023-07-30 10:01 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/service/UnViewedCafeService.java
> +        final UnViewedCafe unViewedCafe = unViewedCafeRepository.findByMemberIdAndCafeId(member.getId(), cafeId)
저는 사실 예외를 터뜨려야 할 지 잘 모르겠습니다.
존재하지 않게 한다면 정상 작동하는 것 같아서요!
member의 removeUnViewedCafe 안에서도 예외를 터뜨리는데 필요할 지 잘 모르겠네요!

단순 제 생각이라서 반영은 안해주셔도 좋아용

```java
member.removeUnViewedCafe(new UnViewedCafe(cafeId));
```

2023-07-31 04:19 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/service/RandomPageRequestGenerator.java
> +        final int pageIdx = new SecureRandom().nextInt((int) Math.ceil((double) unViewedCafeCount / pageSize));
감사합니다!

2023-07-31 04:43 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/service/UnViewedCafeService.java
> +        final UnViewedCafe unViewedCafe = unViewedCafeRepository.findByMemberIdAndCafeId(member.getId(), cafeId)
음 이부분 프론트에서도 history api를 여러번 호출하는 일이 발생할 것 같다고 해서 불필요한 예외 발생에 대해
변경이 필요하다 생각했는데 잘 말해주셨습니다!
반영하겠습니다

2023-07-31 06:23 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/service/UnViewedCafeService.java
> +        final UnViewedCafe unViewedCafe = unViewedCafeRepository.findByMemberIdAndCafeId(member.getId(), cafeId)
존재 검사를 하는 방향으로 변경했습니다.
그런데 optional을 쓰는 지금이 나을지 아래의 직접 null가 좋을지는 모르겠네요. 지금이  isPresent()라는 메서드명으로 의도를 더 드러내는 장점이 있는 것 같아 우선은 그 방향으로 수정했습니다.
```java
@Transactional
public void removeUnViewedCafe(final Member member, final long cafeId) {
    UnViewedCafe unViewedCafe = unViewedCafeRepository.findByMemberIdAndCafeId(member.getId(), cafeId);
    if (unViewedCafe == null) {
        return;
    }

    member.removeUnViewedCafe(unViewedCafe);
    if (member.isEmptyUnViewedCafe()) {
        updateUnViewedCafes(member);
    }
}

```

2023-07-31 06:27 UTC, merged