LikedCafe 코드 분리
woowacourse-teams/2023-yozm-cafe pull request #244
Opened 2023-07-31 11:17 UTC by donghae-kim

## #️⃣ 연관된 이슈

> close #236 

## 📝 작업 내용

> LikedCafe에 관한 로직들이 분산되어있고 이를 하나의 컨트롤러, 레포지토리, 서비스에서 관리하는 것이 응집성도 높고 좋다고 생각하여 코드를 분리하였습니다.
> 거의 대부분의 코드들이 단순 이동 입니다!

## 💬 리뷰 요구사항
> LikedCafeService 를 보면 지금 memberRepository, cafeRepository에 의존하고 있는데 이는 어쩔수 없이 의존해야겠죠 ? 최대한 likedCafeRepository만을 사용하여 의존도를 없애보고 싶었지만, 멤버 조회, 카페 조회 로직상 의존할 수 밖에 없더라고요. 이를 그대로 가져가는것과 수정하는 것에 대해 의견 궁금합니당

2023-07-31 14:19 UTC, green-kong approved these changes
오션의 말대로 한번씩은 봤던 코드라 따악히 리뷰를 할만한 부분이 보이진 않네요..ㅎ
굉장히 번거로운 작업이었을 텐데 고생많으셨습니다!

>  최대한 likedCafeRepository만을 사용하여 의존도를 없애보고 싶었지만, 멤버 조회, 카페 조회 로직상 의존할 수 밖에 없더라고요.

음.. 이 부분은 당연한거란 생각이 들어요.
서비스가 커지면 커질 수록 이런부분은 당연하게 늘어나지 않을까요..?
저 같은 경우는 사실 likedCafeService에서 likedRepository만 의존한다고 했을 때의 장점이 뭔지도 잘모르겠네요....😭
오션이 이 부분을 고민한 이유가 궁금한데 공유해주시면 좋겠어요!

2023-08-01 01:39 UTC, nuyh99 requested changes
고생하셨습니다!!
분리 되고 나니 훨씬 좋은 것 같아요!

2023-08-01 01:39 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/controller/LikedCafeController.java
> +                                                                 @PageableDefault(size = 15) final Pageable pageable) {
PageableDefault의 사이즈는 상수로 치환해도 좋을 것 같아요!

2023-08-01 01:39 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/LikedCafeRepository.java
> +    Slice<LikedCafe> findLikedCafesByMemberIdOrderByIdDesc(@Param("memberId") final String memberId, final Pageable pageable);
Param이 쓰이는 상황인지 궁금합니다!

2023-08-01 01:39 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/service/LikedCafeService.java
> +                .orElseThrow(() -> new IllegalArgumentException("해당하는 회원이 존재하지 않습니다."));
MemberService에 동일한 기능이 있는 상태에서 MemberService에 의존해도 좋을 것 같아요!
동일한 코드를 두 서비스에서 관리하는 것보다 장점이 많다고 생각합니다.

커스텀 예외가 머지가 되면 예외를 교체해도 좋아보입니다!!

2023-08-01 01:47 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/domain/cafe/LikedCafeRepository.java
> +    Slice<LikedCafe> findLikedCafesByMemberIdOrderByIdDesc(@Param("memberId") final String memberId, final Pageable pageable);
쿼리메소드로 변경하면서 놓쳤었네요 ㅎㅎ..

2023-08-01 01:58 UTC, hum02 approved these changes
구-웃~

2023-08-01 01:58 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/LikedCafeRepository.java
> +    Slice<LikedCafe> findLikedCafesByMemberIdOrderByIdDesc(@Param("memberId") final String memberId, final Pageable pageable);
decs하게 정렬해서 반환하는 건 좋아요 페이지에 일정한 순서대로 보여주기 위함인 듯하네요!
디테일 좋습니다

2023-08-01 02:02 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/service/LikedCafeService.java
> +                .orElseThrow(() -> new IllegalArgumentException("해당하는 회원이 존재하지 않습니다."));
중복코드의 발생으로 인해 저도 연어가 말해준 고민을 해보았었는데요 !
물론 동일한 코드를 두 서비스에서 관리하는 것은 지금보다 훨씬 장점이 많다고 생각합니다. 
다만 저는 서비스와 서비스간 의존관계가 생길때는 계층형 구조로 이루어져있을때 진행하는 것이 좋다고 생각합니다. 순환참조 문제(코드단에서 우리가 주의있게 사용하면 해결될 문제)도 생길 수 있고, 현재 프로젝트가 레이어드 형식으로 가져가는데 서비스 또한 레어어드 형식으로 가져가는게 맞다고 생각이 들어서요 !

다만 중복코드를 제거하기 위해서는 의존을 할 수 밖에 없는데 서비스에 의존하지 않고 중복코드를 제거할 방법이 고민되네요 흠

2023-08-01 06:26 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/service/LikedCafeService.java
> +                .orElseThrow(() -> new IllegalArgumentException("해당하는 회원이 존재하지 않습니다."));
의 존

2023-08-01 07:45 UTC, donghae-kim reviewed
좋아하는 카페 목록을 조회하려고 할 때 LikedCafeRepository를 사용하지 않고 멤버에게 직접 메세지를 보내 처리하도록 하였습니다!~

2023-08-01 08:12 UTC, green-kong requested changes
로직 수정해주세용~~

2023-08-01 08:12 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/domain/member/Member.java
> +        int startIndex = (pageNum-1)*pageSize;
아~ 띄어쓰기요~

2023-08-01 08:12 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/domain/member/Member.java
> +        Collections.reverse(pagedLikedCafes);
여기 로직 이상해요~

2023-08-01 08:12 UTC, green-kong commented on server/src/test/java/com/project/yozmcafe/domain/member/MemberTest.java
> +    }
요기 테스트가 조금 보완됐으면 멤버 객체에 로직이상을 좀 더 빨리 캐치할수 있지 않았을까요...

2023-08-01 08:12 UTC, green-kong commented on server/src/test/java/com/project/yozmcafe/domain/member/MemberTest.java
> +    }
카페를 한 5개 넣어놓고 3개짜리 가져오는 테스트였다면 로직이 이상한걸 오션도 바로 캐치했을것 같아요..!

2023-08-01 08:14 UTC, hum02 approved these changes

2023-08-01 08:14 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/controller/LikedCafeController.java
> +    public ResponseEntity<List<LikedCafeResponse>> getLikedCafes(@PathVariable("memberId") final String memberId,
pathParam을 받도록 수정했군요! 인지했습니다

2023-08-01 08:16 UTC, donghae-kim commented on server/src/test/java/com/project/yozmcafe/domain/member/MemberTest.java
> +    }
그러게요 .. 경계값을 제대로 체크하지 못했네요 현재는 1~4번 카페 중 2개만 받아올 때 3,4번 카페만 받아오는 것을 테스트 하게 확인했습니다.

2023-08-01 08:17 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/controller/LikedCafeController.java
> +    public ResponseEntity<List<LikedCafeResponse>> getLikedCafes(@PathVariable("memberId") final String memberId,
굳이 pageable을 받을 필요가 없다고 판단되었습니다! 그래서 임의로 처리할 수 있도록 하였습니다~

2023-08-01 08:21 UTC, hum02 approved these changes

2023-08-01 08:23 UTC, green-kong approved these changes
넘모 좋아용 수고하셨어용 오션

2023-08-01 08:39 UTC, nuyh99 approved these changes
완벽합니다!!!

2023-08-01 08:40 UTC, merged