카페 CRUD 어드민 API 구현
woowacourse-teams/2023-yozm-cafe pull request #286
Opened 2023-08-04 05:19 UTC by nuyh99

## #️⃣ 연관된 이슈
- #282

## 📝 작업 내용
- 카페 도메인 검증 로직 추가
- 카페 어드민 서비스, 컨트롤러 추가

2023-08-04 05:51 UTC, hum02 approved these changes
감사합니다 연 선생님

2023-08-04 05:51 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/service/CafeAdminService.java
> +        Stream.of(
오호 entitymanager로 이렇게 할수도 있겠네요

2023-08-04 05:51 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/Detail.java
> +        final long countUniques = availableTimes.stream()
영업시간 검증까지 좋습니다!

2023-08-04 05:51 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/service/CafeAdminService.java
> +                .forEach(Query::executeUpdate);
회원이 이미 서비스를 이용하고 있어 해당 카페를 가진 채로 로그인되어 있다면 거기까지 바로 삭제되지는 않겠네요. 하지만 다음에 member가 로드될 때는 삭제가 반영된 상태일 테니 상관없는 문제 같습니다. 좋습니다!

2023-08-04 05:51 UTC, hum02 commented on server/src/test/java/com/project/yozmcafe/service/CafeAdminServiceTest.java
> +        void delete_foreign() {
오 이 케이스도 테스트 해주시나요. 꼭 할 필요는 없을 것 같아서 하고 싶으면 하시면 될 것 같습니다

2023-08-04 07:24 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/service/CafeAdminService.java
> +        Stream.of(
생각해보니 EntityManager는 Autowired가 아니라 PersistenceContext가 나을 것 같아서 주입 어노테이션을 바꿨습니다

2023-08-06 04:14 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/service/CafeAdminService.java
> +                .forEach(Query::executeUpdate);
같은 트랜잭션 내에서 Delete가 실행되면 변경감지 때문에 삭제가 무효화되는 경우가 있는데요.
그 문제는 Transactional의 propagation을 Requires New로 해결했습니다!

2023-08-06 04:16 UTC, nuyh99 commented on server/src/test/java/com/project/yozmcafe/service/CafeAdminServiceTest.java
> +        void delete_foreign() {
다른 트랜잭션에서 쓰고 있을 때 삭제하는 경우 삭제는 DB에 바로 반영됩니다.
그리고 다른 트랜잭션이 commit 되면 변경감지로 인해 Member 내의 UnViewedCafe, LikedCafe를 다시 DB에 저장하려고 하는데요!
이때 Cafe 튜플이 존재하지 않기 때문에 다시 추가되지 못하고 `DataIntegrityViolationException`이 발생합니다.

위의 경우를 테스트하도록 해뒀습니다.
예외는 발생하지만, 유저에게 삭제된 카페가 좋아요 목록에 보이거나 메인 화면에 로딩되는 경우는 없습니다.

2023-08-06 04:20 UTC, nuyh99 commented on server/src/test/java/com/project/yozmcafe/service/CafeAdminServiceTest.java
> +        void delete_foreign() {
다만 우려되는 상황은 해당 트랜잭션 내에서 했던 다른 작업들도 모두 롤백되게 됩니다.
카페에서 UnViewedCafe, LikedCafe 방향으로 의존하지 않고 깔끔하게 삭제하는 방법은 없을까요..?

2023-08-07 06:46 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/service/CafeAdminService.java
> +                .forEach(Query::executeUpdate);
삭제가 무효화되는 경우가 어떤 상황인지 잘 모르겠습니다 ㅠ 
같은 트랜잭션에서 이 delete메서드를 호출하면서도 해당하는 카페가 jpa 캐시에 올라와 있는 경우에 무효화가 되는 건가요?
이 메서드는 사장,관리자의 입장에서 카페를 삭제하는 동작일텐데, 그런 상황이 있나요?

2023-08-07 08:29 UTC, green-kong requested changes
연어 수고했어요!
영업시간 부분 validate 하나 추가해주면 좋을것 같은뎅 해줄수 이쬬?

2023-08-08 03:36 UTC, donghae-kim approved these changes
고생하셨어요 연어살몬

2023-08-08 03:36 UTC, donghae-kim commented on server/src/test/java/com/project/yozmcafe/service/CafeAdminServiceTest.java
> +        void delete_foreign() {
이건 고민을 해봤는데도 어렵네요 . . 😭

2023-08-08 06:43 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/service/CafeAdminService.java
> +                .forEach(Query::executeUpdate);
Requires New가 없는 상태라면, 다른 메서드에서 카페 삭제하는 이 public 메서드를 호출했을 때 삭제가 안되는 경우가 생깁니다!

만약 호출하는 쪽에서 삭제하려고 하는 UnViewedCafe, LikedCafe를 영속 상태로 가지고 있을 경우, 같은 트랜잭션 내에서 이 삭제 메서드를 호출하면 삭제 메서드가 씹힙니다. 변경감지 때문에요!

그래서 다른 메서드에서 이 메서드를 애초에 호출하지 못하도록 설정했습니다.
이 메서드를 호출한 다른 메서드(아마 테스트를 작성하겠죠...?)의 테스트가 무조건 실패하게 됩니다.
오용을 방지하는 목적이 가장 큰 것 같습니다.
만약 전파수준을 없앤다고 생각하면 설정하는 것에 비해 장점이 있을 지 모르겠어요.

2023-08-08 07:04 UTC, green-kong approved these changes
고마워잉

2023-08-08 07:05 UTC, merged