스와이프를 통해 카페의 좌우 사진을 볼 수 있도록 한다.
woowacourse-teams/2023-yozm-cafe pull request #288
Opened 2023-08-06 03:02 UTC by jeongwusi

## #️⃣ 연관된 이슈

> 연관된 이슈 번호를 모두 작성해주세요

close #287

## 📝 작업 내용

![화면 기록 2023-08-06 오전 11 12 01](https://github.com/woowacourse-teams/2023-yozm-cafe/assets/122500517/fbbdc061-3321-4c30-996f-9cd2c3ee54e9)

- [검정 바탕에 투명도 들어간 rgba 수정](https://github.com/woowacourse-teams/2023-yozm-cafe/commit/a1873bf6ee86551a99fca9727d0fb673150029c0)

- [스크롤 없애는 코드를 Globalstyle.ts에 추가 후, 나머지 파일에는 관련 코드 삭제](https://github.com/woowacourse-teams/2023-yozm-cafe/commit/45e2bdddbce2ca388d68af248dec32cc9b5a75d1)

- [좌우 스크롤 기능 추가](https://github.com/woowacourse-teams/2023-yozm-cafe/commit/4d646569d05c171a6691d0da4542227238781908)
---
## 스크롤 관련된 코드에 대한 설명

### 상태 추가: `const [currentImageIndex, setCurrentImageIndex] = useState(0); `
- `currentImageIndex`는 현재 보고 있는 이미지의 인덱스를 나타내는 상태입니다. 초기 값으로 0을 설정합니다.

### 스크롤 이벤트 처리 함수: `const handleScroll = () => { ... }`
```tsx
const handleScroll = () => {
  if (ref.current) {
    const { scrollLeft, clientWidth } = ref.current;
    const index = Math.round(scrollLeft / clientWidth);
    setCurrentImageIndex(index);
  }
};
```
 - `handleScroll` 함수는 이미지 리스트를 스크롤할 때 호출되는 함수입니다. 스크롤이 변경되면 현재 스크롤 위치를 계산하여 `currentImageIndex` 상태를 업데이트합니다.
 - `const { scrollLeft, clientWidth } = ref.current;`: `ref.current`는 `CarouselImageList` 컴포넌트의 DOM 요소를 참조하는 변수입니다. 여기서`scrollLeft`는 스크롤이 좌측으로부터 얼마나 떨어져 있는지를 나타내며, `clientWidth`는 컨테이너 요소의 가로 너비를 나타냅니다.
 - `const index = Math.round(scrollLeft / clientWidth);`: 스크롤이 얼마나 이동했는지를 이미지의 가로 너비로 나눈 값을 반올림하여 현재 보고 있는 이미지의 인덱스를 구합니다. 예를 들어, `scrollLeft`가 150px이고 `clientWidth`가 100px일 때, index는 1이 됩니다. 또한 `scrollLeft`가 250px이고 `clientWidth`가 100px일 때, index는 2가 됩니다.
 - `setCurrentImageIndex(index);`: 구한 이미지 인덱스를 `setCurrentImageIndex` 함수를 통해 `currentImageIndex` 상태에 업데이트합니다. 이렇게 함으로써 현재 보고 있는 이미지의 인덱스가 업데이트되면, 자동으로 dot의 위치도 해당 인덱스에 맞추어 표시됩니다.

### 스크롤 이벤트 리스너 등록과 해제: `useEffect(() => { ... }, []);`
 - `useEffect` 훅을 사용하여 컴포넌트가 처음 마운트될 때 스크롤 이벤트 리스너를 등록하고, 언마운트될 때 해당 리스너를 해제합니다. 이렇게 함으로써 컴포넌트가 마운트되어 있을 때만 스크롤 이벤트를 감지하도록 합니다. 
### 스크롤 이벤트 핸들러 내용: `if (ref.current) { ... }`
 - 스크롤 이벤트 핸들러 내부에서는 ref를 사용하여 실제 스크롤 위치를 가져옵니다. 
 - ref.current는 CarouselImageList 컴포넌트의 DOM 요소를 참조하는 변수입니다.
 - scrollLeft는 스크롤이 좌측으로부터 얼마나 떨어져 있는지를 나타내는 속성이며, clientWidth는 컨테이너 요소의 가로 너비를 나타냅니다.
 - 이 정보를 사용하여 현재 스크롤 위치를 계산하고, 그 위치에 해당하는 이미지의 인덱스를 구해 currentImageIndex를 업데이트합니다. 

이렇게 수정된 부분은 스크롤 이벤트를 감지하여 스크롤이 변경될 때마다 현재 보고 있는 이미지의 인덱스를 계산하고, 이를 토대로 dot의 위치를 자동으로 변경해줍니다. 사용자가 스크롤을 하면 dot도 자동으로 따라 움직이게 됩니다.

## 💬 리뷰 요구사항

pull 당겨서 이상 없는 지 확인해주세용

2023-08-07 10:33 UTC, solo5star commented
https://github.com/woowacourse-teams/2023-yozm-cafe/assets/20203944/85c455e4-4c59-472f-a794-b206a97465ee

세로 스크롤 중 가로로 스크롤 할 시 그 자리에서 멈추는 문제가 있네요!

2023-08-07 10:41 UTC, solo5star requested changes
리뷰 남겼습니다! 현재 포커스된 이미지를 react 상태와 싱크하는 것은 `scrollLeft`, `clientWidth` 로 처리하셨더라구요! 저는 `useIntersection` 사용을 생각했었는데 이렇게 하는게 더 깔끔한 것 같네요.

스크롤바 표시가 이제 아예 보이지 않도록 GlobalStyle에 설정하셨는데 작업자들이 이를 잘 숙지하고 있어야 할 듯 하네요.
수고 많으셨습니다~!

2023-08-07 10:41 UTC, solo5star commented on client/src/components/CafeCard.tsx
> +  };
렌더링 될 때 마다 사용되는 것은 아닌 것 같은데 useEffect 안에서 선언되어야 하지 않을까요?

2023-08-07 10:41 UTC, solo5star commented on client/src/styles/GlobalStyle.ts
> +  }
```suggestion
    &::-webkit-scrollbar {
      display: none;
    }
```
인덴트 수정이요!

2023-08-07 10:41 UTC, solo5star commented on client/src/components/CafeCard.tsx
> +  }, []);
```suggestion
  useEffect(() => {
    ref.current?.addEventListener('scroll', handleScroll);
    return () => {
      ref.current?.removeEventListener('scroll', handleScroll);
    };
  }, []);
```
옵셔널 체이닝을 하면 더 깔끔할 것 같아요!

2023-08-07 23:49 UTC, geuntaek1013 approved these changes
고선생님 수고 많으셨습니다~!!

2023-08-08 04:37 UTC, jeongwusi commented on client/src/components/CafeCard.tsx
> +  };
저는 가독성 면에서 분리가 되는 게 좋다고 생각하였는데, 해당 함수는 렌더링 될 때 사용되는 것은 아니니 useEffect안에서 선언되는 게 더 좋겠네요! 수정하였습니당 ^^

2023-08-08 04:39 UTC, jeongwusi commented on client/src/styles/GlobalStyle.ts
> +  }
넷넷!

2023-08-08 04:39 UTC, jeongwusi commented on client/src/components/CafeCard.tsx
> +  }, []);
수정하였습니다^^

2023-08-08 04:40 UTC, solo5star approved these changes

2023-08-08 04:40 UTC, merged