likedCafesPaging 검증 추가
woowacourse-teams/2023-yozm-cafe pull request #318
Opened 2023-08-08 11:21 UTC by donghae-kim

## #️⃣ 연관된 이슈

> close #315 

## 📝 작업 내용
 ```
if (pageNum - 1 > likedCafes.size() / pageSize) {
            return Collections.emptyList();
        }
```
> 기존에는 최대 page를 넘어선 요청이 올 경우 에러가 발생했습니다.
이를 해결하고자 프론트로부터 요청 페이지 숫자가 1 이상이기에 -1 처리를 진행하였고, 
likedCafes.size()/pageSize가 결국 요청할 수 있는 최대 page 이므로 이것을 넘어갈 경우 빈 리스트를 반환하게 하였습니다

## 💬 리뷰 요구사항

2023-08-08 11:51 UTC, hum02 approved these changes

2023-08-08 11:51 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/domain/member/Member.java
> +    public List<LikedCafe> getLikedCafesByPaging(final int pageNumber, final int pageSize) {
이 부분이 controller에서부터 LikedCafeService를 타고 호출되는 듯합니다.
```java
@GetMapping("/guest")
    public ResponseEntity<List<CafeResponse>> getCafesForUnLoggedInMember(@PageableDefault(size = PAGE_SIZE) final Pageable pageable) {
        List<CafeResponse> cafeResponses = cafeService.getCafesForUnLoginMember(pageable);
        return ResponseEntity.ok(cafeResponses);
    }
```
pageConfiguration이 되어 있으니 위 코드처럼 이를 활용해서 받으면 page-1을 자연스럽게 controller에서 해줄 수 있지 않을까요?

2023-08-08 12:03 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/domain/member/Member.java
> +    public List<LikedCafe> getLikedCafesByPaging(final int pageNumber, final int pageSize) {
pageable을 통해 값을 받아오는 것이 좀 오버하지 않나 싶었는데
도치 말대로 이렇게 하는게 훨씬 깔끔하고 좋을 것 같아요! 수정하였습니다

2023-08-09 01:22 UTC, green-kong requested changes
수고해써용 오션~
코멘트 남겼는데 확인해주세용 ㅎㅎ

2023-08-09 01:45 UTC, nuyh99 requested changes
고생하셨습니다!!
개인적인 생각을 남겨봤어용

2023-08-09 01:45 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/service/LikedCafeService.java
> +        }
저도 Member 내부에서 해당 구간의 LikedCafes가 없다면 빈 리스트를 주도록 하는 게 좋아보입니다!
서비스에서 멤버 내부를 꺼내서 하는 느낌이라서요!

2023-08-09 01:45 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/domain/member/Member.java
> +    public List<LikedCafe> getLikedCafesSection(final int pageNumber, final int pageSize) {
page 관련을 받기 보다는
```java
public List<LikedCafe> getLikedCafesSection(final int startInclusive, final int endExclusive){
        //포함되는 부분만 리턴, 없으면 emptyList()
        }
```
위의 느낌은 어떨까요?
현재 멤버라는 도메인이 페이징에 결합된 상태인데 페이징이 제거된다면 도메인이 바뀌어버리는 것보단 서비스 레이어가 바뀌는 것이 낫다고 생각해요.

2023-08-09 03:47 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/service/LikedCafeService.java
> +        }
경계 값에 대해서 놓쳤던 부분이였던 것 같네요 !
수정하였습니다

2023-08-09 03:52 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/domain/member/Member.java
> +    public List<LikedCafe> getLikedCafesSection(final int pageNumber, final int pageSize) {
사실 저는 파라메터명의 차이라고 생각해요. page관련 정보가 도메인까지 넘어온다고 판단되어 진다면 파라메터명을 바꿀 수 있을 것 같아요.
단순하게 start~end 까지의 인덱스 값을 불러오는 것이 아니라서 
```
public List<LikedCafe> getLikedCafesSection(final int sectionNumber, final int sectionSize) {
}
```
다음과 같은 방식으로 변경하였습니다.

2023-08-09 08:58 UTC, donghae-kim commented
조금 이따가 작업해서 다시 말씀 드리겠습니다 흑흑

2023-08-10 08:58 UTC, nuyh99 approved these changes
도메인이 훨씬 깔끔해진 것 같아요!

2023-08-10 09:09 UTC, hum02 approved these changes
고생하셨습니다~~

2023-08-10 09:09 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/service/LikedCafeService.java
> +        int endIndex = startIndex + pageable.getPageSize();
여기하고 member의 getLikedCafesSection()메서드 내의 지역변수에 final만 붙이면 될 것 같아요!

2023-08-10 09:28 UTC, green-kong approved these changes
아주 좋아용

2023-08-10 09:28 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/domain/member/Member.java
> +        }
👍👍👍

2023-08-10 09:28 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/domain/member/Member.java
> +        List<LikedCafe> reverseLikedCafes = new ArrayList<>(this.likedCafes);
요기 this는 빼도 무관한것 같아용

2023-08-10 10:22 UTC, merged