feat: 카페 단 건 조회 API 개발(#326)
woowacourse-teams/2023-yozm-cafe pull request #330
Opened 2023-08-09 08:13 UTC by hum02

## #️⃣ 연관된 이슈
- resolved #326 

## 📝 작업 내용

- 공유하기와 관련하여 카페 id를 통한 단 건 조회 API를 개발

## 💬 리뷰 요구사항

> 존재하지 않는 카페를 조회하려할 때 1)예외를 던지는 방법 2)null,빈 배열 등을 응답하는 방법 등
이 있을 것 같습니다. 
공유하기를 통해 삭제된 카페를 보려할 경우 적절한 안내 메시지("존재하지 않는 카페입니다")가 노출되어야 한다고 생각해서
이 부분에 대한 합의가 필요합니다.
지금은 우선 예외상황은 아닌 듯해 존재하지 않는 카페이면 null을 responseBody에 담아 응답하도록 구현했습니다.

2023-08-09 09:10 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/service/CafeService.java
> +        return foundCafe.map(CafeResponse::fromUnLoggedInUser)
요부분 왜 map으로 되어있나 의문일 수 있는데 
![image](https://github.com/woowacourse-teams/2023-yozm-cafe/assets/96762301/5afa0c23-988e-4b6d-80fa-4e233de5de9b)
원래 이런식으로 작성되었었는데 저 warning에 따라 수정했더니 map으로 바꾸어서 저도 헷갈렸네요;;
단 건이라도 이런식으로 분기문을 줄일 수 있을 것 같은데 어떤가요?

2023-08-09 09:20 UTC, green-kong requested changes
수정부탁..드립니다...

2023-08-09 09:20 UTC, green-kong commented on server/src/test/java/com/project/yozmcafe/domain/cafe/CafeRepositoryTest.java
> +        assertThat(cafe).usingRecursiveComparison().isEqualTo(cafe1);
이건 또 왜...?
Cafe domain에 equals & hashcode가 id값을 통해 재정의 되어있다는 건
id가 같으면 같은 객체라고 판단하기로 한거라고 생각했는데...

2023-08-09 09:20 UTC, green-kong commented on server/src/test/java/com/project/yozmcafe/controller/CafeControllerTest.java
> +    }
null을 반환하는게 아니라,
적절한 ErrorResponse를 반환하고,
프론트 측에서 해당 ErrorResponse에 대한 처리를 하는게 맞지않을까요..?

2023-08-09 09:20 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/service/CafeService.java
> +    }
🤬 선생님 이건 아니죠 정말.....

2023-08-09 09:20 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/service/CafeService.java
> +        return foundCafe.map(CafeResponse::fromUnLoggedInUser)
음.. 저는 카페가 없는 경우에 null을 반환하는거 자체가 조금 문제지 않나 싶어요...

2023-08-09 09:54 UTC, hum02 commented
존재하지 않는 회원 조회의 경우 예외를 발생시키도록 수정했습니다

2023-08-09 11:51 UTC, nuyh99 requested changes
고생하셨습니다!!
서비스 테스트만 추가되면 좋을 것 같아용

2023-08-09 11:51 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/service/CafeService.java
> +
CafeService에 메서드가 추가됐습니다.
성공, 예외 테스트가 CafeService에 추가돼야 할 것 같아요!

2023-08-09 11:51 UTC, nuyh99 commented on server/src/test/java/com/project/yozmcafe/controller/CafeControllerTest.java
> +    @DisplayName("카페 id로 해당하는 카페를 조회할 때, 존재하지 않는 카페이면 statusCode 400을 응답한다")
컨트롤러의 메서드를 봤을 때는 존재하지 않는 카페에 대한 로직이 없습니다.
`CafeService`의 내부 사정인데 컨트롤러에서의 예외 테스트는 필요없다고 생각해요!

슬라이스 테스트에서 다른 계층과 강한 결합이 되지 않았나 싶은 생각입니다!

2023-08-09 12:57 UTC, donghae-kim approved these changes
아까 말했던 예외 관련 로직들은 모두 수정이 된 것 같네요.

다만 이제 admin쪽 조회로직과 비슷해서 이를 병합하면 좋을 것 같아요 !

남은 부분에서도 다른 크루들이 남겨주신 의견 외에는 크게 수정할 것이 없어서 저는 approve하겠습니다!
고생하셨어요

2023-08-09 12:57 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/service/CafeService.java
> +    public CafeResponse getCafeById(long cafeId) {
파라메터 final!

2023-08-10 02:00 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeRepository.java
> +    Optional<Cafe> findById(Long id);
삭제해서 반영했습니다!

2023-08-10 02:25 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/service/CafeService.java
> +
서비스 테스트 추가했습니다!

2023-08-10 02:29 UTC, hum02 commented on server/src/test/java/com/project/yozmcafe/controller/CafeControllerTest.java
> +    @DisplayName("카페 id로 해당하는 카페를 조회할 때, 존재하지 않는 카페이면 statusCode 400을 응답한다")
cafeService의 테스트를 추가했습니다. 그런데 해당 테스트도 의도한 statusCode와 에러메시지를 응답하는 지 확인하는 측면에서 있어서 나쁠 건 없어서 삭제하지는 않았습니다!

2023-08-10 09:01 UTC, nuyh99 approved these changes
고생하셨습니다!!

2023-08-10 09:01 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/service/CafeService.java
> +        Cafe foundCafe = cafeRepository.findById(cafeId)
```java
final Cafe foundCafe = ~
```
final!!

2023-08-10 09:36 UTC, green-kong approved these changes
ErrorResponse를 응답하는 테스트에 대해서도
문서화를 진행하면 어떨까요..?

2023-08-10 09:36 UTC, green-kong commented on server/src/test/java/com/project/yozmcafe/controller/CafeControllerTest.java
> +    }
음 저는 실패하는 테스트 역시 통합테스트 레벨에서 필요하다고 생각해요.
사실 실패에 대한 테스트를 한다기보단, 적절한 ErrorResponse를 응답하는지에 대한 테스트라는 생각이에요.

그렇기 때문에 이 테스트도 문서화를 진행하는게 어떨까요?
처음에 도치가 존재하지 않는 카페 조회에 대한 응답을
`프론트와 백간의 합의`만 있으면 어떤식으로 전달해줘도 괜찮지 않을까 라는 말을 했었잖아요.

그 `프론트와 백간의 합의`의 결과물이 api 문서가 돼야 된다고 생각하는데,
어떻게 생각하시나요??

2023-08-10 10:16 UTC, donghae-kim commented on server/src/test/java/com/project/yozmcafe/controller/CafeControllerTest.java
> +    }
저도 폴로와 비슷한 생각을 하고 있는데 백엔드 크루끼리 이야기를 한번 해보면 좋을 것 같아요!

2023-08-10 12:39 UTC, hum02 commented on server/src/test/java/com/project/yozmcafe/controller/CafeControllerTest.java
> +    }
실패 케이스에 대한 문서화 추가했습니다. openapi yml파일을 보니 실패 케이스도  문서도 있는게 좋겠네요!

2023-08-13 04:37 UTC, merged