카페 좋아요 목록에 나열된 카페의 상세 내용을 볼 수 있게 한다.
woowacourse-teams/2023-yozm-cafe pull request #334
Opened 2023-08-10 06:08 UTC by jeongwusi

## #️⃣ 연관된 이슈

> 연관된 이슈 번호를 모두 작성해주세요

close #304 

## 📝 작업 내용

- [client 파일에 회원이 좋아요한 카페의 상세 정보를 조회할 수 있는 API 추가](https://github.com/woowacourse-teams/2023-yozm-cafe/commit/2187fe99c1fadb78f65164afaf5d6779fe291863)
- [LikedCafeDetail 페이지의 경로 설정](https://github.com/woowacourse-teams/2023-yozm-cafe/commit/102df159f0eff1fb4540937872a76af468b3ab67)
- [좋아요 한 카페 목록 상세 조회에 대한 MSW 핸들러 작성](https://github.com/woowacourse-teams/2023-yozm-cafe/commit/a713dec8b5e7344825008b706ef89cde6e75c37b)
- [달러 기호를 통해 DOM 엘리먼트로 렌더링 되는 것을 방지](https://github.com/woowacourse-teams/2023-yozm-cafe/commit/776dcbc7ec8207f1e4779ac37311a331a64d2752)
- [useCafeLikes 커스텀 훅 추가](https://github.com/woowacourse-teams/2023-yozm-cafe/commit/5b1917a2c73b35bc1bcc9483a42ae1838c39c1c2)
- [useLikedCafesDetail 커스텀 훅 생성](https://github.com/woowacourse-teams/2023-yozm-cafe/commit/fac045815a4f19e037df89448abbda8718011a39)
- [MyProfile 컴포넌트에서 불필요한 코드 삭제](https://github.com/woowacourse-teams/2023-yozm-cafe/commit/153c372afb93237d1a0e69088168dd978a25d931)
- [스크롤 이벤트에서 useIntersection로 수정, useLikedCafes 추가](https://github.com/woowacourse-teams/2023-yozm-cafe/commit/211ba738212d100123ee34b1f7fb0885a767e007)
- [useCafeActions에서 useCafeLikes로 수정](https://github.com/woowacourse-teams/2023-yozm-cafe/commit/5d7eb69d7d8b204b29e05ed1c25eec9dfc862ddc)

## 💬 리뷰 요구사항

Pull 받아서 잘 작동되는지 확인해주세요~!

2023-08-10 06:24 UTC, solo5star requested changes

2023-08-10 06:24 UTC, solo5star commented on client/src/components/LikedCafeList.tsx
> +            <Link to={`/my-profile/cafes/${cafe.cafeId}#${cafe.cafeId}`} key={cafe.cafeId}>
`#cafeId`는 없어도 될 것 같아요

2023-08-10 06:24 UTC, solo5star commented on client/src/hooks/useSuspenseQuery.ts
다른 PR인 것 같은데 왜 뜬걸까요 ..

2023-08-10 06:24 UTC, solo5star commented on client/src/pages/LikedCafeDetail.tsx
> +        <CardList key={cafe.id} id={String(cafe.id)}>
다른 컴포넌트를 만들면서 id가 충돌할 수도 있지 않을까요? [useId](https://react.dev/reference/react/useId)를 사용하여 유일한 id를 만드는 게 좋을 것 같아요

2023-08-10 06:24 UTC, solo5star commented on client/src/hooks/useCafeLikes.ts
> +  const isLiked = queryClient.getQueryData<boolean>(['cafes', cafe.id, 'likes', identity]) ?? cafe.isLiked;
가만 생각해봤는데 useState로 관리되는게 맞지 않을까요? 컴포넌트가 다시 마운트될 때 마다 `cafe.id`값을 사용하여 초기화가 필요할 것 같아요.

2023-08-11 00:33 UTC, geuntaek1013 commented on client/src/pages/LikedCafeDetail.tsx
> +        <CardList key={cafe.id} id={String(cafe.id)}>
useId를 사용한다면 최상위 컴포넌트나 훅에서 호출하고, 반복문이나 조건문에선 사용할 수 없는데, 컴포넌트를 따로 추출해야 하나요?

2023-08-11 01:35 UTC, jeongwusi commented on client/src/hooks/useSuspenseQuery.ts
이거 충돌은 우려되고 사용은 해야겠고... 그래서 다 넣었어요 ㅎ.ㅎ

2023-08-11 01:42 UTC, jeongwusi commented on client/src/components/LikedCafeList.tsx
> +            <Link to={`/my-profile/cafes/${cafe.cafeId}#${cafe.cafeId}`} key={cafe.cafeId}>
네네 삭제하였습니다!

2023-08-11 02:49 UTC, jeongwusi commented on client/src/pages/LikedCafeDetail.tsx
> +        <CardList key={cafe.id} id={String(cafe.id)}>
> useId를 사용한다면 최상위 컴포넌트나 훅에서 호출하고, 반복문이나 조건문에선 사용할 수 없는데, 컴포넌트를 따로 생성해야 하나요?

useId를 사용안하고 ref를 이용해서 해결하였습니닷

2023-08-15 06:10 UTC, geuntaek1013 approved these changes
고선생님 리뷰 확인 부탁드립니다!!

2023-08-15 06:13 UTC, solo5star approved these changes
굿~ 좋아요

2023-08-15 06:20 UTC, solo5star commented
base를 `main`->`dev`로 바꾸어놓았어요 참고 부탁드립니당

2023-08-15 10:03 UTC, geuntaek1013 commented on client/src/hooks/useLikedCafesDetail.ts
> +    queryFn: () => client.getLikedCafeDetail(user?.id as string).then((likedCafesDetail) => likedCafesDetail),
```suggestion
    queryFn: () => client.getLikedCafeDetail(user?.id as string),
```
필요없는 코드같네요!

2023-08-15 11:57 UTC, jeongwusi commented on client/src/hooks/useLikedCafesDetail.ts
> +    queryFn: () => client.getLikedCafeDetail(user?.id as string).then((likedCafesDetail) => likedCafesDetail),
네 수정하였습니당 ^^

2023-08-16 01:15 UTC, merged