회원의 좋아요  된 카페들의 상세정보를 조회하는 API 개발
woowacourse-teams/2023-yozm-cafe pull request #335
Opened 2023-08-10 06:23 UTC by hum02

## #️⃣ 연관된 이슈

-  resolved #324 

## 📝 작업 내용

>  회원의 좋아요  된 카페들의 상세정보를 조회하는 API 개발

## 💬 리뷰 요구사항

> 응답은 CafeResponse랑 구조가 똑같지만 LikedCafeDetailResponse dto를 새로 만들었습니다.
의미를 더 잘 드러낼 수 있다고 생각하고, 정팩메도 선언해야 하는 이유입니다.

> 이렇게 회원의 좋아요 카페정보를 모두 응답하는 건 최선의 선택이 아니라 생각합니다.
페이지 별로 응답하기, 단 건 조회로 스와이프 할때마다 응답하기 등의 방식을 생각했지만
프론트 측에서 카페정보 여러개를 나눠서 줄 때, 선택한 좋아요 된 카페부터 보여주는 것에 어려움을 겪어
우선 이렇게 한 번에 보내주고, 프론트 측에서 지금 css로 동작하는 부분을 자바스크립트로 바꾸고 나면 더 개선해볼 수 있을거라 해서 
우선 회원의 모든 좋아요 된 카페를 응답하는 방식으로 구현했습니다.

2023-08-10 09:50 UTC, green-kong requested changes
궁금한 점이 있어서 코멘트 남겨놨습니당!

2023-08-10 09:50 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/controller/LikedCafeController.java
> +    }
음 도치가 PR에 적어주신 내용만으로는 조금 이해가 힘들어서 여기다가 질문 남길게요.
이 API 가 언제 호출 되는거죠?
그러니까 사용자가 어떤 행위를 할때 이 API가 호출되는 것인지 조금 이해가 잘안되네요..!

좋아요 목록 페이지에 들어갔을 때인지?
아니면 좋아요 목록 페이지에서 카페의 썸네일 이미지를 눌렀을 때인지?
궁금하네요!

2023-08-10 10:39 UTC, donghae-kim requested changes
```
우선 이렇게 한 번에 보내주고, 프론트 측에서 지금 css로 동작하는 부분을 자바스크립트로 바꾸고 나면 더 개선해볼 수 있을거라 해서
우선 회원의 모든 좋아요 된 카페를 응답하는 방식으로 구현했습니다.
```
계속 우선이라고 말씀을 해주셨는데 저희가 내일 당장 마감을 해야하는 것도 아니고 급하지는 않으니까 천천히 더 좋은 방법을 위해 고민하고 나아가면 좋을 것 같습니다!

2023-08-10 10:39 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/controller/LikedCafeController.java
> +    public ResponseEntity<List<LikedCafeDetailResponse>> getLikedCafeDetails(@PathVariable("memberId") final String memberId) {
궁금한 점이 있습니다!
```
프론트 측에서 카페정보 여러개를 나눠서 줄 때, 선택한 좋아요 된 카페부터 보여주는 것에 어려움을 겪어
우선 이렇게 한 번에 보내주고
```
라고 해주셨는데 이것을 해결하기 위해 전체 데이터를 넘겨주는 방법보다는 다른 방법이 좋을 것 같습니다.

현재 많은 좋아요 목록 중에서 어떤 카페를 누르던지 간에 이 api가 호출될 것 같은데 그 때마다 모든 detail을 가져오는 것은 리소스가 너무 큰 것 같습니다.

만약 사용자는 1개를 보려했는데 저장 카페가 몇백개라면 1개를 위해 몇백개의 데이터를 가져와야 할 것 같아서요

2023-08-11 05:27 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/controller/LikedCafeController.java
> +    }
좋아요 목록 페이지에서 카페 썸네일 이미지를 눌렀을 때입니다!
좋아요 목록 페이지와 프로필 페이지가 같은 페이지이기에
프로필에 들어올 때 카페 정보까지 다 로드하는 건 피해야겠다고 생각했어요.

2023-08-11 05:33 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/controller/LikedCafeController.java
> +    public ResponseEntity<List<LikedCafeDetailResponse>> getLikedCafeDetails(@PathVariable("memberId") final String memberId) {
저도 한 응답에 많은 수의 카페정보가 담겨서 단점이 있다고 생각해요...
그런데 스와이프할 때마다 카페들을 나눠서 가져오는 방식은 
프론트에서 자바스크립트로 스와이프를 고도화할 때 더 많은 것을 해줄 수 있다고 해요!

그래서 현재 상황에서는 1)스와이프 마다 1개씩 요청하기 2) 처음 썸네일 선택 때 모든 카페를 가져오는 현재의 방식
2가지를 고려했어요. 현재는 카페 수가 100개 정도로 좋아요 한 카페 정보의 개수도 최대 100개 정도이기에,
스와이프마다 요청을 보내기 때문에 발생하는 성능의 저하가 더 크다고 판단했어요

2023-08-13 08:16 UTC, nuyh99 requested changes
고생하셨습니다!!
다른 코멘트들을 보니 동작 과정이 바뀔 것 같아서 단순한 부분만 남겨봤어요!
화이팅

2023-08-13 08:16 UTC, nuyh99 commented on server/src/test/java/com/project/yozmcafe/service/LikedCafeServiceTest.java
> +        final Cafe savedCafe3 = cafeRepository.save(Fixture.getCafe("카페3", "주소3", 12));
이 카페도 테스트에서 필요한 지 궁금해요.

모든 카페들 중 좋아요 누른 카페만 좋아요 목록으로 들어간 것을 확인하고 싶으신 건가요??
만약 그렇다면 `좋아요를 누르지 않은 카페는 멤버의 좋아요 목록에 존재하지 않는다.` 등의 테스트로 분리하는 것이 좋지 않을까요?

테스트에서 검증하려고 하는 부분만 테스트 내용에 있는 것이 이해하기 좋을 것 같아요!

2023-08-13 08:16 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/service/LikedCafeService.java
> +        reverse(likedCafes);
`Member#getLikedCafesSection`는 좋아요 최신 순으로 주기 위해서 내부에서 reverse 합니다.

여기서는 Member 외부에서 reverse 하는 군요!

최신 순으로 항상 보여줘야 한다면, `Member` 내부에 들어오는 좋아요 목록을 최신 순서로 가져오면 될 것 같습니다. 추가적인 스키마 변경이 필요할 것 같네요.

만약 Application 단에서 최신순으로 하고 싶다면, Member 내부에서만 reverse() 하는 것이 좋을 것 같습니다.

2023-08-14 05:10 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/controller/dto/cafe/LikedCafeDetailResponse.java
> +    private static LikedCafeDetailResponse of(final Cafe cafe, final boolean isLiked) {
확장성의 면도 있지만, isLiked가 사실 하드코딩으로 다 true로 들어가는 거라 이를 좀 더 잘 나타내지 않을까했어요!
그런데 굳이라는 생각이 들긴하네요.. 정팩메 하나만 쓰도록 수정하겠습니다

2023-08-14 05:13 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/controller/dto/cafe/LikedCafeDetailResponse.java
> +public record LikedCafeDetailResponse(Long id, String name, String address, List<String> images, boolean isLiked,
기존의 LikedCafeResponse네이밍 때문에 혼동할까봐 detail이라는 이름을 붙인거였는데, 바로 알아보시는 군요!
LikedCafeThumbnailResponse라는 이름 좋은 것 같습니다. 반영하겠습니다

2023-08-14 05:48 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/service/LikedCafeService.java
> +        reverse(likedCafes);
흠 저도 reverse를 member에 넣을 수는 없을까 생각해보았는데 getter()에서 reverse()를 하는 건 getter()를 비대하게 해버리는 것 같아 하지 않았습니다... 

스키마 변경을 통해 member의 likedCafe를 최신 순으로 가져올 수 있도록 하는 방법이 있나요? 어떻게 스키마 변경이 필요한 건지 잘 모르겠습니다 ㅜ

제 생각에 db에서 이런 저런 정렬이나 제약조건으로 최신순을 유지하는 것은 비용이 클 것 같아 application단에서의
최신순을 하는 방법을 생각하게 됩니다. getter()에서 정렬을 하지 않는다면 member의 likedCafes의 평소상태가 
최신순으로 정렬되있도록 생성자와 메서드에서 관리를 하는 방향일 것 같은데.. 그렇다면
최신순으로 정렬되있도록 하는 책임을 가지는 일급컬렉션을 사용할까 합니다.
```java
@Embeddable
public class LikedCafes {

    @OneToMany(mappedBy = "member", orphanRemoval = true, cascade = {PERSIST, MERGE})
    private List<LikedCafe> likedCafes = new ArrayList<>();

    public LikedCafes(List<LikedCafe> likedCafes) {
        ArrayList<LikedCafe> sortedLikedCafes = new ArrayList<>(likedCafes);
        Collections.reverse(sortedLikedCafes);
        this.likedCafes = sortedLikedCafes;
    }
}
```
이처럼요.. 어떤가요?

2023-08-14 06:28 UTC, hum02 commented on server/src/test/java/com/project/yozmcafe/controller/LikedCafeControllerTest.java
> +        final Cafe savedCafe3 = cafeRepository.save(Fixture.getCafe("카페3", "3동", 7));
savedCafe3변수 삭제했습니다!

2023-08-14 06:34 UTC, hum02 commented on server/src/test/java/com/project/yozmcafe/service/LikedCafeServiceTest.java
> +        final Cafe savedCafe3 = cafeRepository.save(Fixture.getCafe("카페3", "주소3", 12));
불필요한 변수들 전반적으로 제거할게요!!

2023-08-14 15:55 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/service/LikedCafeService.java
> +        reverse(likedCafes);
createdAt과 OrderBy를 이용하는 방식으로 수정했습니다!

2023-08-14 16:47 UTC, hum02 commented on server/src/test/java/com/project/yozmcafe/domain/member/MemberTest.java
> +        assertThat(likedCafes).map(LikedCafe::getCafe).containsExactly(cafe1, cafe2);
이 부분 정렬을 db에서 가져올 때 하게되어서 기존 테스트는 깨집니다
이 테스트는 페이징 처리가 가능한지만 검증하는 것으로 바뀐다고 생각해 바꿨어요!

2023-08-14 17:02 UTC, hum02 commented on server/src/test/java/com/project/yozmcafe/service/LikedCafeServiceTest.java
> +@Sql(scripts = "classpath:truncate.sql", executionPhase = Sql.ExecutionPhase.AFTER_TEST_METHOD)
이거 이렇게 한 이유는 기존의 trasactional이면 서비스의 흐름대로 db에 쿼리가 나가질 않아서
db에 createdAt 저장 순서가 맞지 않더라구요.
transactional붙었을 때 쿼리
```

Hibernate: 
    insert 
    into
        cafe
        (address,description,map_url,phone,like_count,name) 
    values
        (?,?,?,?,?,?)
Hibernate: 
    insert 
    into
        cafe
        (address,description,map_url,phone,like_count,name) 
    values
        (?,?,?,?,?,?)
Hibernate: 
    insert 
    into
        cafe
        (address,description,map_url,phone,like_count,name) 
    values
        (?,?,?,?,?,?)
Hibernate: 
    select
        m1_0.id,
        m1_0.image,
        m1_0.name,
        l1_0.member_id,
        l1_0.id,
        l1_0.cafe_id,
        c1_0.id,
        c1_0.address,
        c1_0.description,
        c1_0.map_url,
        c1_0.phone,
        c1_0.like_count,
        c1_0.name,
        l1_0.created_at 
    from
        member m1_0 
    left join
        liked_cafe l1_0 
            on m1_0.id=l1_0.member_id 
    left join
        cafe c1_0 
            on c1_0.id=l1_0.cafe_id 
    where
        m1_0.id=? 
    order by
        l1_0.created_at desc
Hibernate: 
    insert 
    into
        member
        (image,name,id) 
    values
        (?,?,?)
Hibernate: 
    insert 
    into
        liked_cafe
        (cafe_id,created_at,member_id) 
    values
        (?,?,?)
Hibernate: 
    insert 
    into
        liked_cafe
        (cafe_id,created_at,member_id) 
    values
        (?,?,?)

```
`@sql`로 초기화할 떄 쿼리
```
Hibernate: 
    insert 
    into
        cafe
        (address,description,map_url,phone,like_count,name) 
    values
        (?,?,?,?,?,?)
Hibernate: 
    insert 
    into
        cafe_available_times
        (cafe_id,close,day,is_opened,open) 
    values
        (?,?,?,?,?)
Hibernate: 
    insert 
    into
        cafe_available_times
        (cafe_id,close,day,is_opened,open) 
    values
        (?,?,?,?,?)
Hibernate: 
    insert 
    into
        cafe_available_times
        (cafe_id,close,day,is_opened,open) 
    values
        (?,?,?,?,?)
Hibernate: 
    insert 
    into
        cafe_available_times
        (cafe_id,close,day,is_opened,open) 
    values
        (?,?,?,?,?)
Hibernate: 
    insert 
    into
        cafe_available_times
        (cafe_id,close,day,is_opened,open) 
    values
        (?,?,?,?,?)
Hibernate: 
    insert 
    into
        cafe_available_times
        (cafe_id,close,day,is_opened,open) 
    values
        (?,?,?,?,?)
Hibernate: 
    insert 
    into
        cafe_available_times
        (cafe_id,close,day,is_opened,open) 
    values
        (?,?,?,?,?)
Hibernate: 
    insert 
    into
        image
        (cafe_id,urls) 
    values
        (?,?)
Hibernate: 
    insert 
    into
        image
        (cafe_id,urls) 
    values
        (?,?)
Hibernate: 
    insert 
    into
        cafe
        (address,description,map_url,phone,like_count,name) 
    values
        (?,?,?,?,?,?)
Hibernate: 
    insert 
    into
        cafe_available_times
        (cafe_id,close,day,is_opened,open) 
    values
        (?,?,?,?,?)
Hibernate: 
    insert 
    into
        cafe_available_times
        (cafe_id,close,day,is_opened,open) 
    values
        (?,?,?,?,?)
Hibernate: 
    insert 
    into
        cafe_available_times
        (cafe_id,close,day,is_opened,open) 
    values
        (?,?,?,?,?)
Hibernate: 
    insert 
    into
        cafe_available_times
        (cafe_id,close,day,is_opened,open) 
    values
        (?,?,?,?,?)
Hibernate: 
    insert 
    into
        cafe_available_times
        (cafe_id,close,day,is_opened,open) 
    values
        (?,?,?,?,?)
Hibernate: 
    insert 
    into
        cafe_available_times
        (cafe_id,close,day,is_opened,open) 
    values
        (?,?,?,?,?)
Hibernate: 
    insert 
    into
        cafe_available_times
        (cafe_id,close,day,is_opened,open) 
    values
        (?,?,?,?,?)
Hibernate: 
    insert 
    into
        image
        (cafe_id,urls) 
    values
        (?,?)
Hibernate: 
    insert 
    into
        image
        (cafe_id,urls) 
    values
        (?,?)
Hibernate: 
    insert 
    into
        cafe
        (address,description,map_url,phone,like_count,name) 
    values
        (?,?,?,?,?,?)
Hibernate: 
    insert 
    into
        cafe_available_times
        (cafe_id,close,day,is_opened,open) 
    values
        (?,?,?,?,?)
Hibernate: 
    insert 
    into
        cafe_available_times
        (cafe_id,close,day,is_opened,open) 
    values
        (?,?,?,?,?)
Hibernate: 
    insert 
    into
        cafe_available_times
        (cafe_id,close,day,is_opened,open) 
    values
        (?,?,?,?,?)
Hibernate: 
    insert 
    into
        cafe_available_times
        (cafe_id,close,day,is_opened,open) 
    values
        (?,?,?,?,?)
Hibernate: 
    insert 
    into
        cafe_available_times
        (cafe_id,close,day,is_opened,open) 
    values
        (?,?,?,?,?)
Hibernate: 
    insert 
    into
        cafe_available_times
        (cafe_id,close,day,is_opened,open) 
    values
        (?,?,?,?,?)
Hibernate: 
    insert 
    into
        cafe_available_times
        (cafe_id,close,day,is_opened,open) 
    values
        (?,?,?,?,?)
Hibernate: 
    insert 
    into
        image
        (cafe_id,urls) 
    values
        (?,?)
Hibernate: 
    insert 
    into
        image
        (cafe_id,urls) 
    values
        (?,?)
Hibernate: 
    select
        m1_0.id,
        m1_0.image,
        m1_0.name,
        l1_0.member_id,
        l1_0.id,
        l1_0.cafe_id,
        c1_0.id,
        c1_0.address,
        c1_0.description,
        c1_0.map_url,
        c1_0.phone,
        c1_0.like_count,
        c1_0.name,
        l1_0.created_at 
    from
        member m1_0 
    left join
        liked_cafe l1_0 
            on m1_0.id=l1_0.member_id 
    left join
        cafe c1_0 
            on c1_0.id=l1_0.cafe_id 
    where
        m1_0.id=? 
    order by
        l1_0.created_at desc
Hibernate: 
    select
        c1_0.id,
        c1_0.address,
        c1_0.description,
        c1_0.map_url,
        c1_0.phone,
        a1_0.cafe_id,
        a1_0.close,
        a1_0.day,
        a1_0.is_opened,
        a1_0.open,
        c1_0.like_count,
        c1_0.name 
    from
        cafe c1_0 
    left join
        cafe_available_times a1_0 
            on c1_0.id=a1_0.cafe_id 
    where
        c1_0.id=?
Hibernate: 
    select
        u1_0.cafe_id,
        u1_0.urls 
    from
        image u1_0 
    where
        u1_0.cafe_id=?
Hibernate: 
    insert 
    into
        member
        (image,name,id) 
    values
        (?,?,?)
Hibernate: 
    insert 
    into
        liked_cafe
        (cafe_id,created_at,member_id) 
    values
        (?,?,?)
Hibernate: 
    select
        c1_0.id,
        c1_0.address,
        c1_0.description,
        c1_0.map_url,
        c1_0.phone,
        a1_0.cafe_id,
        a1_0.close,
        a1_0.day,
        a1_0.is_opened,
        a1_0.open,
        c1_0.like_count,
        c1_0.name 
    from
        cafe c1_0 
    left join
        cafe_available_times a1_0 
            on c1_0.id=a1_0.cafe_id 
    where
        c1_0.id=?
Hibernate: 
    select
        u1_0.cafe_id,
        u1_0.urls 
    from
        image u1_0 
    where
        u1_0.cafe_id=?
Hibernate: 
    insert 
    into
        liked_cafe
        (cafe_id,created_at,member_id) 
    values
        (?,?,?)
Hibernate: 
    select
        m1_0.id,
        m1_0.image,
        m1_0.name 
    from
        member m1_0 
    where
        m1_0.id=?
Hibernate: 
    select
        l1_0.member_id,
        l1_0.id,
        l1_0.cafe_id,
        c1_0.id,
        c1_0.address,
        c1_0.description,
        c1_0.map_url,
        c1_0.phone,
        c1_0.like_count,
        c1_0.name,
        l1_0.created_at 
    from
        liked_cafe l1_0 
    left join
        cafe c1_0 
            on c1_0.id=l1_0.cafe_id 
    where
        l1_0.member_id=? 
    order by
        l1_0.created_at desc
Hibernate: 
    select
        u1_0.cafe_id,
        u1_0.urls 
    from
        im [...]

2023-08-14 17:09 UTC, nuyh99 requested changes
고생하셨습니다!!
간단한 내용 조금 남겨봤습니다!

2023-08-14 17:09 UTC, nuyh99 commented on server/src/test/java/com/project/yozmcafe/domain/member/MemberTest.java
> +    void getLikedCafesByPaging() {
궁금한데 이건 왜 바뀐 거죠??!
좋아요 목록은 최신 순으로 받도록 바꾸셨으니 이것도 최신순부터 4, 3으로 보여야하지 않나요??!

Repository에서 가져올 때 최신순으로 정렬되니 순수 도메인 테스트에서는 반영할 수 없겠군요.
어떻게 하는 것이 좋을까요

2023-08-14 17:12 UTC, nuyh99 commented
아 추가적으로 좋아요 카페 목록 리턴하는 컨트롤러 테스트에서
빈 배열 리턴하는 것도 문서화를 추가하셨던데 그건 삭제해도 좋을 것 같아요!

API 사용자 입장에서 빈 배열을 반환 받는 거랑 존재하는 좋아요 목록을 받는 거랑 똑같은 API 동작 아닌가요??
문서가 많아져서 득보단 실이 된다고 생각합니다.

2023-08-14 17:15 UTC, hum02 commented
이거 dev서버에 merge된 pr들이랑 거하게  conflict가 나서 기능과 상관없이 변한 부분이 많습니다...

2023-08-15 06:59 UTC, donghae-kim requested changes
고생하셨어요 도치

2023-08-15 06:59 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/controller/dto/cafe/AvailableTimeRequest.java
> +                                   @JsonProperty("opened") boolean opened) {
JsonProperty 가 필요 없어서 main에서 제거 되었던 것으로 알고 있습니다!
conflict 해결할 때 잘 못 된 것 같아요

2023-08-15 06:59 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/controller/LikedCafeController.java
좋아요 목록은 제가 구현을 했었는데 첫 의도는 인증된 사용자 외에도 사용할 수 있는 API 였습니다!

타 사용자의 좋아요 목록을 확인할 수도 있는 가능성을 열었었어요.

2023-08-15 06:59 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/domain/member/Member.java
> +    @OrderBy("createdAt Desc")
어떤 이유때문에 이렇게 추가 되었는지 궁금합니다!

애플리케이션 단에서 정렬이 아닌 db에서 정렬을 해서 가져오는게 낫다고 생각해서 이렇게 하신건지 ?

2023-08-15 06:59 UTC, donghae-kim commented on server/build.gradle
> +    title = 'USER-API'
why changed ?????

2023-08-15 06:59 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/controller/LikedCafeController.java
> +    public ResponseEntity<List<LikedCafeDetailResponse>> getLikedCafeDetails(@PathVariable("memberId") final String memberId) {
프론트 측에서 지금처럼 하지 않으면 안된다! 라면 어쩔 수 없겠네요 ..

코드가 불편한게 없지 않아 있긴 하네요.

이것하고 별개로 여기서는 최대 100개이기 때문에 모두 가져오는 방식을 가져오셨는데
랭킹에서는 30개정도 되는 지금보다 적은 size의 규모를 페이징 처리 하셨더라고요

도치만의 기준이 있을까요 ?

2023-08-15 14:40 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/controller/LikedCafeController.java
넵 저도 다른 사용자의 좋아요 목록을 볼 수도 있다는 가정하에 구현했어요. 때문에 api url에도 굳이 memberId를 pathVariable로 넣었어요

2023-08-15 14:56 UTC, hum02 commented on server/src/test/java/com/project/yozmcafe/domain/member/MemberTest.java
> +    void getLikedCafesByPaging() {
저는 없애야 하나 생각하기도 했는데, 페이지 처리를 위한 테스트로 남겨놓았어요!

2023-08-15 15:04 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/controller/dto/cafe/AvailableTimeRequest.java
> +                                   @JsonProperty("opened") boolean opened) {
오잉? 감사합니다. 정말 꼼꼼하시군요

2023-08-15 15:10 UTC, hum02 commented on server/build.gradle
> +    title = 'USER-API'
감사합니다! 앞으로는 이런식으로 conflict 해결하지 않을겁니다....

2023-08-15 15:20 UTC, hum02 reviewed
지금 github action이 깨지는 건 db스키마가 변경되지 않아서인 듯 하네요! schema.sql의 created_at 타입을 명시해서 수정했어요! 이제 통과합니다

2023-08-16 01:52 UTC, green-kong approved these changes
다른 분들이 의견 많이 남겨주셨고, 반영도 잘해주셔서 딱히 제가 남길게 없네요ㅠ
수고많으셨습니다 또오치

다만 한번에 카페정보를 한번에 넘겨주는 부분이 마음에 걸리긴하지만,
이부분은 프론트와 함께 고도화를 해야되는 부분이니,
레벨4때 시간을 들여서 하면 좋을것 같아요 수고하셨습니다!

2023-08-16 04:03 UTC, donghae-kim approved these changes
저도 위에 폴로 의견처럼 한번에 조회하는 것 빼고는 괜찮은 것 같아요! 
그 부분만 레벨4 이후에 고려해보도록 하죠 !
고생하셨어요 도치~

2023-08-16 04:08 UTC, nuyh99 approved these changes
고생하셨습니다!! 굿굿

2023-08-16 04:09 UTC, merged