프론트엔드 PR 테스트를 위한 github actions workflow 추가
woowacourse-teams/2023-yozm-cafe pull request #339
Opened 2023-08-10 08:22 UTC by solo5star

## #️⃣ 연관된 이슈
close #27 

## 📝 작업 내용
* 프론트엔드 PR을 테스트하기 위해 github actions workflow를 추가하였음
* 겸사겸사 storybook workflow도 살짝 리팩토링 정도 했습니다.

## 💬 리뷰 요구사항

2023-08-10 12:24 UTC, jeongwusi requested changes
확인 한번만 해주세용~!

2023-08-10 12:24 UTC, jeongwusi commented on .github/workflows/client-test.yml
> +        run: yarn build
정확히 어떤 검사를 하는 역할인가요?

2023-08-10 12:24 UTC, jeongwusi commented on .github/workflows/client-deploy-storybook.yml
> +name: Client Deploy Storybook
단순히 가독성을 위해 수정을 하신건가요?

2023-08-10 12:24 UTC, jeongwusi commented on .github/workflows/client-deploy-storybook.yml
> +        run: yarn build:storybook
`run`을 지우신 이유도 가독성을 위해서인가요?

2023-08-10 13:59 UTC, solo5star commented on .github/workflows/client-deploy-storybook.yml
> +name: Client Deploy Storybook
![image](https://github.com/woowacourse-teams/2023-yozm-cafe/assets/20203944/160db54b-c09e-4c03-ab91-66814818b327)

workflow 이름이 이렇게만 보면 구분이 어려운 듯 하여 수정하였습니다.

2023-08-10 13:59 UTC, solo5star commented on .github/workflows/client-deploy-storybook.yml
> +        run: yarn build:storybook
보통 run을 생략하여 사용하기 때문에 생략했어요!

2023-08-10 14:11 UTC, jeongwusi approved these changes
코멘트 확인하였습니다~! 고생하셨어용 ^^

2023-08-15 06:19 UTC, geuntaek1013 approved these changes
확인했습니다!!

2023-08-15 06:27 UTC, merged