메뉴 조회 기능 추가
woowacourse-teams/2023-yozm-cafe pull request #341
Opened 2023-08-10 14:14 UTC by donghae-kim

## #️⃣ 연관된 이슈

> close #325

## 📝 작업 내용

> 먼저 저희는 메뉴, 메뉴판 을 한 뷰에서 사용자에게 전달하기로 하였습니다. 이들은 모두 여러개가 될 수 있습니다.
> 메뉴, 메뉴판 들은 priority라는 우선순위를 가지고 이 순서에 따라 값을 출력합니다.
> 메뉴 는 isRecommend라는 시그니처 메뉴를 나타냅니다. 백엔드에서 전달할 때 isRecommend 순, priority 순 으로 정렬하여 전달합니다.
> 
> 구조는 카페 와 메뉴, 카페 와 메뉴판이 1 : N 입니다.
> 카페 -> 메뉴 를 사용할 일이 없을 것 같아 단방향 매핑으로 진행하였습니다
> 자세한 명세서는 노션에서 확인할 수 있습니다!

## 💬 리뷰 요구사항
> 1. Menu와 MenuBoard 의 복합 unique 제약 조건
> cafeId당 priority 가 unique 해야 해서 조건을 걸어봤습니다.
> 아니면 정규화를 해야되는 것일까요 !? pk가 아닌 cafeId가 priority를 인지할 수 있으니 ... ?
> 2. Response
> 지금 구조를 보면 MenuResponse 정팩메 안에서 메뉴판과 메뉴 response를 생성해주고 있습니다.
> 계층 구조라고 생각해서 이렇게 진행하였는데 어떻게 생각하시는지 궁금합니다 ~

감사합니돵

2023-08-13 05:22 UTC, green-kong requested changes
궁금한 점들 코멘트 남겨놨어요!
수고하셨어용 오션!

2023-08-13 05:22 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/domain/menu/MenuRepository.java
> +    List<Menu> findAllByCafeIdOrderByIsRecommendedDescPriorityAsc(Long cafeId);
혹시 메뉴 최대갯수 제한이 있나요?? 서울앵무새같은 경우 메뉴가 90개라는 말을 들었는데...
이걸 한 큐에 다 줄 필요가 있으려나요??
메뉴 갯수 제한이 뭐 10개 정도로 제한이 있다면 괜찮겠지만,
그렇지 않다면, 괜찮으려나.. 라는 생각이드네요 ㅋㅋ

2023-08-13 05:22 UTC, green-kong commented on server/src/test/java/com/project/yozmcafe/controller/MenuControllerTest.java
> +        final Menu savedMenu = menuRepository.save(new Menu(cafe, 1L, "뜨거운 아이스 아메리카노",
??? 뜨거운 아이스 아메리카노 사주세여

2023-08-13 08:45 UTC, nuyh99 requested changes
고생하셨습니다!!

3번 질문에 대해서 제 생각을 말씀드리자면...
우선 카페와 메뉴는 생명 주기가 다르다고 생각해요.
카페가 추가됐지만, 메뉴는 언제 새로 추가되고 삭제될 지 모르거든요
변경에 초점을 맞춰보면 비즈니스적으로 생명 주기가 확실히 다른 것 같습니다.

현재의 구조가 낫다고 생각해요!

2023-08-13 08:45 UTC, nuyh99 commented on server/src/main/resources/schema.sql
> +    cafe_id BIGINT,
카페가 존재하지 않아도 메뉴는 존재할 수 있는지 궁금합니다!
메뉴판(menu_board)도 마찬가지입니다.

2023-08-13 08:45 UTC, nuyh99 commented on server/src/main/resources/schema.sql
> +        UNIQUE (cafe_id, priority)
insert문이 실행될 때마다 유니크한지 확인해야 합니다.
버퍼에 저장했다가 한 번에 플러시하는 방법을 쓸 수 없기 때문에 삽입 속도가 느려집니다.

유니크하지 않으면 발생하는 문제 VS 삽입, 업데이트 속도 저하 시의 문제

위 두 기준으로 유니크 제약을 고민하면 좋을 것 같아요!
제 개인적인 생각으로는 잘못된 클라이언트의 요청으로 발생하는 문제가 없다고 생각해요.
다른 메뉴를 먼저 보여줬을 때 문제가 발생할 것 같지 않고, 순서를 바꾸려면 어드민 API의 수정 기능 등을 쓰면 될 것 같거든요!

2023-08-13 08:45 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/domain/menu/Menu.java
> +@Table(
실제 반영은 DDL을 사용할 것인데, Menu, MenuBoard 엔티티만 코드 레벨로 테이블 생성 조건을 거는 이유가 궁금해요.

2023-08-13 08:45 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/domain/menu/MenuBoard.java
> +    private String imageUrl;
저도 메뉴, 메뉴판이 둘다 있는 것이 좋은 지 모르겠어요...!
메뉴판이 메뉴를 포함하는 구조라면 차라리 나을 것 같아요.

아니라면 그냥 `메뉴 이미지`등의 엔티티 하나로 메뉴, 메뉴판 사진들 다 쓸 수 있지 않을까요?

2023-08-13 08:45 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/service/CafeAdminService.java
> +                        entityManager.createQuery("DELETE FROM Menu me WHERE me.cafe.id = :cafeId"),
꼼꼼하시군요!

2023-08-13 08:45 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/domain/menu/MenuRepository.java
> +    List<Menu> findAllByCafeIdOrderByIsRecommendedDescPriorityAsc(Long cafeId);
디비에서 정렬 VS 자바에서 정렬

디비에서 정렬을 선정하신 이유가 궁금해요!

2023-08-13 08:45 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/Cafe.java
> +import jakarta.persistence.*;
헉

2023-08-13 08:47 UTC, nuyh99 commented
아 그리고 테스트에 given, when, then이 아예 없습니다...!

2023-08-13 09:26 UTC, hum02 requested changes

2023-08-13 09:26 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/controller/dto/menu/MenuResponse.java
> +public record MenuResponse(Long cafeId, List<MenuBoardResponse> menuBoards, List<MenuItemResponse> menus) {
저도 MenuResponse가 계층형으로 구성되는게 좋다는 데에 동의합니다!

2023-08-13 09:26 UTC, hum02 commented on server/src/test/java/com/project/yozmcafe/domain/menu/MenuBoardTest.java
> +    @NullAndEmptySource
null테스트인 경우에 이런식으로 할 수도 있군요!  새로운 걸 알았습니다

2023-08-13 09:39 UTC, hum02 requested changes

2023-08-13 09:39 UTC, hum02 commented on server/src/main/resources/schema.sql
> +    CONSTRAINT menu_cafe_id
카페가 삭제되면 메뉴,메뉴판도 삭제되어야한다고 생각해요!
manyToOne으로 매핑이 되어 있어서 jpa로 casacade옵션을 걸기 어렵다면 아래처럼 casacade옵션을 직접 걸어주면 어떨까요?
CONSTRAINT fk_cafe
FOREIGN KEY (cafe_id) REFERENCES cafe(id)
ON DELETE CASCADE

2023-08-13 09:42 UTC, hum02 commented
1. 정규화를 한다면 menu테이블과 priority테이블을 분리해서 참조시키는 방식을 말하는 건가요?
저는 이러면 불필요하게 join을 해서 쿼리를 해야할 듯해서, 지금의 unique제약을 건 방식이 좋아보여요!
2.지금의 계층형 구조가 적절하다고 생각합니다
3. 서비스에서 메뉴를 보여주는 건 카페 정보를 보여줄 때와는  다른 주기이기에 지금처럼 엔티티를 분리하는 건 좋아요!
그런데 카페의 삭제 시에는 같은 생명주기로 삭제되어야 해서 casacade옵션이 필요하지 않을까 합니다

2023-08-13 09:47 UTC, hum02 requested changes
메뉴 기능 어려운 기능이네요... 고생합니다 오션

2023-08-13 09:47 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/domain/menu/Menu.java
> +    @ManyToOne
메뉴 엔티티를 로드할 때 cafe를 eager로딩할 필요는 없을 것 같아요!
response를 만들때에도 getCafe()를 해서 쓰지는 않아보여서 lazy로딩을 하는 건 어떨까요?

2023-08-14 04:28 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/domain/menu/MenuRepository.java
> +    List<Menu> findAllByCafeIdOrderByIsRecommendedDescPriorityAsc(Long cafeId);
일단 어플리케이션 단 보다는 db 에서 정렬하는 것이 더 빠르다고 알고 있고, 오류(휴먼에러)가 발생할 가능성이 적다고 생각했습니다. 그리고 코드를 단축시킬 수는 있지만 db 의존도가 높아질 수 있고 .... tradeoff라고 생각합니다. 둘 다 어떤 것을 선택해도 상관없을 것 같지만 저는 처음에 말했던 이유로 이렇게 진행하였습니다.

아니면 Querydsl을 사용해서 자바 코드 + query로 사용하는 방법도 있을 것 같네요

2023-08-14 04:28 UTC, donghae-kim commented on server/src/test/java/com/project/yozmcafe/controller/MenuControllerTest.java
> +        final Menu savedMenu = menuRepository.save(new Menu(cafe, 1L, "뜨거운 아이스 아메리카노",
sure why not ?

2023-08-14 04:29 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/domain/menu/Menu.java
> +
저희가 카페 데이터를 찾아보면서 느낀 건데 변동가격(?) 같은 값이나 5000~7000(이건 이해가 안감 ;;) 이런 식으로 적힌데가 은근 있더라고요 그런 이유로 String 으로 진행하였습니다!

2023-08-14 04:32 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/domain/cafe/Cafe.java
> +import jakarta.persistence.*;
![image](https://github.com/woowacourse-teams/2023-yozm-cafe/assets/86547109/06c38a42-cac2-42af-bc30-4edbd96c91b5)
저 이거 설정하고 싶어요 .... 근데 설정이 안되요 ... 저만 안되나요

2023-08-14 04:36 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/controller/dto/menu/MenuResponse.java
> +    public static MenuResponse of(final Long cafeId, List<MenuBoard> menuBoards, List<Menu> menus) {
놓쳤던 부분 감사함다~

2023-08-14 04:39 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/domain/menu/MenuRepository.java
> +    List<Menu> findAllByCafeIdOrderByIsRecommendedDescPriorityAsc(Long cafeId);
카페별 메뉴 갯수는 상이하나 전체를 다 주는 것은 힘들지 않나 라는 생각이 들었습니다!
그래서 최대 20개 정도의 메뉴만 제공하려고 합니다.

기억은안나지만 절반 정도의 카페가 10개 이하의 메뉴 만을 제공해서 괜찮다고 생각했습니다!

2023-08-14 04:57 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/domain/menu/Menu.java
> +
1. priority 라는 값이 pk 아닌 cafeId 라는 다른 속성에 종속된다고 생각되어 '부분 함수적 종속' 이라고 생각되어서 이를 제거함으로써 정규화 수준을 높일 수 있지 않나? 라고 생각했습니다.

2. 만약 이렇게 진행할 경우에는 priority 테이블을 분리해야 될 것 같습니다.

3&4. Wrapper를 사용한 이유는 not null 컬럼에는 primitive, nullable에는 wrapper형을 쓰면 되겠지만 통일시키지 않아서 오는 어떤 불편함 때문에 Wrapper를 사용했는데 nullable false에 갯수가 많지 않을 것 같아서 int 타입으로 수정하였습니다 ~~

2023-08-14 04:59 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/service/MenuService.java
> +public class MenuService {
read 하나만 있어서 놓쳤었는데 감사합니다 !

2023-08-14 05:05 UTC, donghae-kim commented on server/src/main/resources/schema.sql
> +    CONSTRAINT menu_cafe_id
헉 진짜 중요한데 놓쳤던 부분이네요.
도치 고마워용 수정하였습니다!

2023-08-14 05:44 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/domain/menu/Menu.java
> +    @ManyToOne
사용하지 않는 부분이라 생각을 못했었네요.
지금 확인해보니까 cafe에 대한 조회 쿼리도 동시에 나가서 lazy 타입으로 변경하였습니다!

2023-08-14 05:50 UTC, donghae-kim commented
@hum02 
정규화를 한다면 menu테이블과 priority테이블을 분리해서 참조시키는 방식을 말하는 건가요?
저는 이러면 불필요하게 join을 해서 쿼리를 해야할 듯해서, 지금의 unique제약을 건 방식이 좋아보여요!
- 맞습니다 부분 함수적 종속 이라고 생각되어서 분리해서 사용하는 방식이 낫지 않나? 라고 생각했습니다. 다만 이를 해결하는 방법이 테이블 분리, 복합키 사용 등등이 존재하는데 지금처럼 복합 키를 사용하는게 나을 것 같네요.

2023-08-14 05:53 UTC, donghae-kim commented on server/src/main/resources/schema.sql
> +    cafe_id BIGINT,
카페가 존재하지 않으면 메뉴, 메뉴판은 존재하지 않다고 생각합니다.
그 역은 성립할 수 있고요 !

그래서 cascade 옵션을 통해서 같이 제거될 수 있도록 하였습니다!

2023-08-14 05:59 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/domain/menu/Menu.java
> +@Table(
음 처음 의도는 실제 반영은 ddl 로 한다는 고려가 없었던 것 같습니다. 단순하게 코드 레벨에서도 정보를 드러내야하지 않을까? 라는 생각으로 작성을 했었는데

연어가 남긴 의견을 보니 schema.sql과 ddl 만 잘 사용한다면 굳이 코드레벨단에서 쓸 필요는 없을 것 같네요 !

2023-08-14 06:10 UTC, donghae-kim commented on server/src/main/resources/schema.sql
> +        UNIQUE (cafe_id, priority)
삽입속도가 느려질 수 있다는 점에서는 인정합니다.

유니크하지 않으면 발생할 수 있는 문제로는 같은 메뉴에 대해서 클라이언트 측에서 무엇을 우선순위로 출력해야할지 모르지 않을까요? 다른 메뉴를 먼저 보여줬을 때 문제가 생기지 않을 수는 있지만 (물론 지금은 없지만) 카페한테는 자신의 카페 메뉴 순서(시그니처 라던지 맛있는 메뉴 등)가 중요하다고 생각했습니다. 

연어 의견은 삽입, 업데이트 속도 저하 이슈가 > 유니크 하지 않으면 발생하는 문제 이기 때문에 굳이 유니크할 필요는 없다는 것일까요 ? 하지만 저는 메뉴 추가,삭제가 그렇게 빈번하게 발생할 것 이라는 생각이 들지는 않기에 위에 말한 비즈니스적 사항이 좀 더 중요시 되야한다고 생각했습니다

2023-08-14 06:55 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/domain/menu/MenuBoard.java
> +    private String imageUrl;
@green-kong 
메뉴판을 추가할 생각이라면 imageUrl이 필수라고 생각합니다.
메뉴판은 있는데 imageUrl이 없는게 이상하니까요 .....?

2023-08-14 07:05 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/domain/menu/MenuBoard.java
> +    private String imageUrl;
@nuyh99 
처음에 생각했던 구조가

메뉴판이 메뉴를 포함하는 구조였습니다.

근데 이렇게 진행하다보니 메뉴판, 메뉴 의 이미지가 여러개 생길 수 있고 이거에 대한 우선순위 값도 있어야 하고 ..
그렇게 만들다 보니

메뉴 안에 메뉴판과 메뉴아이템이 들어가 있고 각각에 대해서 모두 entity가 생성이 되어야 하더라고요
그럼 메뉴는 id, cafeid 만 갖게 되고 각각의 메뉴판,메뉴아이템이 manytoone으로 가리키게 되었는데요, 이보다는 지금처럼 하는게 좀 더 나을 것 같아서 진행하였습니다.

`아니라면 그냥 메뉴 이미지등의 엔티티 하나로 메뉴, 메뉴판 사진들 다 쓸 수 있지 않을까요?`
이는 각각 메뉴, 메뉴판에 대한 priority 값 때문에 진행하지 않았습니다.

연어 말처럼 메뉴판이 메뉴를 포함하는 구조가 된다면 좋을 것 같기는 한데 어떤 구조로 짜야할지 잘 모르겠네요 😂 혹시 좋은 의견 있나요 ?

2023-08-14 17:19 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/domain/menu/MenuBoard.java
> +    private String imageUrl;
메뉴판 사진, 메뉴 이미지

이렇게 두 가지의 정보를 준다고 하면 각각이 의미 있는 엔티티인 것 같네요.
지금의 구조처럼 각자의 엔티티로 구현하는 것이 좋은 것 같습니다!
오히려 포함관계면 이상한 것 같아요!

2023-08-14 17:21 UTC, nuyh99 commented on server/src/main/resources/schema.sql
> +    cafe_id BIGINT,
앗 제가 말한 것은 NOT NULL 조건이 들어가야 하지 않는가?! 였습니다

2023-08-14 17:26 UTC, nuyh99 commented on server/src/main/resources/schema.sql
> +        UNIQUE (cafe_id, priority)
만약 백엔드에서 priority를 1,1,3,4 이런 식의 메뉴들을 리턴했다면,
프론트에서는 오류가 발생하는 구조인가요?

첫 두 사진 중 어떤 것을 먼저 보여줄지는 결정이 안돼도 결국 4개의 사진을 보여줄 수 있다면 유니크할 필요가 있을까?하는 의문이였습니다.
클라이언트 구현의 어려움 때문이라면 지금이 좋을 것 같네요!

카페 사장한테는 사진 보여주는 순서가 중요하죠.
하지만 순서는 수정할 수 있지 않나요??
등록한 뒤 눈으로 봤을 때 이 사진이 먼저 나와야하는데? 하고 느끼면 그때 우선순위를 새로 업데이트하면 될 것 같아서요.

제약을 피할 수 있다면 최대한 피하는 것이 좋지 않을까 생각했습니다.
단순히 삽입 속도가 느려지는 문제이지만 삽입 시 락을 사용하게 되면서 사이드 이펙트가 생길 수도 있으니까요!

2023-08-14 17:32 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/domain/menu/MenuRepository.java
> +    List<Menu> findAllByCafeIdOrderByIsRecommendedDescPriorityAsc(Long cafeId);
속도는 무조건 DB가 빠른 것도 아니라서요! 그때그때 다를 것 같습니다.

만약 대용량의 데이터를 DB에서 정렬한다면,
해당 결과를 리턴할 때까지 DB측의 세션 스레드를 물고 있게 됩니다. 스레드가 부족하면 다른 세션이 기다려야합니다.
하지만 스프링에 결과가 리턴된 이후 바로 응답할 수 있기 때문에 WAS의 유저 커넥션 스레드는 빠르게 리턴할 수 있습니다.

대용량의 데이터를 스프링에서 정렬한다면,
DB측의 세션 스레드를 단시간만 물고 있기 때문에 DB를 사용하는 동시성 속도가 좋습니다.
다만 WAS에서 정렬하기 때문에 JVM의 메모리를 써야 하고, 유저 커넥션을 좀 더 오래 물고 있어야 합니다.

말씀하신 대로 트레이드 오프 부분이라서 어떤 기준으로 선택한 것인지 궁금해서 물어본 거에요!

2023-08-14 17:37 UTC, nuyh99 commented on server/src/main/resources/schema.sql
> +    CONSTRAINT menu_cafe_id
DB측에서 cascade를 거는 것은 데이터 정합성 부분에서 좋지만 저희 다른 테이블에 대해서는 아예 사용하지 않고 있습니다.
그 이유는 애플리케이션 단에서 cascade를 사용하기 때문인데요.

카페와 이미지, 디테일
유저와 좋아요 카페, 안 본 카페

등등 위의 경우도 모두 cascade가 필요하다고 생각해요.
여기에만 사용하는 이유가 궁금합니다.

제 개인적인 생각으로는 db 측에서는 제약을 걸 필요가 없다고 생각합니다.
WAS에서 관리하기 때문에 DB 측에서는 최악의 상황만 피하도록 제약을 거는 것이 좋을 것 같거든요!

2023-08-14 17:44 UTC, nuyh99 requested changes
고생하셨습니다!
스쿼드별로 하니까 컨텍스트 스위칭이 힘드네요ㅠ

2023-08-14 17:44 UTC, nuyh99 commented on server/src/test/java/com/project/yozmcafe/domain/menu/MenuBoardTest.java
> +    void invalidImageUrl(String imageUrl) {
final!

2023-08-14 17:44 UTC, nuyh99 commented on server/src/test/java/com/project/yozmcafe/domain/menu/MenuTest.java
> +    void invalidName(String name) {
여기랑 나머지 부분들도 final 있으면 좋을 것 같아요!!

2023-08-14 17:44 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/Cafe.java
> +import jakarta.persistence.*;
I don't know...

2023-08-14 17:44 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/domain/menu/MenuRepository.java
> +    List<Menu> findAllByCafeIdOrderByIsRecommendedDescPriorityAsc(Long cafeId);
혹시 이 메서드가 여러 상황에서 제대로 순서가 맞는지는 테스트가 필요없을까요??!

추후 N+1 문제 해결 등을 위해 JPQL로 바꾸거나 해도 제대로 동작하는 지 테스트가 존재하면 유용할 것 같아서요!

2023-08-14 17:44 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/domain/menu/MenuBoardRepository.java
> +    List<MenuBoard> findAllByCafeIdOrderByPriorityAsc(Long cafeId);
마찬가지로 네이밍 규칙으로 만드는 쿼리도 제대로 동작하는지 테스트가 존재하면 좋을 것 같아요!

2023-08-15 05:35 UTC, donghae-kim commented on server/src/test/java/com/project/yozmcafe/domain/menu/MenuTest.java
> +    void invalidName(String name) {
테스트 파라메터 final을 놓쳤었네요 😂

2023-08-15 05:39 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/domain/menu/MenuRepository.java
> +    List<Menu> findAllByCafeIdOrderByIsRecommendedDescPriorityAsc(Long cafeId);
아래 질문과 같이 답하겠습니다!

MenuServiceTest에서 `getMenus_sort` 라는 테스트 명으로 테스트를 진행했는데요,
이정도면 충분하지 않을까요?

menuBoard 관련해서는 Priority 순으로, menu 관련해서는 recommended, priority 순을 확인하고 있는데 이정도로도 충분하지 않다고 생각하시는지 궁금합니다!

jpql로 변경했을 경우에도 순서가 잘 맞지 않는 경우에 `getMenus_sort` 로 검증은 가능할 것 같습니다.

2023-08-15 05:46 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/domain/menu/MenuRepository.java
> +    List<Menu> findAllByCafeIdOrderByIsRecommendedDescPriorityAsc(Long cafeId);
좀 더 제가 db 정렬한 이유를 덧붙이자면

db가 내부적으로 정렬 작업에 더 최적화 하도록 설계되어있다고 알고 있습니다. 
대용량 데이터일 경우에 스프링에서 처리한다면 동시성 처리가 좋지만, db에서 처리할 경우 dbms에서 모든 것을 처리해주니까 메모리 관리 같은 것을 따로 신경쓰지 않아도 되고 프로덕션 코드에서 별도 정렬로직 구현하지 않아도 되고 .. 등등의 장단점이 있다고 생각합니다.

지금 상황에서는 둘 다 상관 없다고 생각합니다. 동시성 문제가 생긴다던지, 메모리 문제가 생긴다던지 할 때 그때 가서 고려해봐도 되지 않을까요 ?

2023-08-15 05:59 UTC, donghae-kim commented on server/src/main/resources/schema.sql
> +        UNIQUE (cafe_id, priority)
```
만약 백엔드에서 priority를 1,1,3,4 이런 식의 메뉴들을 리턴했다면,
프론트에서는 오류가 발생하는 구조인가요?
```
아직 프론트쪽 구현 상황이 어떻게 되는지를 잘 모르겟지만, 이럴 경우 메뉴를 출력하는데 어려움이 있을 것 같습니다. (일단은 priority 순으로 출력하기로 했기 때문에)

```
카페 사장한테는 사진 보여주는 순서가 중요하죠.
하지만 순서는 수정할 수 있지 않나요??
등록한 뒤 눈으로 봤을 때 이 사진이 먼저 나와야하는데? 하고 느끼면 그때 우선순위를 새로 업데이트하면 될 것 같아서요.
```
음 연어가 말하는 순서를 수정한다는게 prority 값을 제거하고 id 값 순으로 출력했다가 순위를 바꾸고 싶으면 id 값을 바꾼다는 것일까요? 아니면 제약 조건을 걸지 않고 priority값을 삽입하고 수정이 요구되어지면 그 값을 수정하면 된다는 것일까요 ?

물론 제약을 피할 수 있다면 최대한 피하는 것이 좋다고 저도 생각합니다.
다만 비즈니스 로직적으로 필요한 제약들도 모두 피하는게 맞는지가 좀 걱정이네요..

지금같은 상황에서는 초기 데이터로써 저희가 값을 넣어주기 때문에 사실상 제약 조건이 필요할 것 같지는 않습니다! (저희가 값을 잘 넣어주면 되기 때문에) 복합 unique 키를 제거하고 이후에 문제가 생긴다면 고려해보는 것도 좋을 것 같네요 ~

2023-08-15 06:13 UTC, donghae-kim commented on server/src/main/resources/schema.sql
> +    CONSTRAINT menu_cafe_id
위에 연어가 말해준
카페<-> 이미지, 디테일
유저 <-> 좋아요,안본 카페
등은 embeddable이거나 양방향으로 매핑 해놓고 부모의 생명주기를 그대로 가져가는 것으로 알고 있습니다.

하지만 메뉴, 메뉴판은 위에서 연어가 말했듯이 카페와 생명주기를 다르게 가져가고 있습니다. 현재 ManyToOne 단방향 으로 구성되어있습니다.
 연어가 말했듯이 어플리케이션단에서 cascade를 하려면 결국 양방향 매핑을 진행해야하는데 단순하게 삭제 생명주기를 위해서 양방향 매핑을 하는것은 아닌 것 같아서 db단에서 제약을 걸었습니다.

양방향 매핑을 진행하지 않고 애플리케이션 단에서 cascade가 가능할까요 ?  흠. . . 잘 모르겠어서 . . .

2023-08-15 09:42 UTC, donghae-kim commented on server/src/main/resources/schema.sql
> +    cafe_id BIGINT,
Cascade를 의도하신 줄 알았습니다! 
그래서 db 쪽에 삽입하였는데 슬랙에서 말해준것처럼 
항상 application 코드를 확인하는데 db에 걸려있다는것을 인지하지 못하면 사이드 이펙트가 발생하니까 ! 라는 생각이 좋은 것 같습니다.
그래서 NOT NULL 은 삽입하지만 cascade 옵션은 제거했습니다 ~

2023-08-16 01:53 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/domain/menu/Menu.java
> +
하핳... 그렇군요 5000~7000원은 진짜 뭘까요 커피를 싯가로 판다니..답변 감사합니다!

2023-08-16 02:04 UTC, green-kong approved these changes
고생하셨어요 오션 고민한 흔적들이 많이 보여서,
힘들었을것 같네요 ㅋㅋ
수고많으셨습니다!

2023-08-16 02:27 UTC, hum02 approved these changes
고생하셨습니다~~

2023-08-16 02:29 UTC, merged