Feat/331 like ranking
woowacourse-teams/2023-yozm-cafe pull request #348
Opened 2023-08-12 01:02 UTC by hum02

## #️⃣ 연관된 이슈

- resolved #331 

## 📝 작업 내용

- 좋아요 개수 순위에 따라, page에 맞는 카페 정보 조회 API 개발

- 구상한 좋아요 랭킹 기능 예시와 흐름
<img width="513" alt="image" src="https://github.com/woowacourse-teams/2023-yozm-cafe/assets/96762301/5168b55e-dd03-495b-9a77-99c3bce3ea5b">
이런 화면을 예상하기에 카페의 모든 상세정보까지 응답하지는 않습니다.
한 페이지 요청에 10개씩 응답해 좋아요 개수 상위30개까지 보여주도록 하자고 정했습니다.
이 중 하나의 카페를 누르면 해당 카페의 단 건 조회를 하는 페이지로 이동합니다.

## 💬 리뷰 요구사항
- api uri

현재는 `/cafes/ranks?page=?` 와 같은 API입니다.
정렬해서 조회하는 api는 쿼리 파라미터를 이용하는 게 맞다는 관점으로는
`cafes/ranks?orderby = likeCount&page=`같은 uri도 고려해보았지만
현재 정렬 조회하는 api가 이것밖에 없기에 orderby속성을 명시하지 않아도 된다고 생각했습니다.
순위를 매기는 기준이 다양해진다면 그때 이러한 uri를 사용하는 게 좋다고 생각하는데 어떤가요?

- 조회 쿼리 더 좋은 방법이 있을까요?

현재 `@Query("SELECT c FROM Cafe c ORDER BY c.likeCount DESC")`라는 jpql을 실행해서
`select
        c1_0.id,
        c1_0.address,
        c1_0.description,
        c1_0.map_url,
        c1_0.phone,
        c1_0.like_count,
        c1_0.name 
    from
        cafe c1_0 
    order by
        c1_0.like_count desc limit ?,
        ?`
이 쿼리를 1번, 

`Hibernate: 
    select
        u1_0.cafe_id,
        u1_0.urls 
    from
        image u1_0 
    where
        u1_0.cafe_id=?
`
`
Hibernate: 
    select
        a1_0.cafe_id,
        a1_0.close,
        a1_0.day,
        a1_0.is_opened,
        a1_0.open 
    from
        cafe_available_times a1_0 
    where
        a1_0.cafe_id=?
`
이 쿼리들을 page안의 카페 개수만큼 날립니다.
fetch join을 해도 같은 쿼리를 날립니다.
cafe_available_times은 좋아요 랭킹의 응답에는 필요치 않은 정보이지만
Cafe엔티티의 Detail클래스에 eager로딩으로 설정되어 있기에 같이 select하고 있습니다.
이를 lazy로딩으로 바꾸면 image에 대한 select문만 카페 개수만큼 날립니다.
때문에 availableTimes를 lazy로딩으로 바꿀까하는 고민이 있는데 괜찮을까요? 아니면 더 좋은 쿼리를 위한 방법이 있을까요?

2023-08-12 10:19 UTC, donghae-kim requested changes
고생하셨어요 도치

api url 같은 경우에는 현재 계획되어 있는 랭킹(?) api 가 존재하지 않기 때문에 그대로 두고 추후 수정해도 될 것 같습니다.

1개의 쿼리에 대해 N개의 쿼리가 나간다고 하셨는데 현재 EAGER 로딩으로 되어있는 것을 LAZY 로 변경해도 되지 않을까 싶습니다. 근데 다만 저희가 왜 저렇게 했는지 먼저 이유를 알면 좋을 것 같은데 모르겠네요 ,,

2023-08-12 10:19 UTC, donghae-kim commented on server/src/test/java/com/project/yozmcafe/controller/CafeControllerTest.java
> +        final Cafe savedCafe5 = cafeRepository.save(Fixture.getCafe("n5", "address5", 50));
단순 궁금증인데 엣지케이스 cafe 3~5개 정도면 충분하다고 생각하는 편인데 
10개를 다 추가하시는 이유가 있는지 궁금합니당

2023-08-12 10:19 UTC, donghae-kim commented on server/src/test/java/com/project/yozmcafe/controller/CafeControllerTest.java
> +    void getCafesOrderByLikeCount3() {
실패 케이스는 _fail이 낫지 않을까요 ?

2023-08-12 10:19 UTC, donghae-kim commented on server/src/test/java/com/project/yozmcafe/controller/CafeControllerTest.java
> +    @DisplayName("/cafes/rank?page=? 요청을 보낼 때, 좋아요 된 카페가 존재하지 않으면 빈 배열을 반환한다.")
다른 백엔드 분들한테도 궁금한 건데
이렇게 존재하지 않는 페이지에 대한 요청이 들어왔을 경우에는 예외를 발생시키는게 맞지 않나요?
저도 좋아요 목록 조회에서 당장은 이런식으로 구현이 되어있는데 사실 존재하지 않는 리소스에 대해 요청을 하는 것이니까요 !

원래 같은경우에 isNext인가..를 통해 마지막 인지를 확인하고 클라이언트 측에서는 요청을 멈추고 이런 식이 맞지 않나 싶네요..
다른 분들 생각도 궁금합니당

2023-08-12 10:19 UTC, donghae-kim commented on server/src/test/java/com/project/yozmcafe/service/CafeServiceTest.java
> +@Sql(scripts = "classpath:truncate.sql", executionPhase = Sql.ExecutionPhase.AFTER_TEST_METHOD)
변경하신 이유가 따로 있을까요 ?
restassured를 사용하지도 않는데 transactional 로 충분하지 않나? 라는 생각이 들어서용

2023-08-13 07:15 UTC, green-kong requested changes
또오치 고생하셨습니당.
코멘트 몇개 남겼습니다. 확인해주세요~

2023-08-13 07:15 UTC, green-kong commented on server/src/test/java/com/project/yozmcafe/controller/CafeControllerTest.java
> +    @DisplayName("/cafes/rank?page=? 요청을 보낼 때, 좋아요 된 카페가 존재하지 않으면 빈 배열을 반환한다.")
아 어렵네요..
저는 빈배열을 던지는게 좀더 어울리지 않나 쪽인데,
`왜?` 라는 질문에는 명확한 답변이 안나오네요;;

사실 어떤 것을 던져주든 간에 프론트와 백간에 약속만 잘되면 상관없는 부분 아닌가 싶기도 하고... 

뭔가 `findById` 같이 식별자를 지정해서 이것과 관련된 데이터를 내놔 라는 요청에는
해당 식별자와 일치하는 데이터가 없다면 예외를 던지는게 좋다라고 생각이드는데,
왜 이 케이스는 예외가 맘에 들고,
왜 저 케이스는 빈배열이 맘에 드는 걸까요.

저도 제맘을 잘 모르겠네요ㅠㅠ

2023-08-13 07:15 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/exception/ErrorCode.java
> +    RANK_OUT_OF_BOUNDS("R1", "순위 범위를 벗어나는 요청입니다.");
스읍.. 이게 무슨말인지 메세지만 보고는 짐작하기가 쉽지않네요;;
이 에러코드가 호출되는 곳을 따라들어가보니, 페이지넘버가 3이상일 때 발생하는 예외네요.
그럼 그냥 페이지넘버는 2까지만 호출된다거나 그런식으로 메세지를 정해주면 더 좋지 않을까요?

고니와 함께 작업하고 있는 걸로 알고있는데,
다른 프론트 크루에게 이 메세지를 보여주며, `예외메세지 이걸로 날라오면 님 뭐 수정할거임?` 이라고 물어보면 다들 모른다 할거 같은데요..

2023-08-13 07:15 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeRepository.java
> +    Slice<Cafe> findCafesByLikeCount(Pageable pageable);
final 실종사건 ㅠ

2023-08-13 07:21 UTC, green-kong commented on server/src/test/java/com/project/yozmcafe/controller/CafeControllerTest.java
> +    @DisplayName("/cafes/rank?page=? 요청을 보낼 때, 좋아요 된 카페가 존재하지 않으면 빈 배열을 반환한다.")
위의 의견과는 별개로 
`isNext` 인가 `isLast`인가를 통해서 이게 마지막 페이지니까 요청 그만보내셈! 이라고 프론트측에 알려주는건 좋은 것 같아요!
현재는 이게 적용된 페이지응답이 없는 것 같은데 해당부분을 수정해봐도 좋을 것 같아요!

2023-08-13 08:56 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeRepository.java
> +    Slice<Cafe> findCafesByLikeCount(Pageable pageable);
오 이거 좀 재밌네요.

```java
    @Query("SELECT c.id FROM Cafe c ORDER BY c.likeCount DESC")
    List<Long> findCafesByLikeCount(Pageable pageable);

    @Query("SELECT c FROM Cafe c " +
            "JOIN FETCH c.images.urls " +
            "JOIN FETCH c.detail d " +
            "JOIN FETCH d.availableTimes " +
            "WHERE c.id IN :ids " +
            "ORDER BY c.likeCount DESC ")
    List<Cafe> findCafesByIds(List<Long> ids);
```

repository쪽 이렇게 수정하고,

```java
 public List<CafeRankResponse> getCafesOrderByLikeCount(final Pageable pageable) {
        cafeRankingManager.validatePage(pageable);
        final List<Long> ids = cafeRepository.findCafesByLikeCount(pageable);
        final List<Cafe> foundCafes = cafeRepository.findCafesByIds(ids);
        
        return foundCafes.stream()
                .map(cafe -> CafeRankResponse.of(cafeRankingManager.getRank(foundCafes, cafe, pageable), cafe))
                .toList();
    }
```
서비스 쪽에서 이렇게 수정해서 돌렸더니 다음과같은 예외가 터지네요.

<img width="896" alt="image" src="https://github.com/woowacourse-teams/2023-yozm-cafe/assets/96301958/8a7e0e8c-ac45-475f-b06a-db88c97bd42c">

해당 내용 검색해보니, 동욱님 블로그가 나오네요!!

https://jojoldu.tistory.com/457

대충 요약해보면,
`ToOne` 으로 끝나는 애들은 fetchJoin을 몇개해도 상관없지만,
`ToMany`로 끝나는 애들은 fetchJoin 하나만 가능하다고 하네요!

현재 위에 제가 작성한 JPQL은 availableTimes와 urls 모두 cafe 기준에서 `OneToMany`의 관계다 보니,
fetchJoin이 되면서 예외가 발생한 듯 합니다!

`Detail`과 `Images`의 경우는 `OneToOne`이라 여러개의 fetchJoin이 걸려서 상관 없는듯 보이네요!

위에 링크 걸어둔 동욱님 블로그에 이런 경우의 해결 역시 나와있습니다!
저도 읽어보긴 했는데 내용 이해가 완벽히 되지 않아서 어떻게 적용해보세요! 라는 말은 못하겠네요..!

또오치가 열심히 공부해서 저 알려주세요!!ㅋㅋ

2023-08-13 09:50 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeRepository.java
> +    Slice<Cafe> findCafesByLikeCount(Pageable pageable);
오 2개로 나눠서 해볼 생각은 못했는데 공부할 거리가 더 나오네요! 감사합니다 더 생각해볼게요!!

2023-08-14 17:50 UTC, nuyh99 commented on server/src/test/java/com/project/yozmcafe/controller/CafeControllerTest.java
> +    @DisplayName("/cafes/rank?page=? 요청을 보낼 때, 좋아요 된 카페가 존재하지 않으면 빈 배열을 반환한다.")
좋아요 목록 조회는 빈 배열로 주는 것이 맞다고 생각해요.
유저가 좋아요한 카페가 없다는 건 예외가 아니니까요!

존재하지 않는 페이지에 대한 요청은 404가 괜찮을 것 같기도 하구요!
예외인지 아닌지에 대한 것은 예외라고 생각합니다.

2023-08-14 17:52 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/controller/dto/cafe/CafeRankResponse.java
> +        );
동의합니다!

2023-08-14 18:20 UTC, nuyh99 requested changes
고생하셨습니다!!

다른 리뷰들을 봤었는데 우선,
availableTimes를 lazy로 안한 이유는 카페를 조회할 때 항상 영업시간 정보가 필요하다라는 뜻이 있었습니다.
근데 지금은 비즈니스가 달라져서 lazy가 좋을 것 같아요.
https://velog.io/@nuyh99/Lazy-Loading-Eager-Loading에-관한-고찰
글이 좋더라구요.

그리고 fetch join하면 하나의 쿼리로 안된다고 하셨는데 됩니다!
다만 문제는 여러 fetch join을 하게 되면 Cartesian Product가 발생합니다.
Fetch Join을 한 sql이 아닌 여러 sql로 나누는 것이 더 나을 수 있겠네요.

Entity Graph, Fetch Join, Cartesian Product
위 키워드들에 대한 사전 지식이 필요할 것 같아요.

`MultipleBagFetchException`에 대해서는
https://www.baeldung.com/java-hibernate-multiplebagfetchexception
여기 보시면 될 것 같습니다.
현재 단시간에 회피할 수 있는 방법은 List로된 연관 관계를 Set으로 바꾸면 여러 Fetch Join이 한 SQL로 가능해지게 됩니다.

2023-08-14 18:20 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/service/CafeRankingManager.java
> +public class CafeRankingManager {
서비스 레이어인지 잘 모르겠어요!
도메인 아닐까요??

2023-08-14 18:20 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/service/CafeRankingManager.java
> +    public int getRank(final List<Cafe> cafes, final Cafe cafe, Pageable pageable) {
필요 이상의 정보를 받는 것 같습니다.
테스트하기 너무 힘든 구조가 된 것 같아요.

```java
public int getRank(final int index, Pageable pageable) {
```
위의 정보만 있어도 되지 않나요??
그리고 Manager라면 뭔가를 관리해야 하는데 `EntityManager` 같은 느낌으로요!
얘는 그냥 파싱하는 친구 같습니다.

`RankGenerator`가 차라리 어떨지...?
```java
makeRank(final int index, Pageable pageable);
```

이러면 테스트도 매우 쉬워질 것 같습니다.

2023-08-14 18:20 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/service/CafeRankingManager.java
> +    public int getRank(final List<Cafe> cafes, final Cafe cafe, Pageable pageable) {
사실 페이지를 잘못 썼을 때가 예외인지 모르겠습니다.
페이지에 아무것도 존재하지 않으면 그냥 빈 배열 주면 되지 않나요??

비즈니스적으로 아무 문제 없는 상황이라고 생각해서 예외가 맞는지 모르겠습니다.

2023-08-14 18:20 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeRepository.java
> +    Slice<Cafe> findCafesByLikeCount(Pageable pageable);
추상 메서드 시그니처에서는 final 안 붙여도 될 것 같아요!
얘네는 어차피 overriding할 때 final 붙여서 만드니까요.

final은 내부 구현을 드러내는 사항이라고 생각합니다.
내부에서 참조를 바꿀 지 안 바꿀 지는 시그니처가 결정하는 것이 아니라 구현부에서 결정하게 됩니다.

예시로 시그니처에 final이 붙어있어도 구현체에서 안 붙여도 문제 없이 컴파일 되거든요...!

2023-08-15 06:28 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeRepository.java
> +    Slice<Cafe> findCafesByLikeCount(Pageable pageable);
처음에는 Slice반환값일 때 카운트 쿼리가 나가지 않는 장점이 있을거라 생각했어요.
그런데 지금 둘 다 해서 테스트를 해보니 같은 쿼리가 나갑니다! slice로 받을 필요가 없어서 수정하겠습니다

2023-08-15 06:31 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/service/CafeRankingManager.java
> +        return (pageable.getPageSize() * pageable.getPageNumber()) + cafes.indexOf(cafe) + 1;
쿼리에 rank를 이용하는 방식은 순위가 중복되는 걸 허용하면 할만하다고 생각해요!
1,2,3,3(공동3등), 4,4,4.... 같이요!
그런데 고니랑 애기해본 결과 이렇게 숫자가 겹치는 건 깔끔하지 못한데 비해 공동순위라는 정보가 그 정도로 중요하지 않다고 판단했어요
많이 알아보진 않았지만 rank를 쓰면서 중복없이 순위설정을 하려면 아래 이미지처럼 정렬이 더 일어날 것 같아 선택하지 않았습니다
<img width="565" alt="image" src="https://github.com/woowacourse-teams/2023-yozm-cafe/assets/96762301/adbc1d31-5595-4c48-938c-409898800436">

2023-08-15 06:32 UTC, hum02 commented on server/src/test/java/com/project/yozmcafe/controller/CafeControllerTest.java
> +        final Cafe savedCafe5 = cafeRepository.save(Fixture.getCafe("n5", "address5", 50));
실제 서비스랑 똑같이 으로 10개로 설정하는 게 좋지 않을까 했습니다!

2023-08-15 06:43 UTC, hum02 commented on server/src/test/java/com/project/yozmcafe/service/CafeServiceTest.java
> +@Sql(scripts = "classpath:truncate.sql", executionPhase = Sql.ExecutionPhase.AFTER_TEST_METHOD)
https://github.com/woowacourse-teams/2023-yozm-cafe/pull/335#discussion_r1293739288
이 이유와 같은데 transactional로 테스트 코드가 묶이면서 메서드 내에서 동작하는 순으로 쿼리가 나가지 않고 flush할 때 재구성해서 쿼리가 나가서 정확한 테스트가 안될 수 있을 것 같아요...

2023-08-15 06:44 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeRepository.java
> +    @Query("SELECT c FROM Cafe c ORDER BY c.likeCount DESC")
cafe조회할 떄가 특히 심하더군요...

2023-08-15 06:45 UTC, hum02 commented on server/src/test/java/com/project/yozmcafe/controller/CafeControllerTest.java
> +                .filter(document(CAFE_API + "좋아요 개수 순위에 따라 카페정보 조회 - 카페가 존재하지 않는 경우", getPageRequestParam()))
저는 성공 케이스, 실패 케이스 다 프론트의 인지가 필요한 상황이면 문서화하는 게 좋다고 생각합니다. 백엔드 다 같이 애기를 해볼까요?

2023-08-15 06:54 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/service/CafeRankingManager.java
> +public class CafeRankingManager {
전 이렇게 싱글톤인 클래스가 있을때 도메인일지 서비스일지 좀 헷갈리네요...
util클래스 느낌으로 간주해서 도메인에 넣지 않았는데 `@service`가 붙어있지도 않으니 서비스이지도 않은 듯 하네요.
도메인으로 옮기겠습니다. 
연어가 도메인과 서비스를 구분하는 기준을 물어봐도 될까요?

2023-08-15 06:56 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/service/CafeRankingManager.java
> +    public int getRank(final List<Cafe> cafes, final Cafe cafe, Pageable pageable) {
흠 이건 비즈니스 상황에 대한 합의 문제이기도 한 거 같은데요...
고니와 저는 정책으로 랭킹을 최대 30위까지만 보여주기로 정했습니다.
그래서 카페가 없어서 못보여주는 빈 배열을 보내주는 상황이랑, 
취급하지 않는 랭킹에 대한 요청을 한 상황을 구분하자는 게 제 의도였습니다.

이에 대해 어떻게 생각하시나요?

2023-08-15 07:02 UTC, hum02 commented on server/src/test/java/com/project/yozmcafe/controller/CafeControllerTest.java
> +    @DisplayName("/cafes/rank?page=? 요청을 보낼 때, 좋아요 된 카페가 존재하지 않으면 빈 배열을 반환한다.")
일단 이 경우에는 -최대 30위까지의 랭킹 정보만 제공한다- 라는 정책에서 벗어나는 요청이라는 생각에 
페이지를 벗어나는 요청은 예외, 카페가 없으면 빈 배열  2가지로 구분을 하려했던 이유도 있어요!

`isNext`같은 정보로 페이지 요청을 조절하는게 지금처럼 빈 배열로 하는 것보다 낫다는 데에는 동의합니다.
이걸 적용한다면 페이징 처리가 걸려있는 것들 전반에 걸쳐서 다른 pr에서 적용하는 게 좋을 것 같습니다.

2023-08-15 07:15 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/exception/ErrorCode.java
> +    RANK_OUT_OF_BOUNDS("R1", "순위 범위를 벗어나는 요청입니다.");
좋아요 개수 랭킹 범위를 벗어나는 요청입니다. 좋아요 개수 랭킹 요청의 페이지 확인이 필요합니다
라는 메시지로 수정해보았어요!

2023-08-15 07:19 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeRepository.java
> +    Slice<Cafe> findCafesByLikeCount(Pageable pageable);
repository 메서드에는 다 붙어있지 않아서 일단 수정하진 않았어요!

2023-08-15 07:36 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/exception/ErrorCode.java
> +    RANK_OUT_OF_BOUNDS("R1", "순위 범위를 벗어나는 요청입니다.");
위에서 애기했듯 정책으로 정해진 범위를 벗어나는 요청이면 예외를 준다는 관점에서는 어떨까요?

2023-08-15 07:53 UTC, hum02 commented
`
    @Query("SELECT c FROM Cafe c JOIN FETCH c.images ORDER BY c.likeCount DESC")
    List<Cafe> findCafesByLikeCount(Pageable pageable);
`
이렇게 fetch join했을 때는 images에 대한 쿼리는 따로 나가던데 다르게 fetch해서 한번에 조회하는 방법이 있는건지 모르겠네요.....

2023-08-16 02:16 UTC, green-kong approved these changes
또오치 수고많으셨어요!
바쁜 연휴를 보내셨네요! ㅋㅋㅋ
리뷰 반영 감사드립니다!
다만 Response 쪽에 메서드가 `cafe.getImage()~` 로 되어있는데, 
요 부분은 수정하면 더 좋을 것 같아요!
그닥 중요한 부분 아니라, 어프루브할게용
수고하셨어용~

2023-08-16 02:16 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/controller/dto/cafe/CafeRankResponse.java
> +                cafe.getImages().getRepresentativeImage(),
도오오치 이거 말구용. `cafe.getRepresentativeImage()` 만 해도 될거에용

2023-08-16 02:28 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/controller/dto/cafe/CafeRankResponse.java
> +                cafe.getImages().getRepresentativeImage(),
cafe에 바로 있는게  있군요! ㅠ 감사합니다

2023-08-16 03:52 UTC, donghae-kim approved these changes
고생하셨습니다 도치

2023-08-16 04:14 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/service/CafeRankingManager.java
> +public class CafeRankingManager {
순수 단위테스트가 가능하면 도메인이라고 생각합니다.

외부 시스템(DB나 외부 API) 등을 호출하는 것들은 서비스라고 생각합니다!

2023-08-16 04:24 UTC, nuyh99 approved these changes
고생하셨습니다!!
반영하면 좋을 것 같긴해서 간단한 것만 남겼습니다

2023-08-16 04:24 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/exception/ErrorCode.java
> +    RANK_OUT_OF_BOUNDS("R1", "좋아요 개수 랭킹 범위를 벗어나는 요청입니다. 좋아요 랭킹 요청의 페이지 확인이 필요합니다"),
랭킹 범위가 어디까지 가능한지 `format()`을 사용해서 알려주면 좋겠습니다!
MAX_RANK_SIZE를 public으로 열고 하면 될 것 같아요!

2023-08-16 04:43 UTC, merged