좋아요 순으로 랭킹을 보여주는 페이지를 제작한다.
woowacourse-teams/2023-yozm-cafe pull request #349
Opened 2023-08-13 10:27 UTC by jeongwusi

## #️⃣ 연관된 이슈

> 연관된 이슈 번호를 모두 작성해주세요

close #345

## 📝 작업 내용

- 랭킹 페이지와 관련된 MSW 핸들러, fetch 함수, 커스텀 훅, 컴포넌트 등을 구현하였습니다.
- 네비게이션 바에 랭킹 버튼 추가하였습니다. 관련해서 지금은 로고가 아닌 부분을 눌러도 버튼 기능이 작동이 되는데, 로고 부분만 눌러야 이동될 수 있도록 수정을 하였습니다.

## 💬 리뷰 요구사항

https://github.com/woowacourse-teams/2023-yozm-cafe/assets/122500517/d99bca91-959a-48d0-a668-5cb5da8a5bd2

영상 보시면 페이지 1에서 스크롤을 하면 2와 3페이지가 동시에 불러와집니다. 그래서 디바운스를 이용해서 해결해보려고 했는데 이게 예를 들어 3초 딜레이를 걸어도 하나씩 불러오는 게 아니라 3초 뒤에 2와 3페이지가 동시에 불러와집니다... 우선 구현한 내용 PR 올리며 확인부탁드립니다. 😊

2023-08-14 19:03 UTC, solo5star requested changes
> 영상 보시면 페이지 1에서 스크롤을 하면 2와 3페이지가 동시에 불러와집니다. 그래서 디바운스를 이용해서 해결해보려고 했는데 이게 예를 들어 3초 딜레이를 걸어도 하나씩 불러오는 게 아니라 3초 뒤에 2와 3페이지가 동시에 불러와집니다... 뭐가 문제인지 잘 모르겠네용 🥹 우선 구현한 내용 PR 올리며 확인부탁드립니다. 😊

저도 확인해보니 1페이지가 불러와진 상태에서 내려보니 즉시 2, 3 페이지가 로드되네요. 근데 아마 MSW에서 응답이 너무 빠른 나머지 DOM에 반영이 되기도 전에 2 페이지가 로드되었고 이 상태에선 intersection 상태는 여전히 바뀌지 않았기 때문에 '아 intersection.isIntersecting이 true니까 더 불러와야지' 라고 판단되어 3페이지가 불러와지는 식인 것 같습니다.

즉 intersection에 변경이 되었을 때에만(DOM이 업데이트되었을 때에만) 추가적으로 fetch가 일어나도록 해주면 되는데요, 아래의 코드 스니펫을 적용하니 정상적으로 1, 2, 3 페이지가 잘 불러와집니다.

```ts
  useMemo(() => {
    const shouldFetch = hasNextPage && !isFetching && intersection?.isIntersecting;

    if (shouldFetch) {
      fetchNextPage();
    }
  }, [intersection]);
```

2023-08-14 23:43 UTC, jeongwusi commented on client/src/styles/theme.ts
> +    tertiary: '#f4a9a8',
솔로스타의 의견에 동감합니다. 컬러 시스템을 좀 더 정교하게 운영할 필요성도 있다고 생각합니다. 다만 제가 `tertiary`를 적용하게 된 계기는  Google의 디자인 랭귀지인 [Material Design](https://m3.material.io/styles/color/the-color-system/key-colors-tones)를 참고 하여 도입을 하게 되었습니다.

![image](https://github.com/woowacourse-teams/2023-yozm-cafe/assets/122500517/3f2ddf88-1d10-4bd1-b9f9-ff99b584a9a2)

> The tertiary key color is used to derive the roles of contrasting accents that can be used to balance primary and secondary colors or bring heightened attention to an element. The tertiary color role is left for teams to use at their discretion and is intended to support broader color expression in products.

따라서 저는 `tertiary`까지는 괜찮다고 생각하는데... 솔로스타는 어떻게 보시나용?

2023-08-14 23:44 UTC, jeongwusi commented on client/src/styles/theme.ts
ㅋㅋㅋㅋ 디자인 시스템의 중요성을 다시 한번 느낍니당

2023-08-14 23:45 UTC, jeongwusi commented on client/src/data/mockData.ts
> -  },
넹넹 현재 좋아요 리스트는 Cafe 데이터를 참조하고 있습니닷

2023-08-14 23:53 UTC, jeongwusi commented on client/src/components/RankCard.tsx
> +    navigate(`/cafe/${id}`);
아 저거는 함수 이름을 수정이 필요하네용...^^; 저기 랭킹에서는 단건 조회라서 `/cafes/:id`가 맞습니당 ㅎㅎ

2023-08-15 00:05 UTC, jeongwusi commented on client/src/components/Button.tsx
> +    background-color: ${(props) => props.theme.color.tertiary};
![image](https://github.com/woowacourse-teams/2023-yozm-cafe/assets/122500517/599a4c46-4461-4dc8-8e62-895ba0797f05)

Material Design에서는 tonal이라는 명칭도 사용하던데... tonal은 어떠신가욤?

2023-08-15 05:49 UTC, solo5star commented on client/src/styles/theme.ts
> +    tertiary: '#f4a9a8',
`tertiary`는 제가 사용해본 적이 없어서... 제가 이해하고 있는 `primary`와 `secondary`처럼 정의해주신다면 좋지 않을까용?

> `primary`는 요즘카페의 브랜드를 나타내는 상징적인 색과 동시에 사용자의 시선이 가장 먼저 가는 색깔. "확인" 버튼 정도가 대표적인 예시일 거 같고,
> `secondary`는 `primary`보단 덜 중요한, `primary`의 대안으로 사용할 수 있을 것 같구요. "취소" 버튼이 대표적인 예시일 것 같네요.

2023-08-15 05:51 UTC, solo5star commented on client/src/components/Button.tsx
> +    background-color: ${(props) => props.theme.color.tertiary};
아 그런 뜻은 아니었구 secondary css인데 실제론 background-color가 tertiary로 사용되고 있어서 그런거였어용

2023-08-15 05:54 UTC, solo5star requested changes
`flex: 숫자`로 설정하면 부모 flexbox의 크기에 의존적으로 적용되어 뷰포트의 width가 작아지면 버튼도 작아지게 될거에요. 😭 마치 `width: 10%`, `width: 15%` 처럼 쓰는 거랑 똑같은 느낌이죠
고정 크기로 주는게 좋을 것 같아요!

2023-08-15 07:33 UTC, jeongwusi commented
> `flex: 숫자`로 설정하면 부모 flexbox의 크기에 의존적으로 적용되어 뷰포트의 width가 작아지면 버튼도 작아지게 될거에요. 😭 마치 `width: 10%`, `width: 15%` 처럼 쓰는 거랑 똑같은 느낌이죠 크기가 고정될 수 있도록 `flex: 숫자` 는 제거하는 것이 좋을 것 같아요!

네네 이 부분은 고정될 수 있도록 하는 게 더 좋을 거 같네용!

2023-08-15 07:46 UTC, jeongwusi commented on client/src/styles/theme.ts
> +    tertiary: '#f4a9a8',
> `tertiary color`: 이 색상은 주요 및 보조 색상을 균형있게 조절하거나 특정 요소에 강조를 줄 때 사용됩니다.

이 정도로 위와 같이 정리할 수 있을 거 같습니다. 그리고 지금 secondary 색상이 사용하는 곳이 없어서 secondary와 tertiary를 바꾸도록 하겠습니당

2023-08-15 08:11 UTC, solo5star approved these changes
굿 좋습니당

2023-08-15 10:43 UTC, geuntaek1013 approved these changes
고니, 고생하셨습니다!!

2023-08-16 01:17 UTC, merged