카페 메뉴 보기 기능 구현
woowacourse-teams/2023-yozm-cafe pull request #350
Opened 2023-08-14 16:03 UTC by solo5star

## #️⃣ 연관된 이슈
> **이 PR은 #338 PR 머지가 선행되어야 합니다.**

close #300

## 📝 작업 내용
|정보 모달에 대표 메뉴 표시|별도 모달에 모든 메뉴 표시|메뉴판 이미지로 보기|
|:-:|:-:|:-:|
|![](https://github.com/woowacourse-teams/2023-yozm-cafe/assets/20203944/2a35d3e2-6a0d-4584-9c84-387b7192d3e9)|![image](https://github.com/woowacourse-teams/2023-yozm-cafe/assets/20203944/58a9a04c-e34a-4598-9bcf-893bf8e079f9)|![image](https://github.com/woowacourse-teams/2023-yozm-cafe/assets/20203944/74c47858-5954-4949-8825-d1b6803065dd)|

* 관련 API 모킹 및 커스텀 훅 구현 진행하였습니다.
* **이미지 모달에서 pinch-zoom, panning 제스쳐는 구현되지 않았습니다.** 모바일에서 테스트해 본 결과, viewport 자체에서 pinch-zoom과 panning이 동작하기 때문에 사용에 큰 문제는 안될거라 보고 구현하지 않았습니다. 우선순위가 그닥 높지도 않구요.

## ⚒️ API Change

![image](https://github.com/woowacourse-teams/2023-yozm-cafe/assets/20203944/c5367740-46c1-41d2-9721-8065866dd44f)

* `document.bodyRoot`를 추가하였습니다. 이는 `<div id="root"></div>` 에 해당되며, 실제 우리 앱의 (가상) 뷰포트입니다. 모달이 실제 뷰포트(`<body></body>`)를 기준으로 사이즈가 책정되면 안되기 때문에 추가했어요. 타입도 정의해두었기 때문에 아래와 같이 사용하실 수 있을 겁니다.

```tsx
const ExampleModal = () => {
  // ...

  return React.createPortal(<div>MyModal</div>, document.bodyRoot);
}
```
`bodyRoot` 말고 더 좋은 이름이 있다면 추천해주세요!

## 💬 리뷰 요구사항
* 가볍게 백엔드 API랑 연결해보았을 때는 큰 문제는 없었어요.
* 모달은 추상화 작업을 한번 해야할 것 같습니다. 자주 사용되는데 비해 공통 컴포넌트가 없어요.

2023-08-14 23:04 UTC, jeongwusi requested changes
고생많으셨습니다~! 이번 작업을 통해 모달 부분을 굉장히 많이 작업을 하셨군요! 모달 관련된 추상화는 공감합니다. 개선해보도록 하죵 ^^ 코멘트 확인해주세용 ㅎㅎ

2023-08-14 23:04 UTC, jeongwusi commented on client/src/index.tsx
> +Object.assign(document, { bodyRoot: document.getElementById('root') });
> Object.assign() 메서드는 출처 객체들의 모든 [열거 가능](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Object/propertyIsEnumerable)한 [자체 속성 (en-US)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty)을 복사해 대상 객체에 붙여넣습니다. 그 후 대상 객체를 반환합니다.

이 `document.bodyRoot`를 index.tsx 파일을 통해 전역으로 사용할 수 있는건가요?

2023-08-15 05:39 UTC, solo5star commented on client/.storybook/webpack.config.js
> +}
#338 를 기반으로 작업하였기 때문에 #338 PR 머지가 선행되어야 해요 👀

2023-08-15 05:40 UTC, solo5star commented on client/package.json
> +    "webpack-merge": "^5.9.0"
이거도 #338 을 기반으로 해서 그렇습니다~~

2023-08-15 05:41 UTC, solo5star commented on client/src/components/CafeMenuList.tsx
> +};
여기에서만 사용할 것 같아 인라이닝을 했어요 🤔

2023-08-15 05:41 UTC, solo5star commented on client/src/types/index.ts
> +  isRecommended: boolean;
아니에요 ㅋㅋ 서로 충분히 합의된 내용입니닷 😁

2023-08-15 05:41 UTC, solo5star commented on client/src/hooks/useCafeMenus.ts
> + */
굿~!

2023-08-15 05:43 UTC, solo5star commented on client/src/index.tsx
> +Object.assign(document, { bodyRoot: document.getElementById('root') });
> index.tsx 파일을 통해

조금 모호한 말인것 같은데...
index.tsx가 import된 시점에서 전역으로 사용 가능할 겁니다!

2023-08-15 07:19 UTC, jeongwusi commented on client/src/components/CafeMenuList.tsx
> +};
https://github.com/woowacourse/react-lotto/discussions/63 해당 링크와 같은 내용에 대해서 어떻게 생각하시나용?

2023-08-15 07:23 UTC, jeongwusi commented on client/src/index.tsx
> +Object.assign(document, { bodyRoot: document.getElementById('root') });
이러한 부분도 추후에 모달 컴포넌트를 추상화 하면 분리를 해야하지 않나용?

2023-08-15 07:23 UTC, solo5star commented on client/src/components/CafeMenuList.tsx
> +};
링크에서 말하는 "인라인 함수"에는 해당이 안되는 것 같아요! 인라이닝이라 함은 별도로 분리하지 않았다 정도의 뜻입니다 🤔

2023-08-15 07:26 UTC, solo5star commented on client/src/index.tsx
> +Object.assign(document, { bodyRoot: document.getElementById('root') });
모달 뿐만 아니라 토스트 같은 뷰포트를 기준으로 하는 컴포넌트에도 `document.bodyRoot`를 사용해야 하기 때문에 전역으로 두는 것이 합당하다 생각됩니다.

2023-08-15 07:27 UTC, jeongwusi commented on client/src/components/CafeMenuList.tsx
> +};
아 그래용?? 인라이닝이라고 많이 쓰이는 방식인가요? 관련해서 레퍼런스도 있나용?

2023-08-15 07:28 UTC, jeongwusi commented on client/src/index.tsx
> +Object.assign(document, { bodyRoot: document.getElementById('root') });
오홍...! 그렇군여 알겠습니당

2023-08-15 07:29 UTC, solo5star commented on client/src/components/CafeMenuList.tsx
> +};
방식..이라기 보단 별도의 파일로 분리하지 않았다 정도로 받아들여주심 될 것 같습니다 ㅎㅎ..

2023-08-15 07:31 UTC, jeongwusi approved these changes
고생하셨습니당~!~!

2023-08-16 04:23 UTC, merged