어드민 API 이미지 업로드 기능 추가
woowacourse-teams/2023-yozm-cafe pull request #351
Opened 2023-08-14 18:25 UTC by nuyh99

## #️⃣ 연관된 이슈
- #322

## 📝 작업 내용
기존 카페 어드민 API에 이미지 관련 기능을 추가했습니다.
- 썸네일용, 모바일용, 원본 세 가지 버전의 이미지로 리사이즈해서 S3에 업로드합니다.
- 카페를 업데이트할 때는 기존의 이미지들을 전부 삭제하고 새로 업로드합니다.
- 카페를 제거할 때도 관련 이미지를 모두 삭제합니다.

2023-08-15 07:55 UTC, donghae-kim requested changes
고생하셨어요 폴로연어
단순하게 궁금했던 것들에 대해 남겨봤어요!

이미지 리사이징 코드를 작성하면서 고민(?) 했던 점이 있으면 공유해주시면 감사할것 같습니👍

2023-08-15 07:55 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/domain/resizedimage/ImageResizer.java
> +        if (image.getSize() > MAX_IMAGE_SIZE) {
5MB 초과 사진은 추가할 수 없는 건가요 ?!
기준을 5MB로 잡은 이유가 궁금합니당

2023-08-15 07:55 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/domain/resizedimage/ImageResizer.java
> +    public ImageResizer(final MultipartFile image, final String fileName) {
처음 봤을 때 ImageResiszer 면 이미지를 리사이징하는 util성 메소드들이 있을 것 같았어요. factory, generator 처럼 값을 삽입함으로써 이미지를 리사이징 해주는줄 알았습니다!

단순하게 검증된 객체만 생성을 해서 이후에 사용하는 것 같은데 조금 클래스명이 이게 맞나? 라는 생각이 드는데 어떻게 생각하시나요 ?

2023-08-15 07:55 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/service/ImageService.java
> +        resizedImages.forEach(s3Client::upload);
어떤 이유로 originalImage, 리사이즈 이미지를 따로 구별해서 하신건지 궁금합니다!
한번에 처리되도 되지 않을까? 라는 생각도 들어서요!

2023-08-15 07:55 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/domain/resizedimage/ImageResizer.java
> +    }
단순 궁금증인데 image를 가져올 때 꼭 이런식으로 변환과정이 필요한가요?
multipartfile로 객체에 저장된 것을 imageio로 읽고 byte배열로 변환하고 multipartfile로 변환하는 로직이 필수적인건지 궁금합니다.
처음 객체에 저장된것을 사용할 수는 없는지 ..

2023-08-15 07:55 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/domain/S3Client.java
> +                tempFile.delete();  // 임시 파일 삭제
로컬에 계속 쌓이기 때문에 임시 파일을 삭제하신건가요 ?-?

2023-08-15 07:55 UTC, donghae-kim commented on server/src/test/java/com/project/yozmcafe/domain/SizeTest.java
> +        assertThat(fileNames).containsExactlyInAnyOrder("original/image.png", "100/image.png", "500/image.png");
다른 사이즈가 추가될 경우에는 이 테스트가 깨질 수 도 있지 않을까요 ?

2023-08-15 07:55 UTC, donghae-kim commented on server/src/test/java/com/project/yozmcafe/domain/ImageResizerTest.java
> +        @DisplayName("예외가 발생하지 않는다")
ImageResizer 생성 테스트 속 예외가 발생하지 않는다 보단 성공관련 테스트가 나을 것 같아요.
예외가 발생하지 않는다는게 성공한다는 것 같아서요

2023-08-16 01:55 UTC, hum02 approved these changes
고생하셨습니다~~

2023-08-16 01:55 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/domain/resizedimage/ImageName.java
> +        return new ImageName(fileName + extension);
아 이미지 파일 이름을 이렇게 저장 시간으로 했군요! 이미지 파일 이름의 중복 확률을 낮출 수 있을 것 같습니다. 몰라서 그런데 SSSSSS정도의 시간이면 파일명이 충분히 겹치지 않으려나? 싶기도 합니다

2023-08-16 01:55 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/domain/resizedimage/ImageResizer.java
> +    }
저도 궁금하네요! 이미지를 toByteArray로 재구성해서 저장하는 방법말고는 없나요?

2023-08-16 01:55 UTC, hum02 commented on server/src/main/resources/application.properties
> +spring.servlet.multipart.max-request-size=50MB
음 이러면 한 요청에 5MB 사진 10개 이상이 담기면  servlet에서 예외가 발생하나요? 용량초과에 대한 예외상황도 생각해보긴 해야겠군요

2023-08-16 03:26 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/domain/resizedimage/ImageResizer.java
> +        if (image.getSize() > MAX_IMAGE_SIZE) {
핸드폰으로 사진을 찍어서 용량을 확인해보니,
5MB를 넘지 않길래 이렇게 정했습니다~

2023-08-16 03:27 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/domain/resizedimage/ImageResizer.java
> +    public ImageResizer(final MultipartFile image, final String fileName) {
이 클래스는 원본 이미지와 파일네임을 필드로 갖고 내부에서 리사이즈 해주는 역할을 하고있기에,
`ImageResizer`라는 네이밍을 가져갔는데, 혹시 더 좋은 네이밍이 있다면 추천해주세요!

2023-08-16 03:40 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/domain/S3Client.java
> +                tempFile.delete();  // 임시 파일 삭제
네넵 맞습니다. 해당 파일이 계속 로컬에 쌓이기 때문에 finally 에서 업로드 결과와 상관없이 삭제하는 로직을 추가했습니다.

2023-08-16 03:41 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/domain/resizedimage/ImageResizer.java
> +    }
`BufferedImage`를 통해서 리사이즈를 하고, 리사이즈된 `BufferedImage`를 `byte[]`로 변환하여 새로운 멀티파트 파일을 만들어 반환합니다.
그런데 오션이 코멘트를 남겨준 해당부분은 리사이즈 작업 없이 이미지의 이름만 변경해주는 작업을 하기에, 해당 메서드들을 사용할 필요가 없긴 하겠네요. `image.getBytes()`를 통해 바로 처리가 되겠네요 감사합니다!

2023-08-16 04:03 UTC, green-kong commented on server/src/test/java/com/project/yozmcafe/domain/ImageResizerTest.java
> +        @DisplayName("예외가 발생하지 않는다")
테스트에 대한 설명이 부족한듯 보이네요! 수정하겠습니다

2023-08-16 04:12 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/domain/resizedimage/ImageName.java
> +        return new ImageName(fileName + extension);
현재 로직에서는 0.000001초 단위 까지 겹칠일이 없을 것 같아요!
추후 리사이징과 업로드를 병렬처리로 변경하게 되면 겹칠수도 있겠다는 생각이 드네요!
이 부분은 추후 고도화 하면서 수정해도 되지 않을까요??

2023-08-16 04:12 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/domain/resizedimage/ImageResizer.java
> +    }
https://github.com/woowacourse-teams/2023-yozm-cafe/pull/351#discussion_r1295346345

2023-08-16 04:20 UTC, green-kong commented on server/src/main/resources/application.properties
> +spring.servlet.multipart.max-request-size=50MB
그렇네요. 현재 도메인단에서 5MB가 넘는 파일에 대해 예외를 던지고 있는데,
지금같이 설정이 되어있으면, 도메인까지 넘어오질 않고 500에러가 터지겠네요ㅎㅎ
요부분은 도메인에서 설정한 크기보다 조금더 넉넉하게 설정해야겠습니다 감사합니다!

2023-08-16 04:20 UTC, donghae-kim approved these changes
good imageResizer에 클래스에 대한 고민이 있었는데
역시 대면으로 들으니까 바로 해결되었습니다 고생하셨습니다~

2023-08-16 04:30 UTC, merged