feat: flyway 적용
woowacourse-teams/2023-yozm-cafe pull request #428
Opened 2023-09-01 07:27 UTC by green-kong

## #️⃣ 연관된 이슈

> resolved #427 

## 📝 작업 내용

> flyway 적용했습니다.
Versioning은 YYYYMMDDHHMMSS 형식으로 했습니다.
에시) `V202309011617__example.sql`

파일 이름 만들기 귀찮으실 거 같아서 쉘스크립트 작성했습니다.
**server 디렉토리 기준으로 실행시키셔야 정상적으로 돌아갑니다.**

실행 방법
<img width="1148" alt="image" src="https://github.com/woowacourse-teams/2023-yozm-cafe/assets/96301958/2c16f366-c91e-4ed4-b4be-7e74721cbaae">

서비 디렉토리에서 `./src/main/resources/flyway/createSql.sh` 이거 입력하면,
파일이름 입력하라 그러는데 스키마 변경사항 간략하게 입력해주시면 됩니다.
`src/main/resources/db/migration`에 `V{현재시간}__{입력한 파일이름}.sql` 로 파일 생성될거에여.
그럼 그 안에 변경사항 입력해주시면 됩니다.

## 💬 리뷰 요구사항

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요

2023-09-01 11:38 UTC, donghae-kim requested changes
쉘 스크립트로 바로 이름 생성하게 하는거 좋네요~

sql 문에 대한 의문점만 남겨보았어요 !

2023-09-01 11:38 UTC, donghae-kim commented on server/src/main/resources/db/migration/V20230901153300__init.sql
> +create table cafe
if not exists 존재하면 좋겠네요

또한 제약조건들을 하단 ddl로 작성한 이유도 궁금합니다!

2023-09-04 11:01 UTC, green-kong commented on server/src/main/resources/db/migration/V20230901153300__init.sql
> +create table cafe
application.properties에 `spring.flyway.baseline-version=20230901153300` 설정을 적용하여,
해당 버전 이후의 sql 파일만 적용되도록 설정되어있습니다!
그래서 굳이 `if not exist`를 사용하지 않았는데요 혹시 문제가 될 여지가 있을까요?
개인적으로는 문제될만한 상황이 떠오르지 않아서요 ㅎㅎ

제약조건들은 그냥 위에적으나 아래에적으나 똑같다고 생각해서 딱히 신경쓰지 않았습니다 ㅎㅎ

2023-09-04 11:01 UTC, green-kong commented on server/src/main/resources/db/migration/V20230901153300__init.sql
> +create table cafe
application.properties에 spring.flyway.baseline-version=20230901153300 설정을 적용하여,
해당 버전 이후의 sql 파일만 적용되도록 설정되어있습니다!
그래서 굳이 if not exist를 사용하지 않았는데요 혹시 문제가 될 여지가 있을까요?
개인적으로는 문제될만한 상황이 떠오르지 않아서요 ㅎㅎ

제약조건들은 그냥 위에적으나 아래에적으나 똑같다고 생각해서 딱히 신경쓰지 않았습니다 ㅎㅎ

2023-09-04 11:01 UTC, green-kong commented
오늘 연어가 얘기해준 out-of-order 설정 추가해주었습니다!

2023-09-04 14:19 UTC, nuyh99 approved these changes
고생하셨습니다!!
저는 의견만 남기고 Approve하겠습니당

2023-09-04 14:19 UTC, nuyh99 commented on server/src/main/resources/db/migration/V20230901153300__init.sql
> +    phone       varchar(255),
기존의 DDL과 대부분 달라진 것 같아요!
varchar의 길이나 default 값이나 외래키 제약의 제약 이름 등이요!

의도적으로 JPA의 기본 생성 DDL로 한 것인지 궁금합니다.

2023-09-04 14:19 UTC, nuyh99 commented on server/src/main/resources/db/migration/V20230901153300__init.sql
> +create table cafe
운영 환경은 어차피 flyway를 꺼뒀고, 개발 환경은 baseline 설정을 해뒀으니 상관없겠군요.

그럼 새로운 로컬 환경에서는 어떻게 되는지 궁금합니다.
새 데이터베이스로 띄우면 이 sql은 직접 DDL을 날려줘야 하는 지, 그럴 필요가 있을 지 궁금해요!

저도 있는 게 더 나을 것 같다고 생각해서요!
실수로 flyway 관련 설정을 바꿔버려서 적용되버리는 것도 막을 수 있을 것 같아요.

2023-09-04 14:19 UTC, nuyh99 commented on server/src/main/resources/flyway/createSql.sh
> +touch "./src/main/resources/db/migration/$filename"
셸 파일이 있는 위치에서 상대 경로로 저 위치에 만들어질 수 있나요??!

셸 파일 있는 거는 좋은 것 같아요!!

2023-09-04 14:19 UTC, nuyh99 commented on server/src/main/resources/application.properties
> +spring.flyway.out-of-order=true
이게 필요할 것 같아서 말했었는데 갑자기 궁금한 점이 있어요
baseline을 설정하면 초과 버전부터 적용되는데, out-of-order와 같이 사용하면 어떻게 되나요?

2023-09-05 00:48 UTC, hum02 commented on server/src/main/resources/flyway/createSql.sh
> +touch "./src/main/resources/db/migration/$filename"
/server 위치에서 보통 터미널을 많이 써서 이 위치를 기준으로 상대 경로로 작성했어요!

2023-09-05 05:55 UTC, hum02 approved these changes

2023-09-05 06:00 UTC, donghae-kim approved these changes
고생하셨어요 ~

2023-09-05 06:01 UTC, merged