좋아요를 추가와 취소 할 수 있는 기능
woowacourse-teams/2023-yozm-cafe pull request #43
Opened 2023-07-15 06:46 UTC by jeongwusi

## #️⃣ 연관된 이슈

> 연관된 이슈 번호를 모두 작성해주세요

close #4

## 📝 작업 내용

- 좋아요 추가 기능과 좋아요 취소와 관련된 MSW handler 생성
- 상태로 좋아요 취소와 추가 기능 생성
- client.ts 로직을 이용한 통신 로직 생성

## 💬 리뷰 요구사항

> 카페 정보와 관련된 것들을 상위 컴포넌트에서 받기 때문에 Home 페이지 컴포넌트에서 종합적으로 조합해서 최종적으로 만들어야 할 거 같아요!

2023-07-15 07:30 UTC, solo5star requested changes

2023-07-15 07:30 UTC, solo5star commented on client/src/components/LikeButton.tsx
> +  currentLikeCount: number;
`LikeButton` 컴포넌트에서 현재(current)라는 의미는 필요할 것 같진 않아요. `likeCount` 는 어떠실까요?

2023-07-15 07:30 UTC, solo5star commented on client/src/components/LikeButton.tsx
> +const LikeButton = ({ currentLikeCount }: LikeProps) => {
```suggestion
type LikeButtonProps = {
  currentLikeCount: number;
};

const LikeButton = ({ currentLikeCount }: LikeButtonProps) => {
```
`LikeButton` + `Props` 라는 식으로 네이밍하면 더욱 예측 가능하고 좋을 것 같습니다!

2023-07-15 07:30 UTC, solo5star commented on client/src/components/LikeButton.tsx
> +  };
`LikeButton`이 네트워크 요청의 책임까지 맡을 필요는 없을 것 같아요. 이 로직을 부모 컴포넌트에서 작성하고 `onClick` props로 넘겨주는 것이 더 좋을 것 같습니다.

2023-07-15 07:30 UTC, solo5star commented on client/src/components/LikeButton.tsx
> +`;
`HeartIcon` 이름은 어떨까요? 마크업만 보았을 땐 `HeartIcon` 으로 되어있는 편이 더 의미 전달이 잘 될 것 같아요!
```
    <Container>
      <HeartIcon $isActive={isActive} onClick={handleLikeClick} />
      <LikeCount>{likeCount}</LikeCount>
    </Container>
```

2023-07-15 07:30 UTC, solo5star commented on client/src/mocks/handlers.ts
> +  }),
```suggestion
  rest.post('/cafes/:cafeId/likes', (req, res, ctx) => {
    const { cafeId } = req.params;
    const updatedCafes = cafes.map((cafe) => {
      if (cafe.id === Number(cafeId)) {
        return { ...cafe, likes: cafe.likeCount + 1 };
      }
      return cafe;
    });
    return res(ctx.status(200), ctx.json(updatedCafes));
  }),
```
`cafe_id` 를 camelCase로 작성하면 좋지 않을까요?!

2023-07-15 07:30 UTC, solo5star commented on client/src/mocks/handlers.ts
> +        return { ...cafe, likes: cafe.likeCount + 1 };
`isLiked: true`가 필요할 것 같습니다. 그리고 `likes`가 아니라 `likeCount` 이었던거 같아요!

2023-07-15 07:30 UTC, solo5star commented on client/src/mocks/handlers.ts
> +        return { ...cafe, likes: cafe.likeCount - 1 };
여기도 `isLiked`, `likeCount` 확인해주세요!

2023-07-15 07:55 UTC, jeongwusi commented on client/src/components/LikeButton.tsx
> +  currentLikeCount: number;
```js
const LikeButton = ({ currentLikeCount }: LikeProps) => {
  const [isActive, setIsActive] = useState(false);
  const [likeCount, setLikeCount] = useState(currentLikeCount);

  const handleLikeClick = async () => {
    try {
.
.
.
```

위의 코드에서 `const [likeCount, setLikeCount] = useState(currentLikeCount);` 상태의 이름을 likeCount로 해서 currentLikeCount라고 했습니다. 

아무래도 카운트의 경우 Props로 현재의 카운트를 보여주는 것이기 때문에 current~가 괜찮다고 생각했는데용 어떻게 생각하시나요?

2023-07-15 08:10 UTC, jeongwusi commented on client/src/components/LikeButton.tsx
> +const LikeButton = ({ currentLikeCount }: LikeProps) => {
아 원래 컴포넌트 이름이 Like 였다가 중간에 LikeButton으로 변경했는데요...! 그래서 누락이 있었던 거 같습니당 ^^; 수정하도록 하겠습니닷

2023-07-15 08:16 UTC, jeongwusi commented on client/src/components/LikeButton.tsx
> +  };
그러면 이 로직은 페이지에서 작성을 해야겠네여

2023-07-15 08:17 UTC, jeongwusi commented on client/src/components/LikeButton.tsx
> +`;
아항...! 넷넷 좋습니다

2023-07-15 08:18 UTC, jeongwusi commented on client/src/mocks/handlers.ts
> +  }),
뭔가 API 이름을 맞춰야 해야하나 해서 그렇게 했는데 저희 컨벤션 상 생각해보면 camelCase가 더 올바른 거 같네여

2023-07-15 08:18 UTC, jeongwusi commented on client/src/mocks/handlers.ts
> +        return { ...cafe, likes: cafe.likeCount - 1 };
넷넷

2023-07-15 08:19 UTC, jeongwusi commented on client/src/mocks/handlers.ts
> +        return { ...cafe, likes: cafe.likeCount + 1 };
넷넷

2023-07-16 06:54 UTC, solo5star commented on client/src/components/LikeButton.tsx
> +  currentLikeCount: number;
아 지금 보니 `likeCount` 상태를 `Button`에서 관리하네요. 부모가 `likeCount` 상태를 관리하는게 좋지 않을까요? `<LikeButton />` 컴포넌트 스스로가 네트워크 요청 등 주요 기능을 가진다면 `<LikeButton />` 컴포넌트가 상태를 가지고 스스로 제어하는 것이 좋겠지만 `<LikeButton />` 이 그 정도 크기의 컴포넌트라는 생각은 들지 않아서요.

2023-07-16 06:54 UTC, solo5star commented on client/src/components/LikeButton.tsx
> +const LikeButton = ({ currentLikeCount }: LikeProps) => {
굿~ 좋아용 🫡

2023-07-16 06:55 UTC, solo5star commented on client/src/components/LikeButton.tsx
> +  };
넵 그렇게 되겠네요

2023-07-16 06:55 UTC, solo5star commented on client/src/mocks/handlers.ts
> +  }),
params의 이름은 안 맞춰줘도 될 것 같아요~ 어차피 placeholder니까요

2023-07-16 06:56 UTC, solo5star commented on client/src/mocks/handlers.ts
> +        return { ...cafe, likes: cafe.likeCount + 1 };
다섯다섯

2023-07-16 06:56 UTC, solo5star commented on client/src/mocks/handlers.ts
> +        return { ...cafe, likes: cafe.likeCount - 1 };
넷마블~

2023-07-16 07:37 UTC, geuntaek1013 approved these changes
수고하셨습니다:)

2023-07-16 11:33 UTC, jeongwusi commented on client/src/components/LikeButton.tsx
> +  currentLikeCount: number;
음... 그러면 통신 로직을 빼는 게 더 좋겠네여

2023-07-16 12:12 UTC, jeongwusi commented on client/src/types/index.ts
> +type AvailableTime = {
해당 네이밍은 백엔드 API 명세대로 작성한 부분이라 백엔드와의 상의가 필요할 것으로 보입니다.

2023-07-16 12:14 UTC, solo5star commented on client/src/types/index.ts
> +type AvailableTime = {
음~ API 명세에 명시된 내용이라면 명세를 따르는게 좋겠습니다

2023-07-16 12:22 UTC, solo5star requested changes
수정하신거 확인했습니다! 하나만 확인해주세용

2023-07-16 12:22 UTC, solo5star commented on client/src/components/LikeButton.tsx
>  };
```suggestion
type LikeButtonProps = {
  likeCount: number;
  onChange: (likeCount: number) => void;
};
```
사용자가 버튼을 클릭했을 때 부모 컴포넌트가 알 수 있도록 콜백 함수를 props로 추가하는 것이 좋을 것 같아요

2023-07-16 12:51 UTC, geuntaek1013 commented on client/src/types/index.ts
> +type AvailableTime = {
네 명세 확인했습니다!!

2023-07-16 12:57 UTC, jeongwusi commented on client/src/components/LikeButton.tsx
>  };
넷넷 추가 했고 임의로 Home에도 관련된 함수 넣었습니다!

2023-07-16 12:59 UTC, solo5star commented on client/src/components/LikeButton.tsx
>  };
너무 좋습니다

2023-07-16 12:59 UTC, solo5star approved these changes

2023-07-16 22:53 UTC, merged