n+1 개선
woowacourse-teams/2023-yozm-cafe pull request #441
Opened 2023-09-07 08:33 UTC by donghae-kim

## #️⃣ 연관된 이슈

> #430 

## 📝 작업 내용

> n+1 문제를 해결하였습니다.

### CafeRepository
사용하는 쿼리들에 대해서 left join fetch을 이용해서 최대한 n+1을 제거하였습니다.
가장 크게 고민했던 부분은 ElementCollection인 Detail.availableTimes , Images.urls을 한번에 fetch join 하고 싶었지만, oneToMany 특성상 불가해서 다른 방법을 고민하였습니다.
1. Set으로 변경 -> fetch join 시 set을 이용하면 회피 가능 하지만 set자료구조로 변경시 get도 어렵고 순서보장도 어렵다는 단점
2. BatchSize -> 1 + (db 특정 컬럼 / 1000(현재는 1000개로 디폴트설정))만큼의 쿼리가 생기지만 전보다는 유의미할 정도로 많이 줄어듬
이 두가지에서 고민을 했을 때 2번의 방법이 약간의 쿼리 발생 하지만 (우리 프로젝트에서는 최대 2개 정도 예상) 1번보다는 사용하기도 좋을 것 이라고 판단하여 2번의 방법을 사용하였습니다.

하나의 onetomany를 fetchjoin 하고 이후에 다른 onetomany를 batchsize로 요청을 하는 식 입니다.
그럼 이 경우 어떤 것을 fetchjoin 하는가 ? -> 현재 저는 images, availableTimes 중 image를 선택하였습니다. 
images 의 개수가 availableTimes 보다 많기 때문에 batch in 절로 가져오는 것보다는 fetchjoin하고 availableTimes를 batch in절로 가져왔습니다.

### MemberRepostiory
멤버에도 위에와 마찬가지로 unviewedCafe와 likedCafe를 같은 고민을 진행했고 likedCafe를 batch절로 가져왔습니다.

---

Cafe같은 경우에 실제 case 로 테스트 해보니
쿼리 개수는 11 -> 2개
시간은 비슷한 결과가 나왔습니당
더 많이 조회할 수록 더 차이가 벌어져요

2023-09-08 07:32 UTC, hum02 approved these changes
좋아요~~

2023-09-08 07:32 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeRepository.java
> +            LEFT JOIN FETCH c.images.urls
이 부분 cafeServiceTest.getCafesForUnLoginMember 테스트 돌려보아서 where in절이 잘 나가는 건 확인했는데, 이게 어떻게 가능한 지 잘 모르겠네요 ㅠ 
defaut_batch_fetch_size설정으로 lazy로딩 해올 때 알아서 where in절로 실행되게 만들 수 있는 건가요? 포스팅하면 가서 보겠슴다

2023-09-10 13:15 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/domain/menu/MenuBoardRepository.java
> +            LEFT JOIN FETCH c.images.urls
사실 지금 당장 cafe까지 가지고 올 필요는 없습니다! 아무데서도 사용하지도 않고 직렬화하는 과정에서조차 안쓰니까요! 처음에는 확장성 때문에 고민했었는데 오히려 그게 더 낭비일것 같다는 생각에 바로 지워버렸습니다

2023-09-10 13:16 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/domain/menu/MenuRepository.java
> +            LEFT JOIN FETCH c.images.urls
맞아요 ㅠㅠ  Menu 쪽은 딱히 건드릴게 없더라고요

2023-09-10 13:26 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeRepository.java
> +            LEFT JOIN FETCH c.images.urls
lazyLoading 시 연관된 엔티티를 조회할 때 지정된 size 만큼 SQL의 IN절을 사용해서 조회됩니다.

Cafe 100개를 조회하고, 이후에 availbleTime을 조회하려고 하는 상황일때, Cafe id 100개를 모두 알고 있으니 이를 in절을 사용하여 availbleTime을 조회하는 방식입니다!

2023-09-10 13:26 UTC, donghae-kim commented
오늘 다시한번 봤는데 N+1 개선이라고 해놓고 엄청 크게 한 것은 없네요 .. 적용한 것보다 그냥 공부한게 더많은 것 같아요 흑흑

2023-09-11 06:35 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/Images.java
> +    @ElementCollection(fetch = FetchType.LAZY)
아 이거 lazy로 바꾸면 깨지는 테스트 있지 않나요?
<img width="403" alt="images eager변경하면 깨지는 테스트" src="https://github.com/woowacourse-teams/2023-yozm-cafe/assets/96762301/7421229d-193b-4787-84a8-055be5784360">

2023-09-11 14:50 UTC, nuyh99 approved these changes
굿굿!
사실 이 고도화 부분은 실제 사용하면서 확인해봐야할 것 같아서 현재로써 충분하다고 생각됩니다!

2023-09-12 06:45 UTC, green-kong requested changes
덕분에 공부가 많이 되었습니다!
다만 @Param 붙여주시면 안될까요.... 헿
[영한님이 붙이래요](https://www.inflearn.com/questions/24879/query-%EC%82%AC%EC%9A%A9%EC%8B%9C-param-%EC%96%B4%EB%85%B8%ED%85%8C%EC%9D%B4%EC%85%98%EC%9D%B4-%ED%95%84%EC%88%98-%EC%9D%B8%EA%B0%80%EC%9A%94)

2023-09-12 06:45 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeRepository.java
> +            """)
textBlock! 완전 까먹고 있었는데.. 👍

2023-09-12 14:48 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeRepository.java
> +            """)
@param 추가완료했는데 제가 봤을때 붙일 곳이 한군데 뿐이더라고요!
제 것에서는 테스트가 워낙 잘 작동해서 .. 폴로가 테스트 한번만 돌려주시면 고마울것같아요 👍

2023-09-13 06:37 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeRepository.java
> +            """)
모두 정상적으로 돌아가네요!!
고마워요 오션!!

2023-09-13 06:37 UTC, green-kong approved these changes
수고하셨습니다!!

2023-09-13 06:38 UTC, merged