카페 검색 기능 개발
woowacourse-teams/2023-yozm-cafe pull request #443
Opened 2023-09-10 13:43 UTC by hum02

## #️⃣ 연관된 이슈

- #433 

## 📝 작업 내용

- querydsl 적용 위한 의존성 추가 및 설정
- 검색 위한 cafeQueryRepository와 api구현

## 💬 리뷰 요구사항

- CafeQueryRepository.searchCafesByWord()가 꽤 클린하지 못합니다...
   검색 기준에 따른 join문을 작성하는 걸 다른객체의 책임으로 넘길까도 생각했지만 
  이게 쿼리문이다 보니 더 읽기 어려워지는 듯했어요.
   더 고민해보겠지만 좋은 의견 있으면 말해주세요.

- Cafe.images의 fetchjoin문제
  querydsl이 embeded객체에 대한 fetch join을 지원해주지 않아서 images를 효율적으로 가져오려면 조금 다른 방법이 필요한데
  1. Images를 entity로 바꾸고 cafe에 oneToOne매핑하는 등의 엔티티 변경
  2. CafeQueryRepository.searchCafesByWord()에서 엔티티가 아닌 dto를 반환하게 
  하고 직접 매핑
  -> 2의 방법이 fetch join으로 인한 위험성을 피하고 엔티티의 수정도 없어서 합리적이라고 생각해요. 이에 대해 의견 주시면 생각해서 반영할게요
  
- 검색 기능에 페이징 붙이기까지도 해야하는데, 좀 오래 붙들고 있기도 했고 pr이 커질 것 같아서 1차적으로 리뷰 요청해봅니다.

2023-09-11 07:51 UTC, donghae-kim requested changes
고생하셨어요 도치~ 역시 querydsl 어렵네요..

진행한 사항에 대해서만 의견 남겨봤습니다

CafeQueryRepository.searchCafesByWord()가 꽤 클린하지 못합니다...
` 댓글에 궁금한점을 먼저 달았습니다 ! `

Cafe.images의 fetchjoin문제

querydsl이 embeded객체에 대한 fetch join을 지원해주지 않아서 images를 효율적으로 가져오려면 조금 다른 방법이 필요한데
Images를 entity로 바꾸고 cafe에 oneToOne매핑하는 등의 엔티티 변경
CafeQueryRepository.searchCafesByWord()에서 엔티티가 아닌 dto를 반환하게
하고 직접 매핑
-> 2의 방법이 fetch join으로 인한 위험성을 피하고 엔티티의 수정도 없어서 합리적이라고 생각해요. 이에 대해 의견 주시면 생각해서 반영할게요

` 결국 image랑 cafe 간 onetomany 관계인데 단순하게 embedded로 되어있다고 해서 아예 안되는것인가요 ? 잘 이해가 좀 안가네요 ㅠㅠ jpql 기반이면 될 것 같아서요 !! 혹시 자료같은게 있을까요? 만약에 안된다고 하면 entity를 변경하는 것 외의 방법을 선택하는게 좋아보입니다!`

검색 체크박스가 어떤식으로 검색되어야 할까- and식으로? or식으로?
`저는 or 식이 현재 상황에서 좀 더 적절하지 않나 라는 생각이 들어요 ! 다만 모두 체크가 되지않았을때는 다르게 고려를 해야될 것 같고요`

2023-09-11 07:51 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/service/CafeService.java
> +    private final CafeQueryRepository cafeQueryRepository;
따로 repository를 분리해야할까요 ? 결국에는 CafeRepository라고 생각해서 이를 QueryRepository를 extends해서 CafeRepository하나로 사용하는게 더 좋아보여서요 !

2023-09-11 07:51 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeQueryRepository.java
> +        final JPAQuery<Cafe> baseQuery = queryFactory.selectFrom(cafe)
저는 처음에 이런식으로 구현되는 것을 생각했었는데 위아래 추가적인 코드를 보니 조금 헷갈리네요 .. menu를 join 한 것과 join을 종류별로 나눈 것에 대해 왜 이렇게 진행했는지 도치의 의견이 궁금합니다!

2023-09-11 13:10 UTC, green-kong requested changes
어렵습니다 queryDsl..!
갖고있는 초라한 지식 내에서 최대한 리뷰해봤습니다..!
몇가지 궁금한 점 질문 남겼어요!

2023-09-11 13:10 UTC, green-kong commented on server/src/test/java/com/project/yozmcafe/domain/cafe/CafeQueryRepositoryTest.java
> +    }
searchWord를 `음료` 로 변경했을 때 테스트가 깨질거라 예상했는데... 잘 돌아가네요..?
QueryRepository에서 groupBy 사용이 없어서 중복되는 데이터가 반환되진 않을까 했는데,
정상적으로 동작하네요... 왜죠? queryDsl에서 기본으로 중복된 데이터를 제거해주는건가요???

2023-09-11 15:41 UTC, nuyh99 requested changes
메서드의 동작을 잘 모르겠어서 내일 기획에 대해서 물어볼게요...!

2023-09-11 15:41 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/controller/dto/cafe/CafeThumbnailResponse.java
> +        final Cafe cafe = likedCafe.getCafe();
필요한 건 `Cafe` 클래스인데 이 DTO는 `LikedCafe`와의 참조도 가지고 있어요!

1. 비록 게터이지만 DTO에서 도메인의 메서드를 호출합니다. 외부에서 `Cafe`를 주는 게 더 좋을 것 같다고 생각해요.
2. 파라미터에 final이 없어요!

2023-09-12 01:30 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeQueryRepository.java
> +        }
보통 서비스를 사용하면서 아무 필터를 걸지 않고 검색을 하면 모든 기준 안에서 검색되기를 기대한다고 판단했어요!
꼭 하나 이상의 검색 기준을 선택한 후에야 검색이 가능하다면 사용 시 너무 귀찮을 것 같아요..

2023-09-12 01:33 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeQueryRepository.java
> +                        .and(containsMenu(isMenu, searchWord)));
연어도 이런 말을 했는데 이렇게 하나의 검색어만 강제된다면 querydsl을 쓰는 의미가 적기도 하고, 검색의 사용성도 떨어지는 게 맞습니다..

검색 기준마다 검색어를 설정할 수 있도록 기능에 대해서 아인과 더 애기해봐야겠어요 ㅠㅠ

2023-09-14 07:09 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/controller/CafeController.java
> +                                                      @RequestParam(value = "isCafeName", required = false, defaultValue = "false") final boolean isCafeName,
카페 이름, 메뉴, 주소마다 검색어를 설정하도록 기획 수정했어요!

2023-09-14 07:11 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeQueryRepository.java
> +        final JPAQuery<Cafe> baseQuery = queryFactory.selectFrom(cafe)
menu만을 조회할 때에는 inner join이 효율적이지만,
menu조건 뿐 아니라 다른 조건도 걸려있다면 inner join을 하면 다른 조건을 위한 데이터가 삭제가 되기에 outer join을 해야해서 분기문이 생겼었어요!

2023-09-14 07:14 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeQueryRepository.java
> +    }
크흠.. 시정하겠습니다

2023-09-14 08:37 UTC, hum02 commented
> 결국 image랑 cafe 간 onetomany 관계인데 단순하게 embedded로 되어있다고 해서 아예 안되는것인가요 ? 잘 이해가 좀 안가네요 ㅠㅠ jpql 기반이면 될 것 같아서요 !! 혹시 자료같은게 있을까요? 만약에 안된다고 하면 entity를 변경하는 것 외의 방법을 선택하는게 좋아보입니다!

단순히 embedded지원이 안된다 말하니 설명이 부족했네요ㅠ
embedded이면서 다른 테이블에 있어서 join을 해와야 할 때  문제가 있는 듯합니다.
<img width="513" alt="image" src="https://github.com/woowacourse-teams/2023-yozm-cafe/assets/96762301/51d536a3-209f-4305-b013-1761c69a2c0d">
class정보를 알고있는 querydsl의 입장에서 엔티티에 이미 있는 필드인데 join을 한다는 걸 받아주지 못하는 것 같아요...
official한 자료가 있으면 좋겠는데 공식문서가 자세하지는 않네요
https://jojoldu.tistory.com/372
이 글에서도 embedded지원이 안된다는 내용이 있습니다. 더 좋은 레퍼런스를 찾으면 공유할게요

2023-09-14 09:56 UTC, hum02 commented
>  결국 image랑 cafe 간 onetomany 관계인데 단순하게 embedded로 되어있다고 해서 아예 안되는것인가요 ? 잘 이해가 좀 안가네요 ㅠㅠ jpql 기반이면 될 것 같아서요 !! 혹시 자료같은게 있을까요? 만약에 안된다고 하면 entity를 변경하는 것 외의 방법을 선택하는게 좋아보입니다!`

제가 설명이 부족했네요.. 그리고 embedded타입 안의 필드에 직접 접근해서 fetch join도 해올 수 있습니다. 
<img width="513" alt="스크린샷 2023-09-14 오후 5 22 45" src="https://github.com/woowacourse-teams/2023-yozm-cafe/assets/96762301/8cb10a68-100d-4f37-b57a-35d2e896cee3">
이렇게 직접 해봐서 안되었었고 https://kkambi.tistory.com/193 이 글에서도 embedded의 지원이 안된다는 내용이 있어 그렇게 알고 있었네요.. 공식문서에도 자세한 설명이 없어 알기 어려웠습니다.
<img width="502" alt="image" src="https://github.com/woowacourse-teams/2023-yozm-cafe/assets/96762301/985a84d3-1f53-4c31-a892-5982d3dff508">
이렇게 직접 필드에 접근하면
<img width="253" alt="image" src="https://github.com/woowacourse-teams/2023-yozm-cafe/assets/96762301/5ab5763a-eda0-4b61-8122-df83683dc736">
cafe필드에 잘 포함해서 가져오네요

2023-09-14 11:29 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeQueryRepository.java
> +        }
메뉴가 포함될 경우 -  menu테이블까지 join을 해야하는데
  -메뉴만 검색할 경우 : inner join이 효율적
  -메뉴말고 다른 기준도 존재할 경우: inner join하면 다른 기준 검색위한 데이터가 제거되기에 outer join
이외의 경우 join할 필요가 없기에 join안 하는 게 효율적

이러한 차이점들이 있었어요!

2023-09-14 12:04 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/controller/dto/cafe/CafeThumbnailResponse.java
> +        final Cafe cafe = likedCafe.getCafe();
수정했어요!

2023-09-14 15:51 UTC, nuyh99 approved these changes
고생하셨습니다!!

도치가 한 부분은 아니지만 관련 부분도 리팩토링하면 어떨까 싶어서 코멘트로만 남겨봤습니다!
반영은 원하는 대로 하시면 좋겠군요!
Approve 하겠습니당

2023-09-14 15:51 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeCustomRepositoryImpl.java
> +                .where(
먼저 batch size가 걸려있어서 In 절로 이미지들을 가져올 수 있는데 innerJoin으로 가져오는 이유가 궁금하구요! 물론 쿼리 갯수는 1번으로 줄지만 Cartesian Product가 발생하니 더 빠를 지는 측정해봐야 알 것 같아요.

그리고 Hibernate 6에서는 부모 엔티티에 대해서 항상 중복 제거를 해줍니다. 따라서 `distinct`나 쿼리 힌트를 추가로 날릴 필요가 없어요. [여기의 DISTINCT 절을 참고해주세요](https://docs.jboss.org/hibernate/orm/6.0/migration-guide/migration-guide.html)
혹시나 다른 이유 때문에 쓰신 걸까요?

2023-09-14 15:51 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/service/CafeService.java
> +    public List<CafeSearchResponse> getCafesByKeyWord(final String cafeNameKeyWord, final String menuKeyWord, final String addressKeyWord) {
컨트롤러에서 Search라는 용어를 썼으니 여기도 `getCafesBySearch` 등이 혼란이 없을 것 같아요! 아니면 keyword로 통일을 하거나요!

2023-09-14 15:51 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/service/CafeService.java
> +        if (StringUtils.isBlank(menuKeyWord)) {
static import가 좋을 것 같습니다!

분기에 따른 재할당보다는 DTO를 파라미터로 받아서 List<Cafe>를 리턴해주는 메서드를 만드는 건 어떨까요?

```java
final List<Cafe> cafes = findAllBy(searchRequest);

return cafes.stream()
        .map(CafeSearchResponse::from)
        .toList();
```
이런 식으로 될 것 같네요!

2023-09-14 15:51 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/service/LikedCafeService.java
> +                .map(LikedCafe::getCafe)
애초에 `Member`에서 List<Cafe>를 받을 수 없을까 고민해보다가 옛날 코드들을 보게 됐는데요!

1. `Member` 내부 `getLikedCafesSection` 메서드에 `reverseLikedCafes`라고 돼있는데 그냥 `likedCafes`라고 하는게 나을 것 같네요...!
2. `LikedCafe`를 서비스에서 사용하기보다는 `Member` 내부로 숨기는 것이 나을 것 같아요. `Member`에서 애초에 `List<Cafe>`를 리턴하는 것이 좋을 것 같다는 생각입니다.
3. 아래의 `getLikedCafes` 내부의 첫 번째 줄은 `pageable.getOffset()` 메서드를 활용하면 깔끔해질 것 같네요!

위의 사항을 다 적용하면,
```suggestion
public List<CafeThumbnailResponse> findLikedCafeThumbnailsByMemberId(final String memberId, final Pageable pageable) {
        final Member member = memberService.findMemberByIdOrElseThrow(memberId);

        final List<Cafe> likedCafes = member.getLikedCafes(pageable.getOffset(), pageable.getPageSize());

        return likedCafes.stream()
                .map(CafeThumbnailResponse::from)
                .toList();
    }
```
이러한 형태가 될 것 같고 `LikedCafeService#getLikedCafes` 메서드는 필요가 없어보여요!

2023-09-14 15:51 UTC, nuyh99 commented on server/build.gradle
> +    //queryDsl
위의 다른 의존성들도 대문자로 시작하니 `QueryDSL`은 어떨까요?!

2023-09-14 15:51 UTC, nuyh99 commented on server/src/test/java/com/project/yozmcafe/controller/CafeControllerTest.java
> +                () -> assertThat(cafeResponse.likeCount()).isZero(),
굿

2023-09-14 15:51 UTC, nuyh99 commented on server/src/test/java/com/project/yozmcafe/domain/cafe/CafeCustomRepositoryImplTest.java
> +
이러한 부분은 다 제거하는 것이 좋을 것 같습니다..!

2023-09-14 15:51 UTC, nuyh99 commented on server/src/test/java/com/project/yozmcafe/domain/cafe/CafeCustomRepositoryImplTest.java
> +class CafeCustomRepositoryImplTest extends BaseTest {
메뉴 + 주소 조합의 테스트 하나와 아무 조건이 없을 때의 테스트 하나가 더 추가되면 좋을 것 같아요!

2023-09-14 15:51 UTC, nuyh99 commented on server/src/test/java/com/project/yozmcafe/domain/cafe/CafeCustomRepositoryImplTest.java
> +import static org.junit.jupiter.api.Assertions.*;
도치 혹시 와일드카드 설정 안 꺼두셨나요...??
물론 테스트라서 딱히 상관 없긴 합니다.

2023-09-14 15:51 UTC, nuyh99 commented on server/src/test/java/com/project/yozmcafe/fixture/Fixture.java
> +    }
이건 그냥 `Menu`의 생성자 같은데 Fixture로 쓰는 의미가 궁금합니다...!

2023-09-15 01:23 UTC, hum02 commented on server/src/test/java/com/project/yozmcafe/domain/cafe/CafeQueryRepositoryTest.java
> +    }
우선 fetch join이 아니라 sql의 join을 건 거라 연관된 엔티티까지 가져오지 않아요!
그래서 억지로 fetch join을 걸면 어떻게 될까? 생각해보면 Cafe엔티티는 Menu엔티티를 참조하지 않기에 애초에 fetch join 문을 적용할 수가 없는 구조네요.

2023-09-15 05:33 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeCustomRepositoryImpl.java
> +                .where(
쿼리 갯수를 1번으로 하기 위해서 수정했어요! 그런데 N+1을 해결하면서 batch size설정을 했기에 굳이 이렇게 할 필요는 없을 것 같네요.
distinct잘 먹겠습니다

2023-09-16 04:05 UTC, donghae-kim requested changes
Repository 쪽 관련 질문만 조금 달아봤습니다! 연어가 댓글을 잘 달아줘서 이것 정도만 말해주면 될 것 같아요 !

2023-09-16 04:05 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeCustomRepositoryImpl.java
> +    public List<Cafe> findAllBy(final String cafeNameWord, final String menuWord, final String addressWord) {
아직 쿼리 dsl을 학습하지 않아서 잘은 모르겠지만 제가 이번에 근로 학습을 하면서 봤던 것은 지금처럼 cafeNameWord, menuWord, addressWord에 따라 메소드 오버로딩을 할 필요 없이 한 메소드를 통해서 진행할 수 있었는데 지금은 불가한 것일까요 ?

왜 오버로딩했는지가 궁금합니다! 단순하게 leftJoin, innerJoin 때문에 분리한건지도요 !

2023-09-17 03:30 UTC, green-kong approved these changes
죄송합니다. 리뷰가 너무 늦었네요 죄송합니다.
연어랑 오션이 이미 많은 리뷰 남겨 주셔서 크게 남길건 없었습니다.

service쪽 cafe 재할당이랑, 쿼리 관련해서 코멘트 남겨놓았습니다.
감사합니다. 죄송합니다.

2023-09-17 03:30 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeCustomRepositoryImpl.java
> +                .fetch();
요거 left join 일 필요가 있나요?? 검색이면 있는 것중에서 찾는 걸텐데.. 라는 생각이 드네요ㅎㅎ

2023-09-17 03:30 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/service/CafeService.java
> +    }
```suggestion
    public List<CafeSearchResponse> getCafesByKeyWord(final String cafeNameKeyWord, final String menuKeyWord,
                                                      final String addressKeyWord) {
        final List<Cafe> cafes = asdf(cafeNameKeyWord, menuKeyWord, addressKeyWord).get();

        return cafes.stream()
                .map(CafeSearchResponse::from)
                .toList();
    }

    private Supplier<List<Cafe>> asdf(final String cafeNameKeyWord, final String menuKeyWord,
                                      final String addressKeyWord) {
        if (menuKeyWord.isBlank()) {
            return () -> cafeRepository.findAllBy(cafeNameKeyWord, addressKeyWord);
        }
        return () -> cafeRepository.findAllBy(cafeNameKeyWord, menuKeyWord, addressKeyWord);
    }
```

저도 재할당은 좀 보기싫어서 좋은 방법 없을까 하다가.
이런건 어떤가요?
펑셔널인터페이스 맛도리~

2023-09-19 07:07 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/service/CafeService.java
> +        if (StringUtils.isBlank(menuKeyWord)) {
menu검색이 아닐때에는 join을 하지 않으려고 분기를 했는데,
service나 repository 둘 중 하나에서는 분기문이 생기는 듯해요.
그래서 menu검색을 하든 말든 leftjoin하도록 이번에 수정해봤는데 어떨까요?

2023-09-19 07:46 UTC, hum02 commented on server/src/test/java/com/project/yozmcafe/fixture/Fixture.java
> +    }
아 설정할 필요없는 인자는 여기서 정해진 값으로 들어가게 수정할게요!

2023-09-19 07:59 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/service/CafeService.java
> +        else {
leftjoin으로 통일하도록 해봤어요!

2023-09-19 08:10 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeCustomRepositoryImpl.java
> +    public List<Cafe> findAllBy(final String cafeNameWord, final String menuWord, final String addressWord) {
오버로딩 했던 이유가 menu검색을 하지 않을 경우에는 cafe엔티티만으로 검색이 가능해서에요!
그래서 분기문으로 menu검색이 없을 때는 불필요한 조인을 하지 않도록 하려 했습니다.

그런데 불필요한 join이라면 db측의 옵티마이저가 알아서 최적화해주지 않을까? 하는 생각이 드네요.

2023-09-19 10:16 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/service/CafeService.java
> +        else {
아 이 부분 join을 안할때는 다른 메서드로 실행하려 하니 어렵네요....
아래에서 폴로가 언급한 대로 메서드 분리해서 수정해보았어요!

2023-09-19 10:19 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/service/CafeService.java
> +    }
폴로 천재!

2023-09-19 11:06 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/service/LikedCafeService.java
> +                .map(LikedCafe::getCafe)
이거 고쳤는데 LikedCafeServiceTest쪽 테스트가 실패하더라고요!
왜인지 보니 원래 transactional을 붙여서 테스트 코드에서 변경감지를 이용했었던 걸 transactional을 뺀 후 수정하지 않아서 같아요. 
변경감지를 이용해서 작성한 테스트 코드가 더 있을 수도...?

2023-09-19 12:15 UTC, hum02 commented
그.. 보니까 저도 모르게 이상한 커밋 push해놨더라고요 이거 되돌리려했는데 잘 안되서 이상한 commit하나 껴있습니다. 죄송합니다ㅠ

2023-09-20 01:39 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/service/CafeService.java
> +        if (StringUtils.isBlank(menuKeyWord)) {
저는 함수형 인터페이스가 필요 없다고 생각해요!

```java
public List<CafeSearchResponse> getCafesBySearch(final CafeSearchRequest searchRequest) {
        final List<Cafe> cafes = mapSearchMethod(searchRequest);

        return cafes.stream()
                .map(CafeSearchResponse::from)
                .toList();
    }

    private List<Cafe> mapSearchMethod(final CafeSearchRequest cafeSearchRequest) {
        if (isBlank(cafeSearchRequest.menu())) {
            return cafeRepository.findAllBy(cafeSearchRequest.cafeName(), cafeSearchRequest.address());
        }
        
        return cafeRepository.findAllBy(cafeSearchRequest.cafeName(), cafeSearchRequest.menu(), cafeSearchRequest.address());
    }
```
이렇게 쓰면 되지 않나요...?

2023-09-20 12:25 UTC, donghae-kim approved these changes

2023-09-25 04:50 UTC, hum02 commented
full text search를 적용할 때 functionContributor가 낯설텐데요
참고자료 남길게요
hibernate6부터 사용자 설정 dialect를 위한 설정이 변했더라고요
https://discourse.hibernate.org/t/migration-of-dialect-to-hibernate-6/6956

2023-09-25 05:20 UTC, nuyh99 approved these changes
고생하셨습니다!!
Hibernate에 의존적인 코드가 추가로 생긴 것 같아요.
필요한 부분인지 궁금하고, 여러 선택지들 중 이것을 선택한 이유가 궁금해요!

2023-09-25 05:20 UTC, nuyh99 commented on server/src/main/resources/META-INF/services/org.hibernate.boot.model.FunctionContributor
> +com.project.yozmcafe.domain.cafe.CustomFunctionContributor
함수를 등록하려면 이 부분이 필요한 건가요??
어떤 부분인지 궁금해요

2023-09-25 10:06 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CustomFunctionContributor.java
> +
저도 가능하면 특화구문을 최소한의 의존성으로 사용하고 싶어요!
`    private BooleanExpression contains(final StringPath target, final String searchWord) {
        if (isBlank(searchWord)) {
            return null;
        }

        return booleanTemplate("match({0}) against ({1} in boolean mode) > 0", target, searchWord);
    }`
    이런 식으로 matxh against문을 바로 쓰는 것을 생각하신 게 맞나요?
이렇게 사용할 시  hql이 이런 특화 구문을 지원해주지 않아 hibernate에서 parsing할 때 exception이 발생합니다 ㅜ.
<img width="1222" alt="image" src="https://github.com/woowacourse-teams/2023-yozm-cafe/assets/96762301/2fc16f1e-69c1-44a4-8b96-d5f0184d7d3a">

이외에 함수 등록을 하지 않고 querydsl과 공존하여 사용하는 방법이 마땅히 없어보입니다...

2023-09-25 10:24 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeCustomRepositoryImpl.java
> +        final String literalSearchWord = MATCH_LITERALLY_OPERATOR + searchWord + MATCH_LITERALLY_OPERATOR;
습 저는 상수화를 통해 가독성을 개선했다 생각했는데 오히려 이해를 어렵게 했군요..
MATCH_LITERALLY_OPERATOR 는 상수화 하지 않고
literalSearchWord 라는 변수명은 formattedSearchWord로 수정하려합니다!

2023-09-25 10:29 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeCustomRepositoryImpl.java
> +    private static final String MATCH_LITERALLY_OPERATOR = "\"";
boolean모드에서  "  operator를 통해 literal하게 문자열 그대로 포함하는 것을 검색하는 것
에 대해 의미를 드러내고자 했는데 쉽지 않네요....
상수화를 하지 않겠습니다.

그렇다고 functionContributor쪽에서 " 를 끼워 넣는것은 operator가 추가되었다는 인지를 힘들게 할 것 같아 하고싶지 않네요

2023-09-26 04:06 UTC, hum02 commented on server/src/main/resources/META-INF/services/org.hibernate.boot.model.FunctionContributor
> +com.project.yozmcafe.domain.cafe.CustomFunctionContributor
<img width="680" alt="image" src="https://github.com/woowacourse-teams/2023-yozm-cafe/assets/96762301/c8321771-e650-400e-9459-3c4ca230b889">

여기서 fuctionContirbutor를 사용하려면 sericeLoader에서 스캔하도록 META-INF경로에 파일을 만들거나
코드를 통해 등록하려면 applyFunctions등을 이용하라 안내하는데요
<img width="1060" alt="image" src="https://github.com/woowacourse-teams/2023-yozm-cafe/assets/96762301/7279f484-a1c1-447e-994f-d66003af3466">
이 방식으로 해보니 여전히 직접 설정을 집어넣어야 하는 게 존재해서 이러느니 META-INF에 파일을 만드는 지금 방식이 더 낫다고 생각합니다

2023-09-26 04:36 UTC, green-kong approved these changes
사실 어제는 도저히 내용이 이해가 되질 않았었습니다.
그런데 오늘 연어의 코멘트 내용과, 도치 블로그 포스팅 내용을 보고 난 이후 다시보니 개괄적인 부분이 이해가 되네요!

새로운 기술을 접목하시느라 너무 수고 많으셨어요! 감사합니다!

2023-09-26 06:04 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CustomFunctionContributor.java
> +
query dsl은 말 그대로 DSL로 편하게 동적 쿼리를 작성하기 위함이고 native query를 사용하는 것은 피할 수 없다고 생각해요.
필요하면 JDBC Template을 쓰거나, Entity Manager로 날리거나 하는 것이 당연하다고 생각합니다!

근데 만약 여기서 Entity Manager를 사용하면 좀 더 추상객체(Entity Manager)의 의존만으로 처리할 수 있지 않나 해서 남겼어요!
어떤 장점 때문에 했는지 궁금해서요.

native query가 필요할 때마다 native query가 아닌 Query DSL로 하실 것인가요??

2023-09-26 06:07 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CustomFunctionContributor.java
> +
아 Entity Manager로 변경하라는 뜻은 아닙니다!
지금 그대로도 좋아요!! 단순 궁금증입니다.

2023-09-26 06:48 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CustomFunctionContributor.java
> +
지금은 querydsl에 where에 native쿼리가 들어가야 처음 querydsl을 쓸 때 의도했던 대로
하나의 쿼리 template으로 동적인 쿼리가 가능하다 생각해요!
Entity Manager를 쓰면 이 결과를 querydsl에 적용하려면 그결과를 booleanExpression으로 바꿔야 하는 데 그게 가능한지 모르겠네요...

2023-09-26 07:52 UTC, merged