442/improve resize performance
woowacourse-teams/2023-yozm-cafe pull request #445
Opened 2023-09-11 03:44 UTC by green-kong

https://github.com/woowacourse-teams/2023-yozm-cafe/pull/437
## #️⃣ 연관된 이슈

> 연관된 이슈 번호를 모두 작성해주세요
>
> ex) #이슈번호, #이슈번호

## 📝 작업 내용

> 이번 PR에서 작업한 내용을 간략히 설명해주세요 (이미지 첨부 가능)

## 💬 리뷰 요구사항

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요

2023-09-11 07:18 UTC, hum02 approved these changes
고생했어요~~

2023-09-11 07:18 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/domain/ImageHandler.java
> +package com.project.yozmcafe.domain;
패키지 위치가 도메인으로 바뀌었네요! 그런데 `@service`어노테이션까지 붙어있어서 이게 도메인이 맞나? 하는 생각이 들어요.
s3Client도 외부(s3)와의 통신을 하고 있기에 service가 아닐까 싶고 이를 사용하는 imageHandler도 service아닐까하는 생각이에요!

2023-09-11 07:18 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/service/MenuService.java
>          Menu menu = menuRequest.toMenuWithoutImage(cafe);
여기에도 final?

2023-09-11 07:18 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/domain/ImageHandler.java
> +                .forEach(resizer -> resizer.resizeImageToAllSizes()
저도 이거 공부해봐야겠네요

2023-09-11 08:43 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/domain/ImageHandler.java
> +package com.project.yozmcafe.domain;
저도 도치랑 비슷한 생각입니다!

2023-09-11 08:58 UTC, donghae-kim requested changes
폴로 고생하셨어요 ~

그 ImageService를 ImageHandler로 변경 후 필요한 서비스(CafeAdminService, MenuService) 내부에서 필드로 갖게끔 리팩토링 했습니다. ImageService와 CafeAdminService가 논리적으로 결합이 되어있다고 느껴저서 이 부분은 이벤트로 결합을 풀어보려 했는데,ImageService가 이게 Service 레이어가 맞는가에 대한 의문이 들더라구요.
```
현재 도메인으로써 위치하고 있는데 지금보다는 외부 s3와 연관도 있고 레이어 자체는 Service레이어가 좀더 적절한 것 같기도 해요 .. 차라리 서비스레이어가 서비스를 의존하는 형태도 괜찮을 수 있을 것 같아요
```

제가 이벤트에 대해서는 잘 모르지만 특정 save, update 시 카페어드민이랑 메뉴에서  imageHandler를 호출하여 실행을 하더라고요! 
이를 이벤트화 해서 처리를 하는 것은 어떤가요 ?-?

2023-09-11 08:58 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/domain/ImageHandler.java
> +        resizers.parallelStream()
동기화도 고려할 필요 없고, 순서도 고려할 필요 없어서 병렬스트림을 사용한 것일까요 ? 병렬적으로 진행하면서 중복을 조회하는 경우도 있을 것 같은데 성능적으로 더 나아진건지 궁금합니다!

2023-09-11 15:19 UTC, nuyh99 approved these changes
고생하셨습니다!!
전체 처리 시간은 지금의 parallel 방식으로 많이 향상될 것 같습니다!

두 가지 의문이 있어요.
첫 번째는 기존에 서비스를 분리해서 컨트롤러단에서 저렇게 했던 이유가 이미지 관련을 트랜잭션에서 빼기 위함이였는데 다시 결합이 된 것 같아요!

결국 DB와의 세션이 이미지를 리사이즈하고 업로드하는 동안 유지됩니다! [예시](https://dkswnkk.tistory.com/704)

두 번째는 Parallel Stream의 경우 `ForkJoinPool`을 사용하는데 이때 디폴트 스레드의 수는 (서버의 코어 수 - 1)로 알고 있습니다. [Baeldung](https://www.baeldung.com/java-when-to-use-parallel-stream) 3.2절을 봐주세요!

저희 서버는 듀얼 코어로 알고 있는데 괜찮을까요??
스레드풀을 커스텀해야 할 것 같기도 하구요!

2023-09-11 15:19 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/domain/ImageHandler.java
> +    public List<String> resizeAndUploadToAllSizes(final List<MultipartFile> files) {
`resizeToAllSizesAndUpload`는 어떨까요?!

2023-09-11 15:19 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/domain/ImageHandler.java
> +        resizers.parallelStream()
중복을 조회하는 경우는 어떤 경우인가요???

2023-09-11 15:19 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/domain/ImageHandler.java
> +    public String resizeAndUploadToFixedSize(final MultipartFile image, final Size size) {
이거는 `Size` 단일 인자를 받기 때문에 저 사이즈로 리사이징하구나 하고 알기 쉽다고 생각합니다!

만약 FixedSize를 알리고 싶으면 `resizeToFixedSizeAndUpload`가 어떨까요...?!

2023-09-11 15:21 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/domain/ImageHandler.java
> +package com.project.yozmcafe.domain;
아 이 부분은 못 봤었네요.
저도 외부와의 통신은 서비스 컴포넌트라고 생각합니다!

2023-09-12 00:47 UTC, green-kong commented
이벤트로... 다시 한번 분리 해볼게요 ㅋㅋ
하면서 찜찜한 부분이 있었는데 감사합니다~

아 그리고 연어의  질문이었던,
>두 번째는 Parallel Stream의 경우 ForkJoinPool을 사용하는데 이때 디폴트 스레드의 수는 (서버의 코어 수 - 1)로 알고 있습니다. [Baeldung](https://www.baeldung.com/java-when-to-use-parallel-stream) 3.2절을 봐주세요!

이거 관련해서는 저도 고민이 많았습니다.
현재 ec2가 코어가 2개따리라 default로 스레드하나 생성돼서 그걸로만 되는게 아닐까 고민을 했었는데요.
몇가지 테스트 통해서 알아본 바는 다음과 같아요.

```java
@Test  
void parallel() {  
    System.out.println("호출 쓰레드 : " + Thread.currentThread().getName());  
    IntStream.range(0, 10)
		    .parallel  
            .forEach(num -> System.out.println("스트림 쓰레드 : " + Thread.currentThread().getName() + " , Num : " + num));  
}
```

<img width="691" alt="image" src="https://github.com/woowacourse-teams/2023-yozm-cafe/assets/96301958/8cfa199a-667e-4809-9286-867d62f56d91">

현재 환경은 맥북 M1 air(코어 8따리) 라서 스레드풀 사이즈가 7개로 생성이 됐습니다.
캡쳐된 이미지 보시면, 스레드 넘버링이 7까지 되어있습니다.

그런데 중간에 보면 호출스레드인 main이 병렬작업에 참여한것을 확인 할 수가 있는데요.
parallelStream을 사용하면 호출 스레드 또한 포크조인작업에 참여한다고 하네요.
연어가 걸어준 Baeldung 링크 2.2 내용을 보면, 이와 비슷한 내용이 있습니당.

> ForkJoinPool customThreadPool = new ForkJoinPool(2);
이런식으로 포크조인 풀사이즈를 직접 지정하여 사용하면, 호출스레드는 병렬작업에 참여하지 않습니다.
parallelStream을 통해 매니징되는 병렬작업에선 호출 스레드 역시 작업에 참여합니다.

그래서 듀얼코어 환경에서도, 호출 스레드를 포함하여 2개의 스레드로 동작하지 않을까 예상하고 있습니다.

스레드풀을 커스텀한다고 해도 풀 사이즈를 3이상으론 지정을 못해서
(코어 수 보다 스레드를 많이 생성해버리면, 컨텍스트 스위칭 때문에 오히려 성능이 저하될 듯)
따로 커스텀은 안해줬습니다.

근데 듀얼따리로 성능이 얼마나 향상될지는... 글쎄요.. dev 서버에서 돌려봐야 알 것 같아요ㅋㅋㅋ
그러라고 있는 dev서버 맞죠..?

2023-09-13 03:02 UTC, green-kong commented
ImageService를 비동기 이벤트로 처리하려 하였지만, 몇몇이유로 이벤트로 처리하려 하였지만 병렬스트림만 이용하여 리사이즈 속도만 개선하기로하였습니다. 새로 올릴 PR에 자세히 기술하겠습니다.

2023-09-13 03:02 UTC, closed without merging