공통으로 사용할 수 있는 버튼 컴포넌트와 로그인 페이지 UI 생성
woowacourse-teams/2023-yozm-cafe pull request #45
Opened 2023-07-16 05:51 UTC by jeongwusi

## #️⃣ 연관된 이슈

> 연관된 이슈 번호를 모두 작성해주세요

close #44 

## 📝 작업 내용

- [yellow 색상 추가, 색상 위치 재조정](https://github.com/woowacourse-teams/2023-yozm-cafe/commit/02e5ad70a7399e35c78de14b08364937c29c1228)
- [NavBar 컴포넌트 위치 수정](https://github.com/woowacourse-teams/2023-yozm-cafe/commit/f95cfcb737f56f86ea27870133c425abae660b99)
- [프로젝트에 주아체 추가](https://github.com/woowacourse-teams/2023-yozm-cafe/commit/d31682f89c7249adbca8bd7de8cd885f61aec0f5)
- [카카오와 구글 로고 svg 파일 추가](https://github.com/woowacourse-teams/2023-yozm-cafe/commit/3adabf82d5a47f08d82429ef6fa545ce4cd4e054)
- [공통으로 사용할 수 있는 Logo 컴포넌트 생성](https://github.com/woowacourse-teams/2023-yozm-cafe/commit/dfd9a031a55b388f41d59207d245d6492ccb6561)
- [공통으로 사용할 수 있는 Button 컴포넌트 생성](https://github.com/woowacourse-teams/2023-yozm-cafe/commit/d09e7260af45a56ee8dcfcf26cfc343dba3c7554)
- [중복된 NavBar 컴포넌트 삭제](https://github.com/woowacourse-teams/2023-yozm-cafe/commit/65dc2d92516fcdcebdaadb87cffd8d4ee4187a5f)
- [Login 페이지 UI 생성](https://github.com/woowacourse-teams/2023-yozm-cafe/commit/dd96ec4bf6805431829a2bd9e73be5c3dcf0efe9)

## 💬 리뷰 요구사항

우선 로그인 페이지와 관련된 컴포넌트와 페이지 만들었습니다!

2023-07-16 07:42 UTC, solo5star requested changes

2023-07-16 07:42 UTC, solo5star commented on client/src/components/Button.tsx
> +const StyledButton = styled.button<ButtonProps>`
$ prefix를 쓰는 Transient Props로 바꿔보는 것은 어떨까요?

2023-07-16 07:42 UTC, solo5star commented on client/src/pages/Root.tsx
> +  width: 491px;
`491px` 은 어떻게 계산된 값인가용?

2023-07-16 07:42 UTC, solo5star commented on client/src/components/Button.tsx
> +  height: string;
`width`, `height`를 직접 props로 지정하는 것보단 사이즈를 `small`, `large` 같은 선택지로 제공해주는 건 어떨까요?

2023-07-16 07:42 UTC, solo5star commented on client/src/components/Button.tsx
> +  fontWeight: string;
`border`, `fontWeight` CSS 속성을 직접 지정하면 사용하는 측에서 선택지가 너무 많을 것 같아요 🥲 선택지를 주거나 없애는 것도 좋을 것 같아요

2023-07-16 07:42 UTC, solo5star commented on client/src/components/Button.tsx
> +export default React.memo(Button);
`React.memo` 를 적용한 이유가 무엇일까요?

2023-07-16 11:25 UTC, jeongwusi commented on client/src/components/Button.tsx
> +export default React.memo(Button);
Button 컴포넌트의 부모 컴포넌트에서 props가 변경되지 않았다면, Button 컴포넌트는 이전 렌더링 결과를 재사용하여 불필요한 렌더링을 하지 않기 때문에 memo를 사용하였습니다. 그리고 이거 제가 파랑한테 관련된 리뷰를 받기도 해서요! 솔로스타 생각은 어떠신가요?

2023-07-16 11:26 UTC, jeongwusi commented on client/src/components/Button.tsx
> +  fontWeight: string;
흠... 알겠습니당

2023-07-16 11:28 UTC, jeongwusi commented on client/src/pages/Root.tsx
> +  width: 491px;
그 현재 저희 칸이 491px이기는 해요 100%로 하니까 별로 안 이쁘더라구여 우선 임의로 놓고 페이지 전체적으로 다시 볼 때 조절 해야 될 거 같기는 해요!

2023-07-16 11:28 UTC, jeongwusi commented on client/src/components/Button.tsx
> +  height: string;
음 그러면 theme에서 설정하자는 말씀이신가요?

2023-07-16 11:29 UTC, jeongwusi commented on client/src/components/Button.tsx
> +  color: keyof typeof theme.color;
오홍 Theme 타입이 있었군여! ㅋㅋ

2023-07-16 11:30 UTC, jeongwusi commented on client/src/components/Button.tsx
> +const StyledButton = styled.button<ButtonProps>`
$보다는 Container가 더 좋은 거 같네요 ^^;

2023-07-16 11:30 UTC, jeongwusi commented on client/src/components/Button.tsx
> +export default React.memo(Button);
얍얍

2023-07-16 11:31 UTC, jeongwusi commented on client/src/components/Button.tsx
> +const StyledButton = styled.button<ButtonProps>`
Container 느낌보다는 스타일링만 한다고 생각해서 Styled로 했는데 Container로 고쳐야 겠네여

2023-07-16 12:16 UTC, solo5star commented on client/src/components/Button.tsx
> +const StyledButton = styled.button<ButtonProps>`
앗 그런뜻이 아니고 지금 `styled.button<ButtonProps>` 로 되어있는데 `ButtonProps` 에 정의된 props가 모두 DOM에 그대로 passing될 거에요. 그래서 아래처럼 만들면 DOM에 passing되지 않을 겁니다.

```ts
type StyledButtonProps = {
  $width: string;
  $height: string;
  /* ... */
}
```

2023-07-16 12:16 UTC, solo5star commented on client/src/pages/Root.tsx
> +  width: 491px;
아하 굳!! 좋아요

2023-07-16 12:17 UTC, solo5star commented on client/src/pages/Root.tsx
> +  width: 491px;
향후 상수 혹은 디자인 시스템에 정의해 두는 것도 좋을 듯 하네용

2023-07-16 12:18 UTC, solo5star commented on client/src/components/Button.tsx
> +  height: string;
```ts
type ButtonProps = {
  variant: 'small' | 'large';
}
```
와 같은 식으로 props를 받고, `variant`에 따라 작은 버튼 큰 버튼 만들면 좋지 않을까 싶어요. [mui](https://mui.com/material-ui/react-button/#sizes)도 이러한 식으로 되어있는데 컴포넌트를 쓸 때 편리할 것 같아요~

2023-07-16 12:20 UTC, solo5star commented on client/src/components/Button.tsx
> +export default React.memo(Button);
이건 논쟁이 많긴 한데...ㅋㅋ 제 의견은 작은 컴포넌트에 굳이 필요하다는 생각은 들지 않네요. `Button`만큼 작은 컴포넌트에도 사용할 거라면 모든 컴포넌트에 `React.memo`를 적용해야 하지 않을까 싶습니다.

개인적으론 렌더링이 충분히 무겁다고 여겨지는 컴포넌트에서 쓰면 좋지 않을까 싶습니다.

2023-07-16 22:59 UTC, jeongwusi commented on client/src/components/Button.tsx
> +export default React.memo(Button);
흠 버튼이 렌더링이 무겁지는 않죠 ㅋㅋㅋ 알겠습니당

2023-07-16 23:38 UTC, jeongwusi commented on client/src/components/Button.tsx
> +const StyledButton = styled.button<ButtonProps>`
오홍~ 좋습니닷

2023-07-17 07:52 UTC, geuntaek1013 approved these changes
고생하셨습니다!!ㅎㅎ

2023-07-17 07:52 UTC, geuntaek1013 commented on client/src/pages/Login.tsx
> +const LogoContainer = styled.div``;
LogoContainer는 쓰이지 않는 것 같은데, 혹시 무슨 용도로 존재하나요?🤔

2023-07-17 07:54 UTC, jeongwusi commented on client/src/pages/Login.tsx
> +const LogoContainer = styled.div``;
```ts
      <LogoContainer>
        <Logo fontSize="7xl" />
      </LogoContainer>
```

이런 형식으로 div로 사용되고 있습니다^^

2023-07-17 07:57 UTC, solo5star approved these changes

2023-07-17 07:58 UTC, merged