지도 기능
woowacourse-teams/2023-yozm-cafe pull request #455
Opened 2023-09-16 10:26 UTC by green-kong

## #️⃣ 연관된 이슈

> resolved #451 

## 📝 작업 내용

기존의 카페에 좌표를 추가하는 api를 뚫었습니다.
음 근데, insert문을 다 만들어 버려서, 쓸일이 없을 것 같긴하네요.. 하핳

위에거가 중요한게 아니라,
지도 범위 내에 포함되어있는 카페의 정보들을 반환하는 기능을 만들었습니다.

쿼리 스트링으로 latitude, longitude, latitudeDelta, longitudeDelta 를 받습니다
lat, lng 는 기준 좌표구요.
latDelta, lngDelta는 각각 지도 내 최대 lat(lng) - 기준 lat(lng) 입니다.

델타값들을 미터 단위로 환산하고, 더 작은값을 구합니다(radius)
기준 좌표로부터 radius만큼 원을 만들고(ST_Buffer), 그 안에 포함되어있는 카페들을 반환합니다(ST_Contains)

cafe_coordinates table의 coordinate 쪽에 공간인덱스 걸어뒀구요.
인덱스 걸고 안걸고 속도 차이는 10배정도 나는 듯 하네요.

![image](https://github.com/woowacourse-teams/2023-yozm-cafe/assets/96301958/9e88caf6-e36f-4046-96f5-d31752d1cee4)
👆 인덱스 X

👇 인덱스 O
![image](https://github.com/woowacourse-teams/2023-yozm-cafe/assets/96301958/9bd5dc89-1932-4e1a-b3cd-2f5de52f8885)

자세한 내용은 주말 중에 포스팅 하도록 할게요. 

아 그리고 그 뭐야.
Production에 넣을 좌표값들은 다 만들어 두었습니다.

## 💬 리뷰 요구사항

2023-09-18 09:12 UTC, nuyh99 requested changes
고생하셨습니다 폴로!!
저도 간접적으로 공간 인덱스에 대해서 약간 맛볼 수 있었네요ㅋㅋㅋㅋ

코멘트로 제 생각들 간단히 남겨봤습니다. 저는 기존의 카페 엔티티에 추가하는 방식으로 할 것 같은데 따로 분리한 이유가 제일 궁금하네요!

아 그리고 Point 정보를 엔티티로 분리했다면, 추가적으로 어드민 서비스의 제거 메서드에서도 해당 테이블에서 제거하는 기능을 추가해야 할 것 같아요!

2023-09-18 09:12 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/coordinate/dto/CafePinDto.java
> +public interface CafePinDto {
Projection으로 매핑을 해주는 것이군요!

2023-09-18 15:04 UTC, hum02 approved these changes
고생했어요 폴로! 
공간 인덱스 생각할 것도 많고 기술적으로도 어려운 기능이네요...
잘 구현해주셨다고 느낍니다

2023-09-19 04:53 UTC, donghae-kim approved these changes
고생하셨어요 폴로~

다만 Calculator쪽이 조~금 설명이 더 있으면 좋을 것 같아요 !

2023-09-19 04:53 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/domain/cafe/coordinate/RadiusCalculator.java
> +        double metersLongitude = Math.cos(radianLatitude) * longitudeDelta * METER_PER_DEGREE;
두 지점의 위도 차이와 경도 차이(longitudeDifference)를 계산 -> 위도 차이를 미터 단위로 변환하기 위해 latitudeDifference에 대해 METER_PER_DEGREE 곱함 -> 경도 차이를 미터 단위로 변환하기 위해 longitudeDifference에 대해  * cos(평균 위도)를 곱한다.

어렵네요

2023-09-19 04:53 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/controller/LocationController.java
> +        final List<CafeLocationResponse> cafesFromLocations = locationService.findCafesFromLocations(
dto 환영

2023-09-20 10:51 UTC, green-kong commented on server/src/main/resources/application.properties
> +spring.jpa.database-platform=org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
`spring.jpa.database-platform`이 옵션 자체가 없어도 잘 동작하네요! 해당 옵션은 제거 하도록 하겠습니다!

2023-09-20 10:51 UTC, green-kong commented on server/src/main/resources/db/migration/V20230914151731__add_point_column.sql
> +CREATE TABLE cafe_coordinates
통일성을 위해서 그게 더 좋을듯 하네요!

2023-09-20 10:51 UTC, green-kong commented on server/build.gradle
> +    implementation group: 'org.hibernate', name: 'hibernate-spatial', version: '6.2.5.Final'
역시 세심하네요 연어!

2023-09-20 10:52 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/domain/cafe/Images.java
> +    @ElementCollection(fetch = FetchType.LAZY)
감사합니다!

2023-09-20 11:02 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/domain/cafe/PointGenerator.java
> +    private static final int SRID = 4326;
SRID 에 대한 정보를 말씀 하시는거겠죠?
저도 처음 접해봤고, 보편적으로 생소한 내용이 아니다 보니 이 정도는 주석을 달아두는 것도 나쁘지 않겠네요!

2023-09-20 11:02 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/domain/cafe/coordinate/CafeCoordinateRepository.java
> +    List<CafePinDto> findCafePinsFromCoordinate(@Param("point") final String point,
저두...

2023-09-20 11:03 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/domain/cafe/coordinate/CafeCoordinate.java
> +    @OneToOne(fetch = FetchType.LAZY)
저는 `@OneToOne`처음 써봐서, 이번에 지도기능 구현하면서 구글링 하다가 연어가 얘기한 내용을 접했는데요.
조금 더 덧붙이자면, 양방향 관계일때, 연관관계의 주인이 아닌 경우 LAZY가 안먹는 다고 하네요!

2023-09-20 11:06 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/controller/LocationController.java
> +        final List<CafeLocationResponse> cafesFromLocations = locationService.findCafesFromLocations(
반영하겠습니다!

2023-09-20 11:19 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/domain/cafe/coordinate/CafeCoordinate.java
> +public class CafeCoordinate {
아 이 부분.. 저도 많이 고민했었는데요.

연어의 말대로  비즈니스적으로 분리가 된다고 생각했습니다.
현재의 비즈니스에서는 단순히 지도검색용으로 사용되는 데이터기에 카페의 메인데이터와는 분리를 하고싶었습니다.

다른 부분은 모르겠지만, 카페의 주소와는 동일한 변경 주기를 갖고있다는 말에는 백프로 동의합니다.
주소가 바뀌면 좌표도 당연히 바뀌게 되니까요.
하지만 가게의 이전이라는게 그렇게 많이 일어나는 일이 아니다보니,(폐업이면 몰라도..)
이 부분 만큼은 비즈니스적으로 데이터를 분리하는 게 낫지 않을까 라는 생각을 했습니다.

만약 이 부분이 다른 비즈니스로직에도 사용되어야 하는 경우에는
Location table로 주소와 좌표를 분리하는게 낫지 않을까.. 라는 생각을 했었습니다

2023-09-20 11:24 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/domain/cafe/coordinate/RadiusCalculator.java
> +        return Math.min(metersLatitude, metersLongitude);
오우.. 제가 설명이 부족했나 봅니다 ㅠㅠ 
연어의 말대로 (지도 내의 최대 위도 - 지도 중심의 위도) 와 (지도내의 최대 경도 - 지도 중심의 경도)를 각각 미터로 환산합니다.
그 중 작은값을 반지름으로 갖는 원을 만들어 원 내에 있는 카페의 정보만 반환하도록 하였습니다.
<img width="397" alt="image" src="https://github.com/woowacourse-teams/2023-yozm-cafe/assets/96301958/025e771f-f014-4232-97fa-c61325e236ba">
이 그림을 보시면 조금이나마 더 이해에 도움이 되실까요?

2023-09-20 11:27 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/domain/cafe/coordinate/CafeCoordinateRepository.java
> +    List<CafePinDto> findCafePinsFromCoordinate(@Param("point") final String point,
음 우선 필요한 값만 가져 올 수 있다는게 가장 큰 장점이었어요!
또한 hinernate가 관계 매핑을 고려하지 않아도 돼서 처리속도도 빠르구요.

최근에 봤던 포스팅 중에 리포지토리에서 반환하는 값을 모두 dto로 변경했더니 서비스 속도가 빨라졌다는 글을 본적이 있습니다.
정말 단순 조회작업(조회 이후 조회된 값을 바로 응답) 하는 경우라면 이런식으로 dto를 리턴하는 것도 좋을것 같다는 생각이에요!

2023-09-20 11:35 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/controller/LocationController.java
> +            @RequestParam("longitudeDelta") final double longitudeDelta) {
대면으로 답변 드렸기에 따로 코멘트 남기지 않을게요~

2023-09-20 11:35 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/controller/dto/cafe/CafeLocationResponse.java
> +                cafePinDto.getName(),
사랑해요 도치

2023-09-20 11:38 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/domain/cafe/coordinate/RadiusCalculator.java
> +    private static final int METER_PER_DEGREE = 111_000;
1도 당 거리가 약 111KM 라고 합니다! 저도 처음 알았어요 ㅋㅋ

2023-09-20 11:44 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/domain/cafe/coordinate/RadiusCalculator.java
> +        double metersLongitude = Math.cos(radianLatitude) * longitudeDelta * METER_PER_DEGREE;
위도는 1도 당 거리가 111KM로 동일합니다.

그러나 경도의 경우는
영국의 그리니치 천문대를 중심으로 동경180도 서경 180도 이렇게 표현하니까 결국 360등분하여
하나의 조각을 1도로 사용하죠.

그런데, 한 조각의 거리는 가장 중앙 부분(지구에서 적도해당 )에서 가장 넓고 아래, 위로 갈수록 좁아 지는데요
즉, 같은 경도 사이의 거리는 위도가 커짐(0~90도)에 따라서 점점  좁아지죠.
그렇기 때문에 중심 경도로부터 지도내 최대경도까지의 거리를 계산하기위해서는 위도의 각도에 코사인을 곱하는 계산이 들어가야 한다고 하네요.

사실 저도 이해못했습니다. 그렇다길래 아하 그렇구나 하고 했습니다...

2023-09-20 11:46 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/domain/cafe/coordinate/RadiusCalculator.java
> +        return Math.min(metersLatitude, metersLongitude);
그림에서 가장 오른쪽이 최대 위도,
가장 위쪽이 최대 경도 입니다.
회색선이 겹치는 지점이 지도의 중앙이구요.

혹시나 설명이 부족하다면 말씀해주세요

2023-09-20 13:06 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/service/LocationService.java
> +        final double radius = RadiusCalculator.calculate(latitude, latitudeDelta, longitudeDelta);
> PointGenerator나 RadiusCalculator가 도메인이라기 보다는 util클래스 같은 느낌이 들었어요
그래서 보니 CafeCoordinate 도메인에서 이 작업을 해줄 수 있지 않을까요?

```java
private static final GeometryFactory GEOMETRY_FACTORY = new GeometryFactory();
```

Point를 생성할 때 저 GeometryFactory가 사용되는데요.
매번 인스턴스를 생성하기가 싫어서 PointFactory에 static으로 넣어놨습니다.

또한 여기서 받는 위도와 경도는 카페의 위도와 경도가 아닌 지도 중심점의 위도와 경도입니다.
그렇기 때문에 저 위도와 경도를 이용해서 CafeCoordinate를 만드는 것 자체가, 저 도메인 객체의 역할에 부합하지 않다고 생각해요.
그래서 그저 좌표의 정보만 있는 Point를 사용했습니다.
radius를 계산하는 로직 또한 카페의 좌표와는 맥락이 일치하지 않는다고 생각해요.

전반적으로 제 설명이 부족했던 것 같아요 ㅠ 죄송합니다 ㅠㅠㅠ

> generateStringPoint()메서드의 작업도 Point가 상속받은 Geometry의 toText()로 해줄 수 있는 것 같더라고요!

감사합니다 감사합니다 감사합니다. PointGenerator에서 포인트를 파싱하는 내용은 삭제해도 되겠네요!

2023-09-21 13:13 UTC, green-kong commented
리뷰 내용 모두 반영하였습니다.

**서비스 로직 변경 사항**

기존에는 기준점과 델타값들을 통해 원을 그리고 원 내부에 포함되는 카페들만 반환했었는데요.
<img width="355" alt="image" src="https://github.com/woowacourse-teams/2023-yozm-cafe/assets/96301958/93e8724f-c527-4737-b632-637082e8983e">

이렇게 되면, 반환되는 카페데이터가 화면에 표시된 지도를 모두 커버하지 못합니다.
사용자는 아무래도 지도 전체에 대한 결과를 바랄 것 같아 로직을 변경하게되었습니다.

기준점과 델타값을 이용하는 것은 동일합니다.
다만 이값들을 통해 화면에 보이는 지도의 네 꼭지점들의 좌표를 구합니다.
그리고 이 값들을 통해 `POLYGON WKT` 를 생성합니다.

첫번째 꼭지점이 마지막에 다시한번 들어가야 폴리곤이 정상적으로 생성됩니다.

POLYGON_STRING_FORMAT 에 보면 소괄호`(, )` 가 두개씩 들어가는데요.
이는 오타가 아니라 이게 문법입니다;;
POLYGON WKT는 두개의 인자를 받는데요. 첫번째는 외부의 폴리곤 좌표들, 두번째는 내부의 폴리곤 좌표들입니다.
🍩중앙에 구멍이 뚫린 도넛 형태를 생각하시면 이해가 되실겁니다.

2023-09-21 13:15 UTC, green-kong commented
아 로직 변경하면서 쿼리도 조금 변경됐는데요.
실행 계획 확인결과 인덱스는 잘탑니다~

<img width="1121" alt="image" src="https://github.com/woowacourse-teams/2023-yozm-cafe/assets/96301958/f384a15b-2f89-47a2-901d-32218a8b7d09">

2023-09-22 07:26 UTC, hum02 approved these changes
좋아요~~

2023-09-22 07:26 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/GeometryGenerator.java
> +        final String fourthVertex = String.join(STRING_GEOMETRY_DELIMITER, minLatitude, minLongitude);
원 대신 새로 생긴 사각형 좌표들이군요! 좋아용

2023-09-22 07:26 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/coordinate/RadiusCalculator.java
> +public class RadiusCalculator {
정책이 원이 아닌 사각형 내 카페탐색으로 바뀌어서 이 RadiusCalculator클래스와 관련 테스트는 삭제되어도 될 것 같아요! 남겨둔 이유가 있나요?

2023-09-22 07:26 UTC, hum02 commented on server/src/main/resources/application.properties
> -spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
꼼꼼하시군요! 감사합니다

2023-09-22 07:29 UTC, donghae-kim approved these changes
고생하셨어요 폴로!

2023-09-22 07:29 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/domain/cafe/coordinate/CafeCoordinateRepository.java
> +    List<CafePinDto> findCafePinsFromCoordinate(@Param("area") final String area);
string으로 범위를 주면 그거에 맞춰서 조회 하나보네요 ㄷㄷ 신기방기

2023-09-22 07:29 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/domain/cafe/Images.java
> +    @ElementCollection
👍

2023-09-22 07:29 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/domain/cafe/coordinate/dto/CafePinDto.java
> +public interface CafePinDto {
신기하네요 ...

2023-09-22 08:26 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/domain/cafe/coordinate/RadiusCalculator.java
> +public class RadiusCalculator {
오 지우는거 깜빡했네요! 감사합니다!

2023-09-22 08:34 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/domain/cafe/coordinate/RadiusCalculator.java
> +public class RadiusCalculator {
바로 반영했습니다~ 굿굿

2023-09-22 08:37 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/domain/cafe/coordinate/CafeCoordinateRepository.java
> +    List<CafePinDto> findCafePinsFromCoordinate(@Param("area") final String area);
정확하게는 `Polygon wkt`를 `ST_GeomFromText()` 의 인자로 넘기면 텍스트를 Polygon데이터로 변환해 줍니다.
그리고 변환된 polygon을 ST_cotains의 첫번째 인자로 넘겨줍니다~

2023-09-25 04:22 UTC, nuyh99 approved these changes
원에서 직사각형이 됐군요 고생하셨습니다!
간단한 코멘트만 남겼습니다!!

2023-09-25 04:22 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/coordinate/CafeCoordinate.java
> +@Entity(name = "cafe_coordinate")
name 옵션 없애도 될 것 같습니다!

2023-09-25 04:22 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/coordinate/CafeCoordinate.java
> +    public CafeCoordinate() {
접근제어자 protected로 바꿔도 좋을 것 같아용

2023-09-25 04:22 UTC, nuyh99 commented on server/build.gradle
> +    implementation group: 'org.hibernate', name: 'hibernate-spatial', version: '6.2.5.Final'
```groovy
    implementation 'org.hibernate:hibernate-spatial:6.2.5.Final'
```
다른 것들과 마찬가지로 이 문법을 사용하면 좋을 것 같아요!

2023-09-25 06:03 UTC, merged