카페 이미지 Fetch Join 시 Inner Join 하도록 변경
woowacourse-teams/2023-yozm-cafe pull request #468
Opened 2023-09-20 14:24 UTC by nuyh99

## #️⃣ 연관된 이슈
- #467 

## 📝 작업 내용
- 테스트 환경 설정에서 빠진 batch size 추가(팀시티에도 없더라구요...)
- `CafeRankGenerator` 제거(`Pageable`의 `offset` 사용)
- cafe.images.url 조인할 때 outer join -> inner join으로 변경 (패치 조인 가능)
  - 이미지 최소 1개 이상 포함하도록 검증 로직 추가

2023-09-20 14:35 UTC, nuyh99 commented
[이 부분](https://github.com/woowacourse-teams/2023-yozm-cafe/pull/468/files?file-filters%5B%5D=.java&file-filters%5B%5D=.properties&show-deleted-files=true&show-viewed-files=true)만 보면 될 것 같습니다!

2023-09-20 16:48 UTC, green-kong approved these changes
연어덕에 전반적으로 코드가 많이 좋아졌네요!
감사합니다!

2023-09-20 16:48 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/domain/cafe/Cafe.java
> +import jakarta.persistence.Id;
감사합니다!

2023-09-20 16:48 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/domain/cafe/Cafe.java
>      }
감사합니다2

2023-09-20 16:48 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/domain/member/MemberRepository.java
>      Optional<Member> findById(@Param("id") String id);
흐음. 여기도 inner join 해도 되지 않나요???'
문제가 없는 부분이라 대문자 패치만 하신걸까요??

아 대문자 패치는 감사합니다!3

2023-09-21 07:12 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/domain/member/MemberRepository.java
> +            JOIN FETCH uvc.cafe
헉 이 부분 때문에 테스트가 와장창 깨지는 것 같아요!
테스트에서 member를 찾지 못하고 있네요

2023-09-21 12:10 UTC, donghae-kim requested changes
고생하셨어요 연어~

도치 폴로가 이미 좋은 코멘트를 남겨줬었네요!

현재 테스트 코드가 깨지고있는 fetch join 시 inner join에 대해서 같이 이야기하면서 해결하면 좋을 것 같아요! 일단 inner조인 처리를 하려는 이유가 궁금합니다! 또한 코멘트에 남겼듯이 지금과 같은 방식대로 진행하려면 메소드를 오버로딩 해서 처리해도 될 것 같은데 연어의 의견도 궁금하네용

2023-09-21 12:10 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/domain/member/MemberRepository.java
> +            JOIN FETCH uvc.cafe
이렇게 진행될 경우에 uvc가 없는 멤버는 조회되지 않을 것 같네요 ...

음 . . findbyid 메소드 자체를 오버로딩해서 사용해야 될 수도 있겠는데요 ?!

2023-09-26 06:14 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/domain/member/MemberRepository.java
>      Optional<Member> findById(@Param("id") String id);
`UnViewedCafe`와 `Cafe`는 1:1 not null 관계이기 때문에 inner join이 좋을 것 같아요!

2023-09-26 06:17 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeRepository.java
> +            WHERE c.id = :cafeId
`outer join -> inner join으로 변경해서 패치조인이 가능해졌다 ?` 말이 맞습니다!

2023-09-26 08:24 UTC, donghae-kim approved these changes
고생했어요 연어

2023-09-26 08:25 UTC, merged

2023-09-26 08:27 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/domain/member/MemberRepository.java
> +            JOIN FETCH uvc.cafe
메서드를 따로 분리했습니다