불필요한 이미지 fetch 최소화 및 이미지 fetch 우선순위 조정
woowacourse-teams/2023-yozm-cafe pull request #476
Opened 2023-09-21 11:41 UTC by solo5star

## #️⃣ 연관된 이슈
close #475

## 📝 작업 내용
![image](https://github.com/woowacourse-teams/2023-yozm-cafe/assets/20203944/451b1b27-50ea-41c5-bb00-9dae11d1c7a9)

* 먼저 표시되는 이미지가 먼저 fetch되도록 수정하였습니다.
* 불필요한 이미지가 초기 로드에 fetch되지 않도록 작업하였습니다.
* 커밋 내역 참고 부탁드립니다

## 💬 리뷰 요구사항

2023-09-21 12:29 UTC, jeongwusi requested changes
확인해주세용

2023-09-21 12:29 UTC, jeongwusi commented on client/src/components/CafeCard.tsx
> +    setCurrentImageIndex(index);
이 부분에 대해서 좀 더 설명해주세용

2023-09-21 12:29 UTC, jeongwusi commented on client/src/components/CafeCard.tsx
> +            loading={Math.abs(currentImageIndex - index) <= 1 ? 'eager' : 'lazy'}
속성을 정말 잘 활용하시군요! 👍🏻

2023-09-21 12:29 UTC, jeongwusi commented on client/src/components/ScrollSnapContainer.tsx
> +        indexedItems.at((focusedIndex + 1) % indexedItems.length), // 현재에서 하단 (혹은 첫) 아이템
움직이면 인덱스가 동적으로 바뀌게 하셨군용!

2023-09-21 12:29 UTC, jeongwusi commented on client/src/components/ScrollSnapContainer.tsx
> +        )}
이 부분에 대해서는 부가적인 설명 부탁드립니당

2023-09-21 12:33 UTC, solo5star commented on client/src/components/ScrollSnapContainer.tsx
> +        ))}
가만 생각해보니 이에 대한 설명이 없었네요.. 😓 죄송합니다~.. 본문에 업데이트해두었어요!

2023-09-21 12:34 UTC, solo5star commented on client/src/components/CafeCard.tsx
> -    };
아주 잘 되는 것을 확인하였습니다.

> 처음에는 useEffect를 왜 주셨죠?

![image](https://github.com/woowacourse-teams/2023-yozm-cafe/assets/20203944/843e09a2-bcb4-40e8-bdad-1f40f66c9c53)

음.... 저는 잘 모르겠습니다 🥲

2023-09-21 12:36 UTC, solo5star commented on client/src/components/CafeCard.tsx
> +    setCurrentImageIndex(index);
React 패러다임에서의 부수 효과(Side-Effect) 중 이벤트 핸들링은 `useEffect`를 사용하지 않아도 됩니다. 따라서 `onScroll` props로 전달해주었습니다. 로직 자체는 기존의 것과 똑같습니다!

2023-09-21 12:36 UTC, solo5star commented on client/src/components/CafeCard.tsx
> +            loading={Math.abs(currentImageIndex - index) <= 1 ? 'eager' : 'lazy'}
감사합니다 ☺️

2023-09-21 12:37 UTC, solo5star commented on client/src/components/ScrollSnapContainer.tsx
> +        indexedItems.at((focusedIndex + 1) % indexedItems.length), // 현재에서 하단 (혹은 첫) 아이템
네 맞습니다. `enableRolling` 이 `true` 일 때는 마치 관람차처럼 처음이나 끝이 없이 전체 아이템이 회전하는데, 이를 적용한 것이라 보면 됩니다.

2023-09-21 12:40 UTC, solo5star commented on client/src/components/ScrollSnapContainer.tsx
> +        )}
`enableRolling` 이 아닌 경우 첫 아이템을 기준으로 이전의 아이템을 표시할 필요가 없습니다. 빈 `ScrollSnapVirtualItem` 대신 `null`로 해도 되겠지만, 향후 부작용이 발생할 수 있기 때문에 placeholder로서 두었습니다. (첫 아이템에서 스크롤을 내릴 때 보일 화면을 넣을 수도 있겠죠?)

2023-09-21 12:40 UTC, solo5star commented
꼼꼼한 리뷰 고맙습니다 고니~!!

2023-09-26 05:58 UTC, geuntaek1013 requested changes
솔선생님 고생하셨습니다~!!
간단한 리뷰 확인 부탁드립니다.🥹

2023-09-26 05:58 UTC, geuntaek1013 commented on client/src/components/CafeCard.tsx
> -    };
이전에는 `useRef`를 사용하여 DOM 요소의 참조를 가져왔는데 `UIEventHandler`는 타입 안정성을 추가하시기 위해 사용하신 건가요? 아니면 다른 이유가 있으신가요?🤔

2023-09-26 05:58 UTC, geuntaek1013 commented on client/src/components/CafeCard.tsx
> +    setCurrentImageIndex(index);
이벤트 핸들링은 왜 `useEffect`를 사용하지 않아도 되는지 자세히 말씀해주실 수 있으신가요?ㅎㅎ

2023-09-26 05:58 UTC, geuntaek1013 commented on client/src/components/CafeCard.tsx
> +            loading={Math.abs(currentImageIndex - index) <= 1 ? 'eager' : 'lazy'}
굿굿 좋습니다!!

2023-09-26 05:58 UTC, geuntaek1013 commented on client/src/components/ScrollSnapContainer.tsx
> +        indexedItems.at((focusedIndex + 1) % indexedItems.length), // 현재에서 하단 (혹은 첫) 아이템
비유가 너무 찰떡이네요ㅎㅎ

2023-09-26 05:58 UTC, geuntaek1013 commented on client/src/components/ScrollSnapContainer.tsx
> +        )}
왜 나중에 부작용이 발생할 수 있는지 설명 부탁드려도 될까요? `placeholder `로 둔다면 부작용이 없나요?

2023-09-27 01:12 UTC, solo5star commented on client/src/components/CafeCard.tsx
> -    };
이벤트 핸들링 부수 효과(Side-Effect)는 구태여 `useEffect`로 다룰 필요가 없기 때문입니다

2023-09-27 01:13 UTC, solo5star commented on client/src/components/CafeCard.tsx
> +    setCurrentImageIndex(index);
`onScroll` 같은 `on-` props로 핸들러를 건네주면 되기 때문입니다

2023-09-27 01:15 UTC, solo5star commented on client/src/components/ScrollSnapContainer.tsx
> +        )}
날카롭네요! 다시 생각해보니 부작용은 좀 잘못된 표현인 것 같습니다. 비어있는 칸 마저도 커스텀할 수 있는 여지를 준다 정도로 설명할 수 있을 것 같습니다.

2023-09-27 08:33 UTC, geuntaek1013 approved these changes
관련 리뷰 확인했습니다. 고생하셨습니다!!👍

2023-09-29 04:52 UTC, jeongwusi approved these changes
확인하였습니다~!! 굿굿

2023-09-29 05:42 UTC, merged