홈 화면 주요 기능 구현
woowacourse-teams/2023-yozm-cafe pull request #49
Opened 2023-07-17 05:02 UTC by solo5star

## #️⃣ 연관된 이슈
close #3 

## 📝 작업 내용
`/cafes` API에서 카페 목록을 받아와 렌더링을 합니다.

* 스와이프 기능 구현
* `/cafes` API 모킹 수정 (`?page=1` 쿼리 파라미터 지원)
* `useIntersection` 커스텀 훅 구현
* `useCafes` 커스텀 훅 구현
* `AsideActionBar` -> `CafeActionBar`
* 좋아요, 댓글 등의 사용자 액션을 `CafeActionBar` 에서 수행하도록 구현
* `AppHeader` 컴포넌트 삭제
* react-query에서 `suspense`를 기본적으로 사용하도록 설정 변경

## 💬 리뷰 요구사항
코드 변경이 많아 직접 실행해보시고 확인해보시면 좋을 듯 합니다.

2023-07-17 05:09 UTC, jeongwusi requested changes
고생했어요~! 리뷰 확인해주세여 ㅎㅎ

2023-07-17 05:09 UTC, jeongwusi commented on client/src/pages/Home.tsx
> +  const handleCafeChange = useMemo(() => {
여기에 useMemo를 사용하셨는데 특별한 사유가 있으신가여?

2023-07-17 05:09 UTC, jeongwusi commented on client/src/hooks/useIntersection.ts
> +export default useIntersection;
멋져 😆

2023-07-17 05:09 UTC, jeongwusi commented on client/src/hooks/useCafes.ts
> +export default useCafes;
크... 무한스크롤 👍🏻

2023-07-17 05:14 UTC, solo5star commented on client/src/pages/Home.tsx
> +  const handleCafeChange = useMemo(() => {
```tsx
      <CardList>
        {cafes.map((cafe, index) => (
          <CafeCard key={cafe.id} cafe={cafe} onIntersect={handleCafeChange[index]} />
        ))}
      </CardList>
```
1. 아래에 `<CafeList />`에서 `.map`으로 `<CafeCard />` 컴포넌트 리스트를 렌더링합니다.
2. 각 컴포넌트마다 `onIntersect` 콜백 함수를 넣어주어야 합니다.
3. 콜백 함수의 참조 동일성을 지켜주지 않으면 렌더링 무한 루프가 발생하기 때문에
4. `handleCafeChange` 에 `useCallback` 혹은 `useMemo` 를 사용해주어야 합니다.
5. 그런데 핸들러 함수를 여러 개 만들어주어야 하기 때문에 `useCallback` 대신 `useMemo` 를 사용하게 되었습니다.

2023-07-17 05:15 UTC, solo5star commented on client/src/hooks/useCafes.ts
> +export default useCafes;
굿~ 좋습니다

2023-07-17 05:15 UTC, solo5star commented on client/src/pages/Home.tsx
> +  const handleCafeChange = useMemo(() => {
`useMemo`만 보면 무슨 컨텍스트인지 이해가 어려울 수도 있을 것 같네요. 이에 대한 내용은 주석으로 넣도록 하겠습니다.

2023-07-17 05:20 UTC, jeongwusi commented on client/src/pages/Home.tsx
> +  const handleCafeChange = useMemo(() => {
오홍...! 네네 좋습니닷

2023-07-17 05:21 UTC, jeongwusi approved these changes
승인하였습니당

2023-07-18 07:43 UTC, geuntaek1013 approved these changes
아이고 고생하셨습니다ㅜㅜ

2023-07-18 07:43 UTC, geuntaek1013 commented on client/src/data/mockData.ts
> +      availableTimes: [
카페 영업 시간을 API 명세 수정안대로 openingHours로 변경해주시면 감사하겠습니다!!ㅎㅎ

2023-07-18 07:53 UTC, solo5star commented on client/src/components/CafeActionBar.tsx
> +  const handleLikeChange = () => {
좋습니다. 어떤 동작을 하는지 설명이 되는 이름으로 바꾸어 보겠습니다!

2023-07-18 08:24 UTC, merged