검색 기능 구현
woowacourse-teams/2023-yozm-cafe pull request #490
Opened 2023-09-26 05:43 UTC by solo5star

## #️⃣ 연관된 이슈
close #489 

## 📝 작업 내용
![yozm-cafe-search](https://github.com/woowacourse-teams/2023-yozm-cafe/assets/20203944/b14bae5a-f10f-49fa-80f8-15c1ef49c4f4)

> 위 이미지는 모킹된 데이터를 기반으로 동작하고 있습니다

* 검색 기능 구현
* 검색 페이지 구현
* 3가지 필드를 기준으로 검색 가능(카페 이름, 카페 주소, 카페 메뉴 명)
* 네비게이션 바 리뉴얼 및 검색 페이지 이동 버튼 추가

## 💬 리뷰 요구사항
* 검색 API 연동 테스트가 선행되어야 합니다.

2023-09-29 06:15 UTC, jeongwusi requested changes
검색 기능 구현하시느라 고생하셨습니다~! 확인 한번만 해주십셩

2023-09-29 06:15 UTC, jeongwusi commented on client/src/pages/SearchPage.tsx
> +const FormGroup = styled.fieldset`
시맨틱 태그도 야무지게 사용을 하셨군요!

2023-09-29 06:15 UTC, jeongwusi commented on client/src/client.ts
> +    return this.fetchJson<SearchedCafe[]>(`/cafes/search?${new URLSearchParams(sanitizedSearchParams).toString()}`);
근데 메서드 POST인데 `{ method: 'POST' }` 이거 필요 없나용?

2023-09-29 06:15 UTC, jeongwusi commented on client/src/hooks/useSearchCafes.ts
> +    retry: false,
retry는 왜 fasle로 하셨나용?

2023-09-29 07:11 UTC, solo5star commented on client/src/pages/SearchPage.tsx
> +  const query = useDeferredValue(isDetailEnabled ? { searchName, searchAddress, searchMenu } : { searchName });
네 맞습니다~! useDeferredValue를 사용하면 fallback을 보여주는 대신 이전의 렌더를 보여주기 때문에 끊김이 없는 것처럼 보여 사용자 경험에 좋은 영향을 줄 수 있습니다

2023-09-29 07:11 UTC, solo5star commented on client/src/pages/SearchPage.tsx
> +const FormGroup = styled.fieldset`
그럼요~^^

2023-09-29 07:12 UTC, solo5star commented on client/src/client.ts
> +    return this.fetchJson<SearchedCafe[]>(`/cafes/search?${new URLSearchParams(sanitizedSearchParams).toString()}`);
어떤게 POST라는 걸까용? 서버 측에선 GET으로 구현되어 있기 때문에 GET 을 사용하였습니당

2023-09-29 07:14 UTC, solo5star commented on client/src/hooks/useSearchCafes.ts
> +    retry: false,
검색 결과 조회는 타이핑마다 일어나기 때문에 빈번히 요청합니다. 여기서 이전 타이핑의 조회 결과는 필요없기 때문에 굳이 retry로 가져올 필요는 없기 때문입니다~!

2023-09-30 04:38 UTC, jeongwusi approved these changes
나이스 코드~ 고생고생^^

2023-10-05 06:09 UTC, merged