웹앱 대응을 위한 favicons-webpack-plugin 적용
woowacourse-teams/2023-yozm-cafe pull request #495
Opened 2023-09-28 04:03 UTC by solo5star

## #️⃣ 연관된 이슈
close #494 

## 📝 작업 내용
이 작업이 web app을 full support하지는 않지만 앱 아이콘, 스플래시 스크린 등의 일부 요소에 대응하는 PR입니다. 자세한 내용은 아래를 참고 부탁드립니다.

* web manifest generation 적용
* apple 계열 홈 화면에 추가 generation 적용
* apple 휴대폰 splash 이미지 (apple-touch-startup-image) generation 적용
* favicon.ico는 기존의 것을 사용

> "generation 적용" 은 favicons-webpack-plugin 이 자동으로 생성해주는 컨텐츠임을 의미합니다.

## 💬 리뷰 요구사항

2023-09-29 05:02 UTC, jeongwusi requested changes
확인 한번만 해주십시옹!

2023-09-29 05:02 UTC, jeongwusi commented on client/index.html
>      <link rel="icon" type="image/x-icon" href="/assets/favicon.ico" />
이 부분은 적용을 안하신건가용?

2023-09-29 05:02 UTC, jeongwusi commented on client/package.json
> +    "favicons": "^7.1.4",
이 친구는 사용을 하신건가용?

2023-09-29 05:14 UTC, solo5star commented on client/package.json
> +    "favicons": "^7.1.4",
favicons-webpack-plugin의 의존성이기 때문에 같이 설치하였습니다! (https://www.npmjs.com/package/favicons-webpack-plugin)

2023-09-29 05:15 UTC, solo5star commented on client/index.html
>      <link rel="icon" type="image/x-icon" href="/assets/favicon.ico" />
favicon.ico는 이 PR과는 별개로 기존 디자인을 계속 사용하고 홈 화면에 추가했을 때의 아이콘만 favicons-webpack-plugin 에서 generate합니다!

2023-09-30 04:36 UTC, jeongwusi approved these changes
나이스 코드~ 고생고생 ^^

2023-10-05 05:26 UTC, merged