storybook이 켜지지 않는 오류 해결 및 msw 적용
woowacourse-teams/2023-yozm-cafe pull request #501
Opened 2023-09-28 07:27 UTC by solo5star

## #️⃣ 연관된 이슈
close #496 
close #500 

## 📝 작업 내용
* storybook을 고쳤습니다.
* webpack devServer 환경과 동일하게 storybook에 QueryClientProvider, AuthProvider를 적용하였습니다.
* msw addon을 적용하였습니다.

성능 최적화 PR에서 적용한 캐시 버스팅 설정이 storybook과 충돌이 있었습니다. `[name].[contenthash].js` 설정을 storybook에 적용하면 bundle을 잘 불러오지 못하더라구요. 따라서 production 빌드 시에만 `[name].[contenthash].js` 설정이 적용되도록 해주었습니다.

webpack 설정에 임베드 되어있던 babel 설정을 .babelrc.js 파일로 별도로 분리했는데 storybook에서 읽어서 써야 하기 때문에 이런 구조로 변경하였습니다. 이 점 참고 부탁드립니다~!!

src/mocks 폴더에 있는 `export const` 를 `export default` 로 변경하였으니 이 점도 참고 부탁드립니다

## 💬 리뷰 요구사항
* 커밋 내역 확인 부탁드리겠습니다~!

2023-09-29 05:17 UTC, jeongwusi requested changes
확인해주십숑

2023-09-29 05:17 UTC, jeongwusi commented on client/.storybook/preview.tsx
> +      <QueryClientProvider client={queryClient}>
스토리북에서 리액트 쿼리가 필요한가욤?_?

2023-09-29 05:17 UTC, jeongwusi commented on client/.storybook/main.ts
> +      fastRefresh: true,
이런 기능도 있군여...?!

2023-09-29 05:17 UTC, jeongwusi commented on client/.storybook/preview.tsx
> +initialize();
여기 친구는 왜 설정을 해주셨죵?

2023-09-29 05:17 UTC, jeongwusi commented on client/webpack.production.js
> +    filename: '[name].[contenthash].js',
`[contenthash]`는 임의로 웹펙에서 부여하나요?

2023-09-29 05:34 UTC, solo5star commented on client/.storybook/preview.tsx
> +      <QueryClientProvider client={queryClient}>
음 이게 없으니 오류가 발생하더라구요. 아마 컴포넌트에서 useQuery를 사용해서 그런 것 같습니다.

2023-09-29 05:34 UTC, solo5star commented on client/.storybook/main.ts
> +      fastRefresh: true,
넵 그렇습니다

2023-09-29 05:34 UTC, solo5star commented on client/.storybook/preview.tsx
> +initialize();
msw addon의 initialize 입니다~!

2023-09-29 05:35 UTC, solo5star commented on client/webpack.production.js
> +    filename: '[name].[contenthash].js',
네 그렇습니다~ 빌드 후 계산될 값입니다

2023-09-30 04:39 UTC, jeongwusi approved these changes
나이스 코드~ 짱짱!

2023-10-05 05:57 UTC, merged