MSW, 개발 서버 등 API 서버를 쉽게 변경할 수 있는 명령줄(CLI) 옵션 지원
woowacourse-teams/2023-yozm-cafe pull request #504
Opened 2023-09-28 10:48 UTC by solo5star

## #️⃣ 연관된 이슈
close #503 

## 📝 작업 내용
* 명령줄 옵션으로 msw, dev 서버, prod 서버를 스위칭할 수 있는 기능을 추가하였습니다.
* 이제 `yarn start --profile msw` 와 같은 식으로 msw, dev 서버를 쉽게 전환할 수 있습니다.
* `--profile` 옵션을 사용하지 않을 시 기본 값으로 `msw` 가 사용됩니다. (`yarn start`)

## 💬 리뷰 요구사항
커맨드 라인의 디자인이 어떤지 봐주세요~

2023-09-29 05:22 UTC, jeongwusi requested changes
확인해주십셩!

2023-09-29 05:22 UTC, jeongwusi commented on client/scripts/start.js
> +  '--profile <profile>',
profile말고 mode는 어떠신가욤? mode가 이해하기 더 쉬운 느낌이네영 ㅎㅎ

2023-09-29 05:33 UTC, solo5star commented on client/scripts/start.js
> +  '--profile <profile>',
mode는 주어진 mode 간 상호 호환이 불가한 완전한 전환을 의미하는것에 가깝다고 생각합니다. (개인적으로)
msw와 dev서버를 상호 동시에 설정하여 사용 가능한 점도 고려하면 profile 쪽이 쫌 더 괜찮지 않을까요? 제 생각은 이렇습니다. 고니의 생각은 어떤가요?

2023-09-29 09:52 UTC, geuntaek1013 commented on client/scripts/start.js
> +  '--profile <profile>',
솔스 의견처럼 완전한 전환은 아니니 `profile`도 괜찮아 보입니다.

2023-09-29 09:55 UTC, geuntaek1013 approved these changes
고생하셨습니다~!!

2023-09-30 04:40 UTC, jeongwusi commented on client/scripts/start.js
> +  '--profile <profile>',
넹넹 좋습니닷

2023-09-30 04:40 UTC, jeongwusi approved these changes
나이스 코드~ 짱짱!

2023-09-30 04:56 UTC, merged