카페의 위치를 보여줄 수 있는 지도를 구현
woowacourse-teams/2023-yozm-cafe pull request #506
Opened 2023-09-29 04:41 UTC by jeongwusi

## #️⃣ 연관된 이슈

#444 

## 📝 작업 내용

- 성수 카페를 지도로 알 수 있는 기능을 추가하였습니다.
- 중심은 성수동카페거리입니다.
- 지도의 볼 수 있는 지역은 성수동으로 제한하였습니다.
- 만약 내위치를 알고 싶으나, 내가 성수동에 위치를 하고 있지 않으면 성수 카페 거리로 이동됩니다.
- **마커의 모달의 경우 멀티 루트로 생성되기 때문에 Theme이 적용되지 않아, 직접 스타일 코드를 입력하였습니다.**

## 💬 리뷰 요구사항

잘 부탁드립니다~

2023-09-29 04:42 UTC, solo5star commented
![image](https://github.com/woowacourse-teams/2023-yozm-cafe/assets/20203944/7039ed48-96e5-42ea-8805-c6969831ab00)

오우 Emoji

2023-09-29 05:10 UTC, solo5star requested changes
우선 이 정도 리뷰 작성하고 좀 더 자세히 본 후 추가 리뷰 달겠습니다~!! 지도 기능 구현하느라 수고 많으셨습니다 고니!

2023-09-29 05:10 UTC, solo5star commented on client/src/components/CafeMarkers.tsx
> +};
프로젝트 전반적으로 적용 가능한 훅인 것 같은데 hooks 폴더에 분리해도 좋을 것 같습니다~

2023-09-29 05:10 UTC, solo5star commented on client/src/constants/index.ts
> +export const INITIAL_ZOOM_SIZE = 17;
src/constants 라는 네임스페이스 문맥에서 INITIAL_CENTER, INITIAL_ZOOM_SIZE 는 전달하려는 내용이 모호한 것 같습니다 ..! 상수 이름에 좀 더 많은 정보가 포함되면 좋겠습니다

2023-09-29 05:10 UTC, solo5star commented on client/src/mocks/handlers.ts
> +    console.log('찾은 카페 갯수: ' + foundCafes.length);
지워주세요~!!

2023-09-29 05:10 UTC, solo5star commented on client/src/styles/GlobalStyle.ts
> +  }
side effects를 확인하셨나요? 👀

2023-09-29 06:18 UTC, solo5star commented
![image](https://github.com/woowacourse-teams/2023-yozm-cafe/assets/20203944/c700441b-0dc7-46f1-b217-995f4c960b06)

카페 마커가 모달 위에 나타나네요!

2023-09-29 06:20 UTC, solo5star commented
![image](https://github.com/woowacourse-teams/2023-yozm-cafe/assets/20203944/79f13a48-fae2-4f73-9d1f-02ef676483a4)

이런 오류도 발생하네요~! 확인 부탁드리겠습니다 🙇

2023-09-29 06:26 UTC, solo5star commented on client/src/components/CafeMap.tsx
> +};
CafeMap과 별개로 CafeMapListener가 따로 존재하는 이유가 무엇인가요? CafeMap에 같이 있어도 괜찮지 않나요? UI를 렌더링하는 컴포넌트 역할을 하는 것 같진 않는데 커스텀 훅으로도 괜찮지 않을까요? 🤔

2023-09-29 07:13 UTC, jeongwusi commented on client/src/client.ts
> +    const { longitude, latitude, longitudeDelta, latitudeDelta } = getDisplayPosition(map);
넹넹 getCafesNearLocation()는 longitude, latitude, longitudeDelta, latitudeDelta을 직접 받도록 수정하였으며, useCafesNearLocation 커스텀 훅에서 관련된 로직을 처리 하도록 리펙토링 하였습니당

2023-09-29 07:14 UTC, jeongwusi commented on client/src/types/index.ts
> +};
오옹오옹! 좋습니닷

2023-09-29 07:29 UTC, jeongwusi commented on client/src/types/index.ts
> +};
`CafeMapMarker`에서 `CafeMapLocationData`로 수정하였습니다!!

```js
export type CafeMapLocationData = {
  id: number;
  name: string;
  address: string;
  latitude: number;
  longitude: number;
};
```

2023-09-29 07:31 UTC, jeongwusi commented on client/src/mocks/handlers.ts
> +    console.log('찾은 카페 갯수: ' + foundCafes.length);
넹넹 지웟슴다

2023-09-29 08:58 UTC, jeongwusi commented on client/src/utils/Observer.ts
> +class Observer<T> {
Observer: 다른 객체의 상태가 변경될 때 알림을 받기를 원하는 모든 객체.
Observable: 상태가 관심 대상일 수 있는 모든 객체로, 다른 객체가 그에 대한 관심을 등록할 수 있는 객체.

2023-09-29 09:00 UTC, jeongwusi commented on client/src/utils/Observer.ts
> +class Observer<T> {
허허... Observable로 수정했어용

```js
type Subscriber = () => void;

class Observable<T> {
  protected subscribers: Subscriber[] = [];

  protected state: T;

  constructor(initialState: T) {
    this.state = initialState;
  }

  subscribe(subscriber: Subscriber) {
    this.subscribers.push(subscriber);
  }
.
.
.
```

2023-09-29 09:09 UTC, jeongwusi commented on client/src/components/CafeMarkers.tsx
> +};
```js
import { useSyncExternalStore } from 'react';
import type Observable from '../utils/Observable';

const useObservable = <T>(Observable: Observable<T>): [T, (state: T) => void] => {
  const state = useSyncExternalStore(
    (callback) => {
      Observable.subscribe(callback);

      return () => Observable.unsubscribe(callback);
    },
    () => Observable.getState(),
  );
  const dispatch = (state: T) => Observable.setState(state);
  return [state, dispatch];
};

export default useObservable;
```

커스텀 훅으로 분리했어용

2023-09-29 09:14 UTC, jeongwusi commented on client/src/constants/index.ts
> +export const INITIAL_ZOOM_SIZE = 17;
아래처럼 수정했습니당

```js
export const SUNGSU_CAFE_STREET_LOCATION = {
  lat: 37.543327,
  lng: 127.056738,
};

export const SUNGSU_MAP_INITIAL_ZOOM_SIZE = 17;
```

2023-09-29 09:21 UTC, solo5star commented on client/src/constants/index.ts
> +export const INITIAL_ZOOM_SIZE = 17;
성수의 정확한 영문 표기는 `Seongsu` 입니다~!! (https://www.juso.go.kr/support/AddressMainSearch.do?searchKeyword=%EC%84%B1%EC%88%98%EB%8F%99&dsgubuntext=&dscity1text=&dscounty1text=&dsemd1text=&dsri1text=&dssan1text=&dsrd_nm1text=&aotYn=N)

2023-09-29 09:28 UTC, jeongwusi commented on client/src/styles/GlobalStyle.ts
> +  }
지역에 있는 `cursor: pointer;`의 경우 삭제 처리 하였습니당

2023-09-29 09:33 UTC, solo5star commented on client/src/styles/GlobalStyle.ts
> +  }
좋습니다~!!

2023-09-30 07:02 UTC, solo5star approved these changes
리뷰 반영해주시느라 고생 많으셨습니다. Approve 드립니다 👍

2023-09-30 07:20 UTC, jeongwusi commented on client/src/constants/index.ts
> +export const INITIAL_ZOOM_SIZE = 17;
넹넹 수정했습니다 😇

2023-10-05 00:29 UTC, merged