카페 이미지가 drag & drop 되지 않도록 수정
woowacourse-teams/2023-yozm-cafe pull request #515
Opened 2023-09-29 09:11 UTC by solo5star

## #️⃣ 연관된 이슈
close #507 

## 📝 작업 내용
* 카페 이미지가 drag & drop 되지 않도록 수정했습니다.
* 이제 마우스 클릭으로 스와이프가 잘 동작합니다.
* `enableRolling` props를 전달하지 않은 실수도 고쳤습니다.

## 💬 리뷰 요구사항

2023-09-29 09:23 UTC, geuntaek1013 approved these changes

2023-09-29 09:45 UTC, geuntaek1013 requested changes
<img width="604" alt="스크린샷 2023-09-29 오후 6 43 54" src="https://github.com/woowacourse-teams/2023-yozm-cafe/assets/95906910/d6e0b173-66dd-4dc5-8336-4c99ec412d39">

로컬 환경에서 카페 이미지가 짤려서 나오는데 확인 한번만 부탁드려요:)

2023-09-29 09:46 UTC, solo5star commented
@geuntaek1013 이 PR에서 해결하고자 하는 문제랑 다른 것 같은데 새로 이슈를 만들고 향후 추가 작업이 필요할 듯 합니다...!

2023-09-30 02:29 UTC, jeongwusi requested changes
확인해주십셩

2023-09-30 02:29 UTC, jeongwusi commented on client/src/components/CafeCard.tsx
> +const CarouselImage = styled.img.attrs({ draggable: false })`
`draggable`이 저희 사이트에서는 불필요 할 것으로 보이네용!

좋습니당 ^^

2023-09-30 02:29 UTC, jeongwusi commented on client/src/components/ScrollSnapContainer.tsx
> +        enableRolling={enableRolling}
이 부분의 `enableRolling`에서 `enableRolling={enableRolling}` 이렇게 수정하신 이유가 있나요?

2023-09-30 04:32 UTC, solo5star commented on client/src/components/ScrollSnapContainer.tsx
> +        enableRolling={enableRolling}
예전에 props drilling을 해줘야 했던 것을 깜빡했었는데... 이걸 여기서 수정했습니다. ~ㅜ

2023-09-30 04:32 UTC, solo5star commented on client/src/components/CafeCard.tsx
> +const CarouselImage = styled.img.attrs({ draggable: false })`
그렇습니다 ㅎㅎ

2023-09-30 04:41 UTC, jeongwusi approved these changes
확인하였습니다! 고생하셨어요~

2023-10-05 05:32 UTC, merged