로딩 중을 표시하기 위한 컴포넌트를 제작한다.
woowacourse-teams/2023-yozm-cafe pull request #522
Opened 2023-10-01 05:36 UTC by jeongwusi

## #️⃣ 연관된 이슈

> 연관된 이슈 번호를 모두 작성해주세요

close #521 

로딩 스피너 컴포넌트 제작하였습니다~!~!

## 📝 작업 내용

![화면 기록 2023-10-01 오후 2 32 15](https://github.com/woowacourse-teams/2023-yozm-cafe/assets/122500517/56778422-ce2f-47f5-98bb-9fe848ac59ca)

## 💬 리뷰 요구사항

잘 부탁드립니다. 🙇🏻

2023-10-01 05:45 UTC, solo5star requested changes
리뷰 남겼습니다~! 확인 부탁드려용 🥹

2023-10-01 05:45 UTC, solo5star commented on client/src/components/Loader.tsx
> +  transform: translate3d(-50%, -50%, 0);
이것은 `display: flex`를 적용하면 필요없을 것 같아요!

2023-10-01 05:45 UTC, solo5star commented on client/src/components/Loader.tsx
> +  display: inline-block;
`LoaderContainer` 에서 `display: flex` 를 적용하면 `display: inline-block` 도 필요없을 듯 합니다!

2023-10-01 05:46 UTC, jeongwusi commented on client/src/components/Loader.tsx
> +  transform: translate3d(-50%, -50%, 0);
넹넹!

2023-10-01 05:46 UTC, jeongwusi commented on client/src/components/Loader.tsx
> +  display: inline-block;
넹넹!

2023-10-02 05:13 UTC, geuntaek1013 approved these changes
스피너 이쁘네요~!!

2023-10-02 05:20 UTC, solo5star approved these changes
수정 사항 확인했습니다~!! 👍👍 수고많으셨습니다

2023-10-05 00:21 UTC, merged