에러를 표시하기 위한 컴포넌트를 제작한다.
woowacourse-teams/2023-yozm-cafe pull request #524
Opened 2023-10-01 08:13 UTC by jeongwusi

## #️⃣ 연관된 이슈

close #523 

## 📝 작업 내용

- 에러를 위한 페이지를 생성하였습니다.
- 애니메이션을 추가하여 아이콘이 살짝 움직이게 하였습니다.

https://github.com/woowacourse-teams/2023-yozm-cafe/assets/122500517/69a273fa-0c8b-45d5-a13f-4c820ea27008

## 💬 리뷰 요구사항

잘 부탁드립니다.

2023-10-02 04:41 UTC, solo5star requested changes
굿~~ 작업하시느라 고생 많으셨습니다! 에러 아이콘이 둥둥 뛰는 모습이 아주 좋네요

2023-10-02 04:41 UTC, solo5star commented on client/src/pages/ErrorPage.tsx
> +          <Button $fullWidth={true}>홈으로 돌아가기</Button>
```suggestion
          <Button $fullWidth>홈으로 돌아가기</Button>
```
이건 생략 가능합니다!

2023-10-02 04:41 UTC, solo5star commented on client/src/pages/ErrorPage.tsx
> +`;
혹시 `width` 값을 고정으로 줘야 할 이유가 있을까요? width를 고정하기보다는 자식 요소의 크기에 따라 결정되는 편이 좋을 것 같습니다

2023-10-02 05:19 UTC, geuntaek1013 requested changes
고생하셨습니다. 간단한 리뷰 확인 부탁드립니다.

2023-10-02 05:19 UTC, geuntaek1013 commented on client/src/pages/ErrorPage.tsx
> +`;
저도 궁금합니다. 고정 값으로 두신 이유가 있으실까요?🤔

2023-10-04 14:34 UTC, jeongwusi commented on client/src/pages/ErrorPage.tsx
> +          <Button $fullWidth={true}>홈으로 돌아가기</Button>
넷넷!

2023-10-04 14:38 UTC, jeongwusi commented on client/src/pages/ErrorPage.tsx
> +`;
현재 버튼 컴포넌트의 `$fullWidth`을 이용해서 크기를 조절할 수 있습니다. 

하지만 부모 컴포넌트에 width 값을 주지 않으면 버튼의 크기가 글자의 크기에 딱 맞게 되어 의도하지 않는 디자인이 됩니다.

그리고 현재의 구현 방식은 로그인 버튼을 구현한 방식과 같습니다~~
<img width="459" alt="스크린샷 2023-10-04 오후 11 36 23" src="https://github.com/woowacourse-teams/2023-yozm-cafe/assets/122500517/05169086-bc07-45ff-9b04-3e06b3e5d489">

2023-10-04 17:05 UTC, solo5star approved these changes
변경사항 확인했습니다~!

2023-10-05 00:24 UTC, merged