Toast 컴포넌트를 제작한다.
woowacourse-teams/2023-yozm-cafe pull request #526
Opened 2023-10-02 03:23 UTC by jeongwusi

## #️⃣ 연관된 이슈

close #525 

## 📝 작업 내용
- Toast 컴포넌트를 구현하였습니다.
- 스타일 같은 경우 임의로 넣었습니다.
- 색상은 저희 theme에 정의된 것을 사용하였습니다.
  - primary: '#F08080',
   - error: '#F14646',
   - warning: '#EF8523',
   - success: '#31A115',

https://github.com/woowacourse-teams/2023-yozm-cafe/assets/122500517/7b17930b-a033-49ed-8d6e-9234ccb9c7bb

https://github.com/woowacourse-teams/2023-yozm-cafe/assets/122500517/1c03b2b7-41df-42d3-b5b4-06b1de1a41b7

https://github.com/woowacourse-teams/2023-yozm-cafe/assets/122500517/5adf69db-fc94-47eb-833f-d25ae0c88bf9

https://github.com/woowacourse-teams/2023-yozm-cafe/assets/122500517/7a07ce18-4971-4453-8733-b61d95391e04

## 💬 리뷰 요구사항

확인해주십셩

2023-10-02 04:46 UTC, solo5star requested changes
멋진 토스트 잘 보았습니다 👍 잘 만들어주셨군요 🥳 외부에서 `Toast`를 어떻게 사용할 수 있을지가 감이 안 잡히는데 이 부분에 대해서 설명 추가해주시면 감사하겠습니다 🙇

2023-10-02 04:46 UTC, solo5star commented on client/src/pages/Toast.tsx
> +  $gap?: string;
외부에서 사용할 땐 dolar sign을 안붙히도록 할 수 없을까요? 🥹

2023-10-02 04:46 UTC, solo5star commented on client/src/pages/Toast.tsx
> +    $flexDirection = 'column',
이걸 바꿔서 사용할 케이스가 있을까요?

2023-10-02 04:46 UTC, solo5star commented on client/src/pages/Toast.tsx
> +  }, []);
부모가 이 컴포넌트를 사용하는 건가요? 그렇다면 토스트 메세지가 사라진 사실을 부모는 어떻게 알고 지울 수 있을까요?

2023-10-02 05:33 UTC, geuntaek1013 approved these changes
고생하셨습니다~!!👍

2023-10-02 05:33 UTC, geuntaek1013 commented on client/src/pages/Toast.tsx
> +  $gap?: string;
@solo5star 혹시 외부에서 사용할 때 `$`을 피하는 이유가 있으신가요?

2023-10-02 05:33 UTC, geuntaek1013 commented on client/src/pages/Toast.tsx
> +  }, []);
저도 궁금합니다!!ㅎㅎ

2023-10-02 09:29 UTC, solo5star commented on client/src/pages/Toast.tsx
> +  $gap?: string;
굳이 쓸 필요가 없다고 생각합니다 ㅎㅎ

2023-10-02 09:30 UTC, solo5star commented on client/src/pages/Toast.tsx
> +  $gap?: string;
dollar sign이 어떠한 특별한 의미를 나타내는 것은 아니기 때문이라 생각해요

2023-10-04 07:14 UTC, jeongwusi commented on client/src/pages/Toast.tsx
> +  $gap?: string;
넹넹 스타일을 고정시키면서 관련된 props는 삭제되었습니다.

2023-10-04 07:15 UTC, jeongwusi commented on client/src/pages/Toast.tsx
> +    $flexDirection = 'column',
넹넹 스타일을 고정시키면서 관련된 해당 props는 삭제되었습니당

2023-10-04 07:16 UTC, jeongwusi commented on client/src/pages/Toast.tsx
> +  }, []);
넹넹 Context API로 수정하면서 관련된 로직은 삭제하였습니다.

2023-10-04 07:27 UTC, jeongwusi commented
> 멋진 토스트 잘 보았습니다 👍 잘 만들어주셨군요 🥳 외부에서 `Toast`를 어떻게 사용할 수 있을지가 감이 안 잡히는데 이 부분에 대해서 설명 추가해주시면 감사하겠습니다 🙇

## 리뷰를 반영하여 다음과 같이 수정하였습니다.
- Toast 컴포넌트를 Context API를 이용하여 전역에서 관리되도록 수정
- 조건부 렌더링을 통해 사용될 때만 DOM에 반영되고 5초 후 삭제
- 스타일은 아래에서 나오도록 고정
- props는 2개만 받을 수 있도록 수정 (색상은 이전과 동일합니다.)
  - 예시: `showToast('색상', '메시지');`

## useToast는 다음과 같이 사용하실 수 있습니다.
```js
import { useToast } from '../context/ToastContext';

const Example = () => {
  const showToast = useToast();

  const handleShowToast = () => {
    showToast('default', '작업이 성공적으로 완료되었습니다.');
  };

  return (
    <div>
      <button onClick={handleShowToast}>토스트 메시지 띄우기</button>
    </div>
  );
};

export default Example;
```
## 실제 프로젝트에 적용된 예시

https://github.com/woowacourse-teams/2023-yozm-cafe/assets/122500517/401e6f2d-1841-445a-920c-f68fd75fa743

2023-10-04 07:42 UTC, solo5star requested changes
수고많으셨습니다 고니!! 리뷰 확인부탁드려요🙏

2023-10-04 07:42 UTC, solo5star commented on client/src/context/ToastContext.tsx
> +  ${({ $variant }) => ToastColorVariants[$variant || 'default']}
```suggestion
  ${({ $variant }) => ToastColorVariants[$variant]}
```
`$variant` 는 required props인 것 같은데 `|| 'default'` 처리가 필요없지 않을까요?

2023-10-04 07:42 UTC, solo5star commented on client/src/context/ToastContext.tsx
> +    throw new Error('useToast를 올바르게 사용하지 않았습니다.');
```suggestion
    throw new Error('부모 트리에서 ToastProvider를 사용해주세요');
```
이렇게 메세지를 바꾸는 것이 직관적이지 않을까요!?

2023-10-04 07:42 UTC, solo5star commented on client/src/context/ToastContext.tsx
> +    }, 5000);
showToast가 5초 이내에 2, 3번씩 호출되면 동작이 깨질 것 같은데 재호출되었을 때 이전 `setTimeout`을 clean-up 해줘야 하지 않을까요?

2023-10-04 07:42 UTC, solo5star commented on client/src/context/ToastContext.tsx
> +  };
`ToastContext`에도 동일한 `setTimeout` 로직이 있던데 어느 것이 진짜죠!?

2023-10-04 07:42 UTC, solo5star commented on client/src/context/ToastContext.tsx
> +  };
```suggestion
  const showToast = (message: string, options?: Partial<{ variant: ToastVariant }>) => {
    const { variant = 'default' } = options ?? {};
    setToastState({ variant, message });
  };
```

사용 케이스를 고려해보았을 때 `variant`는 일반적으로 `'default'`를 많이 사용하지 않을까요? 고니가 생각하기엔 어떤가요?

제 생각엔 굳이(?) 명시하지 않아도 바로 `'default'`로 사용할 수 있는 함수로 디자인한다면 더 괜찮을 것 같습니다!! suggestion을 참고해주세용

2023-10-04 07:49 UTC, jeongwusi commented on client/src/context/ToastContext.tsx
> +  ${({ $variant }) => ToastColorVariants[$variant || 'default']}
아하... 저거 아마 예전에 하면서 오류 나와서 했던 처리 같은데... 지금은 불필요하네용 삭제했슴다

2023-10-04 07:53 UTC, jeongwusi commented on client/src/context/ToastContext.tsx
> +    throw new Error('useToast를 올바르게 사용하지 않았습니다.');
좋습니닷!

2023-10-04 08:29 UTC, jeongwusi commented on client/src/context/ToastContext.tsx
> +    }, 5000);
이게 DOM에서 삭제가 안되서 넣었는데 지금은 괜찮네용... 해당 로직은 지우도록 하겠슴다

2023-10-04 08:29 UTC, jeongwusi commented on client/src/context/ToastContext.tsx
> +  };
여기를 살리면 될 거 같아용

2023-10-04 08:30 UTC, jeongwusi commented on client/src/context/ToastContext.tsx
> +  };
```
'{ showToast: (message: string, options?: Partial<{ variant: ToastVariant; }> | undefined) => void; }' 형식은 'ToastContextType' 형식에 할당할 수 없습니다.
  'showToast' 속성의 형식이 호환되지 않습니다.
    '(message: string, options?: Partial<{    variant: ToastVariant;}>) => void' 형식은 '(variant: ToastVariant, message: string) => void' 형식에 할당할 수 없습니다.
      'options' 및 'message' 매개 변수의 형식이 호환되지 않습니다.
        'string' 유형에 'Partial<{ variant: ToastVariant; }>' 유형과 공통적인 속성이 없습니다.ts(2322)
index.d.ts(371, 9): 필요한 형식은 여기에서 'IntrinsicAttributes & ProviderProps<ToastContextType | undefined>' 형식에 선언된 'value' 속성에서 가져옵니다.

(property) React.ProviderProps<ToastContextType | undefined>.value: ToastContextType | undefined
```

위와 같은 오류가 나오네용...

2023-10-04 08:54 UTC, solo5star approved these changes
작업하신 내용 확인완료했어요~~!! 굿 아주 좋스비낟

2023-10-04 08:56 UTC, jeongwusi commented on client/src/context/ToastContext.tsx
> +  };
보류 하는 걸루...ㅎ.ㅎ

2023-10-05 00:18 UTC, merged