unViewedCafe batch insert로 개선하기
woowacourse-teams/2023-yozm-cafe pull request #541
Opened 2023-10-06 05:14 UTC by hum02

## #️⃣ 연관된 이슈

- #539 

## 📝 작업 내용
- CafeCustomRepositoryImpl에 batch insert기능을 개발했습니다.
- mysql bulk insert사용을 위해 rewriteBatchedStatements옵션을 추가했습니다.
- 이 변경으로 인해 테스트를 조금 수정했습니다.
-
아직 완성되진 않았는데 과정에서 대한 이해를 위해 정리한 포스팅 공유하겠슴다,
https://velog.io/@ttomy/batch-insert

## 💬 리뷰 요구사항
- **authService에 memberrepository.flush()를 호출하고 있습니다.**
왜 이렇게 했는지는 flush()를 삭제해보고 authserviceTest를 실행해보면 알 수 있는데요...
batch insert를 위해 member의 id가 필요한데 이게 member.save()작업이 대기 중이면
참조키 오류로 예외가 발생합니다.
이 때문에 flush()를 했는데 위험한 상황이 있을까요? 더 좋은 방법이 있을까요?

2023-10-06 09:02 UTC, green-kong approved these changes
코멘트 몇개 남기긴 했는데, 크리티컬한 내용들은 없어서 어프루브 하겠습니다.
`flush()`에 대해선 음... 고민을 해보기는 했는데 마땅히 떠오르는 방법은 없네요 ㅠ
다른 분들이 좋은 방법을 말씀해주시면 반영해도 좋을 것 같구요.
아니면 이대로 merge하고 추후에 더 좋은 방법을 찾아 보는 것도 좋을 것 같아요.
연휴 간 작업하신것 같은데 당신의 노고에 박수를 보냅니다👏👏👏👏

2023-10-06 14:06 UTC, green-kong commented
또치또치또치
갑자기 샤워하다가 든 생각인데요
`@TransactionalEventListener(phase = TransactionPhase.AFTER_COMMIT)`
`@Transactional(propagation = Propagation.REQUIRES_NEW)`
이거 두개로 해결할 수도 있지 않을까요????

flush() 대신에 이벤트를 발행하는거죠.

그리고 이벤트 리스너(unViewedCafeService#refill~)쪽에서는 
`@TransactionalEventListener(phase = TransactionPhase.AFTER_COMMIT)` 을 하면 
커밋 이후에 동작하기에 DB에 member가 쓰여진 이후에 동작할거에요.  
그리고 `CafeService#getCafesForLoginMember` 에서도 

@Transactional
public List<CafeResponse> getCafesForLoginMember(final String memberId, final int size) {
    final Member member = getMemberByIdOrThrow(memberId);
    final List<UnViewedCafe> cafes = member.getNextUnViewedCafes(size);
    if(member.isUnviewedCafeLessThan(20)) {
        //이벤트 발행
    }

// 이하 동일

}

```  
이런식으로 변경할수 있겠네요.  

현재코드에서 authService랑 cafeService에서 UnviewedCafeService를 의존하고 있는데. 
서비스간 의존도도 분리될거 같아요.  

또한, 현재 코드에서 언뷰드카페를 리필하는 게 하나의 트랜잭션으로 묶여있는데, 이것도 참 웃기죠. 
회원가입할 때 카페가 추가 안되면, 회원가입이 안된다? 

카페 조회하는데 카페가 추가안되면 조회가 안된다? 
맥락상 맞지 않다라고 생각해요.  
위의 이벤트 방식을 사용하면 언뷰드카페의 추가 성공 실패와 상관없이 회원가입과 조회는 이뤄지지 않을까요? 
어떻게 생각하시나요????????  

사실 전 이거 생각하고 살짝 소름돋았는뎅 ㅎ

2023-10-07 15:30 UTC, donghae-kim requested changes
identity id 가 문제라면 이 정책을 바꿔도 되지 않을까? 라는 생각을 했었는데 그에대한 정리가 도치 블로그에 잘 나와있었네요. 변경감지를 사용하지 않는 것은 유감이지만 jdbc 사용 자체에 대해서는 이유가 확실한 것 같아서 좋았어요.

다만 flush.. 폴로도 이 의견을 커멘트에 달아놨네요. 흠.. 어떡하지 흠..

2023-10-07 15:30 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/service/UnViewedCafeService.java
> +            cafeRepository.saveUnViewedCafes(shuffledCafes, member);
단순하게 이렇게 진행되버리면 Member가 소유하고 있는 (20개 이하의 카페) 카페와 중복 카페들도 삽입되지 않나요 ?

이전에는 필터링을 통해 한번 검증했던 것 같은데 이번에는 그렇게 처리되지 않는 것 같아서요!

2023-10-07 15:30 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeCustomRepositoryImpl.java
> +    }
```
for (int i = 0; i < cafes.size(); i += INSERT_BATCH_SIZE) {
    List<Cafe> batch = cafes.subList(i, Math.min(i + INSERT_BATCH_SIZE, cafes.size()));
    batchInsert(batch, member.getId());
}
```

뭔가 이런식으로 진행하면 batchSize 단위로도 진행한다는 의미도 명시적으로 표현될 수 있어서 좋고 코드도 훨씬 깔끔해질것 같은데 어떻게 생각하시나요 ? (근데 작동은 안시켜보고 작성해서 잘못되었을수도있어요 ..)

+ 그냥 궁금한건데 INSERT_BATCH_SIZE가 110인 이유는 뭔가요 ?

2023-10-07 15:30 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/service/auth/AuthService.java
> +        memberRepository.flush();
헉
이건 어떡하지..

2023-10-08 02:14 UTC, hum02 commented on server/src/main/resources/META-INF/services/org.hibernate.boot.model.FunctionContributor
> +com.project.yozmcafe.config.CustomFunctionContributor
있는게 좋겠네요!

2023-10-08 02:18 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeCustomRepositoryImpl.java
> +    public void saveUnViewedCafes(final List<Cafe> cafes, final Member member) {
중간에 insert가 실패하면 전부 다 실패해야하는 한 트랜잭션의 작업이라 생각했어요!

예를 들어 우리 서비스에 카페 200개가 있을 때 110개의 1번 batch Insert를 성공했더라도 111번째의 insert에서 실패했다면 이전에 했던  batch insert도 롤백되는게 적절할 거라 생각해요

2023-10-08 02:19 UTC, hum02 commented on server/src/main/resources/application.yaml
> +    url: jdbc:mysql://localhost:20000/yozm-cafe?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC&rewriteBatchedStatements=true
까먹을 뻔.. 감사합니당

2023-10-08 02:27 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/service/UnViewedCafeService.java
> +            cafeRepository.saveUnViewedCafes(shuffledCafes, member);
헉 이걸 놓쳤네요! 꼼꼼한 오션👍

2023-10-08 03:21 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeCustomRepositoryImpl.java
> +    }
카페가 100여개 이기에 110 batch size로 한번의 쿼리로 처리하려 했습니다!
mysql에 bulk insert할 때 size에 대해 고려할 점은 최대패킷의 사이즈 설정이 어떻게 되어있느냐인데요.

https://stackoverflow.com/questions/3536103/mysql-how-many-rows-can-i-insert-in-one-single-insert-statement
기본적으로는 max_allowed_packet사이즈는 1mb정도로 설정이 되어있습니다.
사실 우리 unViewedCafe는 사실 cafe_id, member_id만 가진 작은 사이즈의 친구여서
더 큰 batch size로 설정할 수도 있겠지만, 우선 우리가 가진 카페를 한번에 처리할 정도면 더 크게 할 필요는 없겠다고 생각했어요

2023-10-08 03:23 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeCustomRepositoryImpl.java
> +            }
아래에서 오션의 제안대로 subList로 가독성을 개선해보았어요!

2023-10-09 05:05 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeCustomRepositoryImpl.java
> +    public void saveUnViewedCafes(final List<Cafe> cafes, final Member member) {
이 메서드호출하는 service layer에 @transactional이 붙어있어서 어차피 하나의 트랜잭션 안에서 동작하는거 아닌가해서 여쭤본거였어요!

2023-10-10 06:10 UTC, nuyh99 approved these changes
고생하셨습니다!!

개인적으로,
`MemberService`를 만들어서 `register()` 메서드에서 회원가입 이벤트를 발행하면 좋을 것 같습니다.
그리고 `UnViewedCafeService`에서는 트랜잭션 리스너로 커밋이 완료된 후 실행하면 될 것 같습니다!

2023-10-10 06:10 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeCustomRepositoryImpl.java
> +    }
```suggestion
final List<Object[]> parameters = cafes.stream()
    .map(cafe-> new Object[]{cafe.getId(), memberId})
    .toList();

jdbcTemplate.batchUpdate(sql, parameters);
```
이건 어떨까요??!

2023-10-10 06:10 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeCustomRepositoryImpl.java
> +    public void saveUnViewedCafes(final List<Cafe> cafes, final Member member) {
`UnViewedCafeRepository`가 탄생할 때가 아닌가 싶습니다!

2023-10-10 06:10 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeCustomRepositoryImpl.java
> +    private boolean isReachBatchSize(final int cafeIdx) {
```suggestion
private boolean reachedBatchSize(final int cafeIndex) {
```
는 어떨까요!

2023-10-12 06:33 UTC, donghae-kim approved these changes
고생하셨어도 요치

2023-10-12 06:33 UTC, donghae-kim approved these changes
고생하셨어도 요치

2023-10-12 06:38 UTC, merged