에러 핸들링을 위한 컴포넌트 추가 및 적용
woowacourse-teams/2023-yozm-cafe pull request #546
Opened 2023-10-08 09:43 UTC by solo5star

## #️⃣ 연관된 이슈
resolve #540 

## 📝 작업 내용
* 에러 핸들링을 위한 컴포넌트 추가 및 적용

### 👻 에러 종류
에러 종류를 다음과 같이 정의하였습니다.

* `e is unknown`
  - string, array 등 모든 타입
* `e is Error`
  - 정형화된 에러 객체
  - 모든 에러는 `Error`의 서브 타입이며 복구 불가능한 에러를 포함한다 (`TypeError` 등)
  - 개발자가 조치해야 한다
  - 예를 들면 `throw new Error('부모 트리에서 ToastProvider를 사용해주세요')` 가 해당된다.
* `e is AppError`
  - `Error`의 서브 타입이며, 복구 가능한 에러이다
  - 앱 내에서 의도적으로 발생시킨 에러
  - 사용자가 조치할 수 있다
  - 예를 들면 `throw new AppError('잘못된 텍스트입니다')` 가 해당된다.
* `e is NetworkError`
  - `AppError` 의 서브타입이며, 네트워크 장애에 해당되는 에러
* `e is APIError`
  - `AppError` 의 서브타입이며, API 호출 중 400, 500일 시 이 에러에 해당
  - 백엔드에서 응답한 에러 코드 및 메세지를 포함한다

### 👻 ErrorBoundary
* `ErrorBoundary`
  - 컴포넌트 렌더링 중 에러 발생 시 catch하는 컴포넌트
  - catch 시 대체 컴포넌트(fallback)을 렌더링 함
  - `fallbackRender`, `FallbackComponent` props로 대체 컴포넌트를 렌더링할 수 있다
  - `caught` props로 핸들링 할 에러의 범위를 지정할 수 있다

* `QueryErrorBoundary`
  - react-query 에서 `suspense: true` 로 사용할 시 유용한 에러 바운더리
  - query reset, network online 시 자동으로 retry 기능이 내장되어 있다

### 👻 useSilentLink
네트워크 상태를 감지하고 오프라인 혹은 온라인 전환될 시 토스트 메세지를 띄운다

## 💬 리뷰 요구사항
몹 프로그래밍 이후에 수정한 사항이 많이 있으니 꼭 확인 부탁드립니다!

2023-10-10 13:00 UTC, jeongwusi requested changes
간단하게 코멘트 확인 부탁드립니다^^

2023-10-10 23:39 UTC, solo5star commented on client/src/App.tsx
> +      retry: false,
3번까지 시도하는 시간이 너무 길어서 사용자 입장에선 답답할 수도 있을 것 같아 껐습니다.

2023-10-10 23:40 UTC, solo5star commented on client/src/hooks/useSilentLink.ts
> +        isOnline ? '인터넷이 다시 연결되었습니다' : '인터넷 연결이 끊어졌습니다. 확인해주세요',
🤣

2023-10-10 23:40 UTC, solo5star commented on client/src/errors/AppError.ts
> + */
💯

2023-10-10 23:41 UTC, solo5star commented on client/src/errors/APIError.ts
> +   * 서버 측에서 지정해 준 에러 코드 혹은 메세지가 포함되어 있는지 검사합니다
네~! 서버 측의 응답을 표시하기 위해 이렇게 만들었습니다. (혹은 분기 처리하기위해)

2023-10-11 00:13 UTC, jeongwusi commented on client/src/App.tsx
> +      retry: false,
넹넹

2023-10-11 00:13 UTC, jeongwusi commented on client/src/errors/APIError.ts
> +   * 서버 측에서 지정해 준 에러 코드 혹은 메세지가 포함되어 있는지 검사합니다
굿굿!

2023-10-11 00:14 UTC, jeongwusi approved these changes
확인하였습니다!

2023-10-11 01:10 UTC, geuntaek1013 approved these changes
고생하셨습니다~!! 간단한 리뷰 확인해주세요:)

2023-10-11 01:25 UTC, solo5star commented on client/src/errors/NetworkError.ts
> +class NetworkError extends AppError {
> Error의 서브 타입이며, 복구 가능한 에러이다
>
> 앱 내에서 의도적으로 발생시킨 에러
>
> 사용자가 조치할 수 있다

`AppError`를 위와 같이 정의하여서 `NetworkError`는 `AppError`의 서브 클래스가 될 수 있습니다. "사용자가 조치할 수 있다"는 말은 즉슨 저희가 이 에러를 핸들링하여 사용자에게 적절한 UI를 제공할 수 있다면 `AppError` 에 해당될 수 있습니다.

2023-10-11 01:27 UTC, solo5star commented on client/src/pages/ErrorPage.tsx
> +        {isExpectedError && <Sentence>{message}</Sentence>}
isExpectedError인 경우 사용자에게 표시할 만한 메세지가 나타날 것이기 때문에 적절한 코드라고 생각합니다!

2023-10-11 01:28 UTC, solo5star commented on client/src/pages/ErrorPage.tsx
> +import { Link, useRouteError } from 'react-router-dom';
넵 그렇습니다. 그리고 그 `error`를 어떻게 취급할 것인지는 개발자에게 달려있다고 할 수 있습니다.

2023-10-11 01:28 UTC, solo5star commented on client/src/context/ToastContext.tsx
> -  useEffect(() => {
그렇습니다~!

2023-10-11 01:29 UTC, solo5star commented on client/src/context/ToastContext.tsx
> +        <Container key={toastId}>
토스트 애니메이션을 다시 재생하기 위해 DOM이 새로운 DOM으로 재생성될 필요가 있고, 이를 `key` 속성을 통해 하고있다고 보심 됩니다!

2023-10-11 01:29 UTC, solo5star commented on client/src/components/ErrorBoundary.tsx
> +  static getDerivedStateFromError(error: Error): ErrorBoundaryState {
[React에서 error를 처리하는 방법](https://react.dev/reference/react/Component#catching-rendering-errors-with-an-error-boundary)이 그렇기 때문입니다!

2023-10-11 09:27 UTC, merged