카페정보 API 비회원인 경우의 기능 구현
woowacourse-teams/2023-yozm-cafe pull request #59
Opened 2023-07-18 06:51 UTC by green-kong

## #️⃣ 연관된 이슈

> resolved #47 

## 📝 작업 내용

> - [x] 비회원인 경우 DB에 저장된 순서로 5개의 카페정보를 응답한다.
> - [x] 요청받은 페이지가 최대 페이지를 초과한 경우 빈배열을 응답한다.

## 💬 리뷰 요구사항

> ^^ 감사합니다.

2023-07-18 06:51 UTC, hum02 approved these changes

2023-07-19 06:52 UTC, solo5star approved these changes

2023-07-19 06:52 UTC, solo5star commented on docker/docker-compose.yml
이거 server 디렉토리로 옮겼는데 여기 왜 있죵?.?

2023-07-19 10:46 UTC, nuyh99 requested changes

2023-07-19 10:46 UTC, nuyh99 commented on docker/docker-compose.yml
최신 Main이 아니라서 그런 게 아닐까요?!

2023-07-19 10:46 UTC, nuyh99 commented on docker/docker-compose.yml
이거 삭제해서 커밋해야 할 것 같습니다

2023-07-19 10:46 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/controller/CafeController.java
> +    public ResponseEntity<List<CafeDto>> getCafes(final @PageableDefault(size = 5) Pageable pageable) {
CafeDtos로 리턴하는 것도 좋을 것 같습니다

2023-07-19 10:46 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/controller/dto/cafe/AvailableTimeDto.java
> +public record AvailableTimeDto(String day, LocalDateTime open, LocalDateTime close, boolean opened) {
~Response, ~Request 등의 dto 네이밍도 좋을 것 같습니다

2023-07-19 10:46 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/controller/dto/cafe/CafeDto.java
> +                false,
isLiked가 false인 이유가 있을까요?

2023-07-19 10:46 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeRepository.java
> +            + "WHERE u.member.id = :memberId")
distinct는 빼도 되지 않을까요?
LEFT JOIN 보다는 RIGHT JOIN이 더 낫지 않을까 싶습니다.

2023-07-19 10:46 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/Cafes.java
> +            final int randomIdx = (int) Math.floor(Math.random() * (cafes.size() - 1));
!

2023-07-19 10:46 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/service/CafeService.java
> +@Transactional
readOnly = true 붙이면 좋을 것 같습니다.

2023-07-19 11:07 UTC, donghae-kim requested changes
고생하셨습니다 !~

2023-07-19 11:07 UTC, donghae-kim commented on server/src/main/java/com/project/yozmcafe/controller/dto/cafe/DetailDto.java
> +    public static DetailDto of(final Detail detail) {
정팩메 한개의 인자 받으면 컨벤션에 따라 from이 좋을 것 같아요!

2023-07-19 11:07 UTC, donghae-kim commented on server/build.gradle
> +    testImplementation 'io.rest-assured:rest-assured:5.3.1'
//restAssured
testImplementation 'io.rest-assured:rest-assured:5.3.1'

이런식으로 분리하면 좋을 것 같아요 밑에 db처럼

2023-07-19 11:07 UTC, donghae-kim commented on server/src/test/java/com/project/yozmcafe/util/AcceptanceContext.java
> +public class AcceptanceContext {
인수context를 만들어서 쓰면 좋을 것 같은데 pathParam를 사용하는 api를 사용하고 싶으면 따로 구현해줘야 하나요 ??!

2023-07-19 12:31 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/controller/dto/cafe/AvailableTimeDto.java
> +public record AvailableTimeDto(String day, LocalDateTime open, LocalDateTime close, boolean opened) {
controller 단에서는 확실히 언급하신 네이밍이 좋을 것 같습니다. 반영하겠습니다!

2023-07-19 12:34 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/controller/dto/cafe/CafeDto.java
> +                false,
비회원은 항상 isLiked가 false일텐데,
회원/비회원인 경우의 dto를 따로 만들 수도 있겠지만 
프론트가 isLiked필드가 없을 경우에 대한 추가적인 구현을 해야할 것 같아 이렇게 했습니다

2023-07-19 12:36 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/Cafes.java
> +            final int randomIdx = (int) Math.floor(Math.random() * (cafes.size() - 1));
헉 지우겠습니다!

2023-07-19 13:05 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeRepository.java
> +    @Query(value = "SELECT DISTINCT c FROM Cafe AS c "
맞습니다. 날카로운 피드백 감사합니다 😂

2023-07-19 13:06 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/service/CafeService.java
> +    private final CafeRepository cafes;
인정합니다. 통일하도록 반영하겠습니다

2023-07-19 13:09 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/service/CafeService.java
> +    private final CafeRepository cafes;
통일하겠습니다!

2023-07-19 13:09 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeRepository.java
> +    @Query(value = "SELECT DISTINCT c FROM Cafe AS c "
그렇네요! DISTINCT는 제거하겠습니다~

2023-07-19 13:10 UTC, green-kong commented on server/build.gradle
> +    testImplementation 'io.rest-assured:rest-assured:5.3.1'
반영할게요!

2023-07-20 04:09 UTC, donghae-kim approved these changes
고생하셨습니다 ~

2023-07-20 04:11 UTC, merged