홈 화면의 오른쪽 버튼들(CafeActionBar) 디자인 개선
woowacourse-teams/2023-yozm-cafe pull request #89
Opened 2023-07-20 13:32 UTC by solo5star

## #️⃣ 연관된 이슈
> 브랜치 이름이 잘못된 관계로 다시 PR을 생성하였습니다.

close #53 

## 📝 작업 내용

## 💬 리뷰 요구사항

2023-07-20 13:38 UTC, jeongwusi requested changes
확인해주세용~~!

2023-07-20 13:38 UTC, jeongwusi commented on client/src/components/CafeInfoModal.tsx
> +  box-shadow: ${({ theme }) => theme.shadow[3]};
저는 모달에 그림자가 필요 없다고 생각하는데 어떻게 생각하시나요?

2023-07-20 13:38 UTC, jeongwusi commented on client/src/components/CommentButton.tsx
> +  margin-top: 5px;
현재 좋아요 버튼에도 마진이 없어서 통일성을 지키기위해 마진은 없어도 될 거 같아요.

2023-07-20 13:38 UTC, jeongwusi commented on client/src/components/ShareButton.tsx
> +  margin-top: 5px;
여기도용~~

2023-07-21 01:42 UTC, geuntaek1013 commented on client/src/components/CafeInfoModal.tsx
> +  box-shadow: ${({ theme }) => theme.shadow[3]};
네, 어차피 이미지가 차지하는 영역 때문에 모달에 쉐도우는 필요 없어보이네요. 삭제하겠습니다.

2023-07-21 01:44 UTC, geuntaek1013 approved these changes

2023-07-21 01:47 UTC, geuntaek1013 commented on client/src/components/CommentButton.tsx
> +  margin-top: 5px;
네 제거 완료했습니다!!

2023-07-21 02:11 UTC, jeongwusi commented on client/src/components/CafeInfoModal.tsx
> +  box-shadow: ${({ theme }) => theme.shadow[3]};
넹넹

2023-07-21 02:12 UTC, jeongwusi approved these changes
확인하였습니당~!!

2023-07-21 02:12 UTC, merged