로그인 된 사용자에게 보여주는 카페정보에 좋아요 여부를 매핑하는 기능 구현
woowacourse-teams/2023-yozm-cafe pull request #96
Opened 2023-07-21 04:17 UTC by green-kong

## #️⃣ 연관된 이슈

> resolved #92 
> resolved #93 

## 📝 작업 내용

> 기존에 구현되어있지 않던 부분 추가 구현했습니다.
> 하는김에 #93 내용도 같이 반영했어요

2023-07-23 05:48 UTC, nuyh99 requested changes
고생하셨습니다!!
꼼꼼히 보다보니 이것저것 제 개인 생각을 많이 적은 것 같은데 기분 상하게 하는 것은 아닐 지 걱정되네요ㅠ

2023-07-23 05:48 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/service/CafeService.java
>      private final CafeRepository cafeRepository;
상수와 의존 간에 개행이 있으면 좋겠습니다!

2023-07-23 05:48 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/service/CafeService.java
> +        return cafeResponses;
```suggestion
return unViewedCafes.stream()
    .map(cafe -> CafeResponse.of(cafe, member.isLike(cafe))
    .toList();
```
이렇게도 좋을 것 같네요!

2023-07-23 05:48 UTC, nuyh99 commented on server/src/test/java/com/project/yozmcafe/service/CafeServiceTest.java
> +    @DisplayName("로그인 된 사용자의 안본 카페 목록을 조회한다.")
로그인 되지 않은 사용자의 경우도 있으면 좋겠습니다!

2023-07-23 05:48 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/LikedCafe.java
> +    public LikedCafe() {
protected가 아닌 이유가 궁금해요!

2023-07-23 05:48 UTC, nuyh99 commented on server/src/test/java/com/project/yozmcafe/domain/member/MemberTest.java
> +        Assertions.assertAll(
1. static import하면 좋겠습니다!
2. 추가로 Member의 addUnViewedCafes, removeUnViewedCafe의 예외 발생 케이스에 대한 테스트가 있으면 좋겠습니다.
3. 현재 true의 경우와 false인 경우를 한 메서드로 테스트하는데 분리해도 좋을 것 같아요.

2023-07-23 05:48 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/LikedCafe.java
> +        this(null, cafe, member);
생성자 체이닝👍

2023-07-23 05:48 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/domain/member/Member.java
> +                .anyMatch(likedCafe -> likedCafe.isSameCafe(cafe));
`cafe::isSameCafe` 로 바꿀 수 있다면 바꾸는 것이 좋을 것 같습니다!

2023-07-23 08:01 UTC, donghae-kim approved these changes
수정하면 좋을 것들에 대해서 이미 연어가 의견을 많이 남겨놓았더라고요 !
그래서 그 정도만 수정하면 될 것 같아서 저는 먼저 어프로브 남겨놓습니다!

2023-07-24 02:31 UTC, hum02 commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeRepository.java
> +    Slice<Cafe> findUnViewedCafesByMember(final Pageable pageable, final String memberId);
이 `@Param`에 관해서 제 환경에서는 에러가 발생하고 있어요!
![param 에러 메시지](https://github.com/woowacourse-teams/2023-yozm-cafe/assets/96762301/e4bb555c-1608-4c7c-b703-005c7616611b)

그래서 찾아보니 java 8+부터는 JPQL 메소드 매개변수명에 접근해 param어노테이션 없이도 파라미터 매핑이 가능하지만, javac -parameters 옵션이 있어야 가능합니다.
- reference
https://www.inflearn.com/questions/367372/param-%EC%83%9D%EB%9E%B5
https://zzang9ha.tistory.com/357#google_vignette

그런데 될때도 있고 안될 때도 있는 건 빌드할 때 이 옵션을 자동으로 넣어줬는냐에 따라 갈리는 듯 해요.
항상 넣어주는 건 아닌 듯 하니 `@Param`을 붙이는 쪽으로 통일하는 게 어떤지 제안합니다!

2023-07-24 08:19 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/domain/cafe/LikedCafe.java
> +    public LikedCafe() {
놓쳤네요 감사합니다!

2023-07-24 08:30 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/domain/cafe/CafeRepository.java
> +    Slice<Cafe> findUnViewedCafesByMember(final Pageable pageable, final String memberId);
오 좋은 가르침 감사합니다 도치!

2023-07-24 08:37 UTC, green-kong commented on server/src/main/java/com/project/yozmcafe/domain/member/Member.java
> +                .anyMatch(likedCafe -> likedCafe.isSameCafe(cafe));
음 순환참조 생길것 같은데 괜찮을 까요 확인한번 해주세요 ㅠ

2023-07-24 08:40 UTC, hum02 approved these changes

2023-07-24 08:44 UTC, nuyh99 commented on server/src/main/java/com/project/yozmcafe/domain/member/Member.java
> +                .anyMatch(likedCafe -> likedCafe.isSameCafe(cafe));
앗 제가 잘못 봤습니다. likedCafes의 타입도 Cafe인 줄 알았어요!

2023-07-24 11:31 UTC, donghae-kim approved these changes
고생하셨습니다~

2023-07-24 12:22 UTC, nuyh99 approved these changes

2023-07-24 12:23 UTC, merged